/*
Copyright IBM Corp. All Rights Reserved.

SPDX-License-Identifier: Apache-2.0
*/

package utils

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"io"
	"sync"
)

const randPoolSize = 16 * 16

var (
	poolMu  sync.Mutex
	poolPos = randPoolSize     // protected with poolMu
	pool    [randPoolSize]byte // protected with poolMu
)

var randChar = &poolRandReader{
	randReader: rand.Reader,
	pool:       []byte(`ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz`),
}

type poolRandReader struct {
	randReader io.Reader
	pool       []byte
}

func (r *poolRandReader) Read(p []byte) (int, error) {
	n, err := r.randReader.Read(p)
	if err != nil {
		return n, err
	}

	l := uint8(len(r.pool))
	for i := range p {
		p[i] = r.pool[p[i]%l]
	}
	return n, nil
}

// GenerateBytesUUID returns a UUID based on RFC 4122 returning the generated bytes
func GenerateBytesUUID() []byte {
	uuid := make([]byte, 16)

	poolMu.Lock()
	if poolPos == randPoolSize {
		_, err := io.ReadFull(rand.Reader, pool[:])
		if err != nil {
			poolMu.Unlock()
			panic(fmt.Sprintf("Error generating UUID: %s", err))
		}
		poolPos = 0
	}
	copy(uuid[:], pool[poolPos:(poolPos+16)])
	poolPos += 16
	poolMu.Unlock()

	// variant bits; see section 4.1.1
	uuid[8] = uuid[8]&^0xc0 | 0x80

	// version 4 (pseudo-random); see section 4.1.3
	uuid[6] = uuid[6]&^0xf0 | 0x40

	return uuid
}

// GenerateUUID returns a UUID based on RFC 4122
func GenerateUUID() string {
	uuid := GenerateBytesUUID()
	return idBytesToStr(uuid)
}

func idBytesToStr(id []byte) string {
	dst := make([]byte, 36)
	hex.Encode(dst[0:8], id[0:4])
	dst[8] = '-'
	hex.Encode(dst[9:13], id[4:6])
	dst[13] = '-'
	hex.Encode(dst[14:18], id[6:8])
	dst[18] = '-'
	hex.Encode(dst[19:23], id[8:10])
	dst[23] = '-'
	hex.Encode(dst[24:], id[10:16])
	return string(dst)
}

// GenerateUUIDOnlyLetters returns a UUID without digits
func GenerateUUIDOnlyLetters() string {
	uuid := make([]byte, 16)
	if _, err := io.ReadFull(randChar, uuid); err != nil {
		panic(err)
	}
	return string(uuid)
}
