/*
Copyright IBM Corp. All Rights Reserved.

SPDX-License-Identifier: Apache-2.0
*/

package view

import (
	"context"
	"fmt"
)

const (
	OK    = 200
	ERROR = 500
)

type Message struct {
	SessionID    string // Session Identifier
	ContextID    string // Context Identifier
	Caller       string // View Identifier of the caller
	FromEndpoint string // Endpoint identifier of the caller
	FromPKID     []byte // PK identifier of the caller
	Status       int32  // Message Status (OK, ERROR)
	Payload      []byte // Payload
	Ctx          context.Context
}

func (m *Message) String() string {
	return fmt.Sprintf("[session:%s,context:%s,caller:%s,endpoint:%s",
		m.SessionID,
		m.ContextID,
		m.Caller,
		m.FromEndpoint)
}

// SessionInfo contains information about a session and the remote peer.
type SessionInfo struct {
	// ID is the unique identifier for the logical session.
	// It is generated by the initiator and used to multiplex messages.
	ID string
	// Caller is the authenticated identity of the remote peer.
	// The communication layer guarantees that this identity matches the
	// public key used in the underlying secure transport (e.g., TLS certificate).
	Caller Identity
	// CallerViewID is the string identifier of the View that initiated
	// the session on the remote peer's side.
	CallerViewID string
	// Endpoint is the network address (e.g., IP:port) of the remote peer.
	Endpoint string
	// EndpointPKID is the cryptographically verified public key identifier
	// (hash) of the remote peer. The communication layer ensures that
	// this ID is bound to the verified transport-layer identity.
	EndpointPKID []byte
	// Closed is true if the session has been closed.
	Closed bool
}

func (i *SessionInfo) String() string {
	return fmt.Sprintf("session info [%s,%s,%s,%s,%s,%v]", i.ID, i.Caller, i.CallerViewID, i.Endpoint, i.EndpointPKID, i.Closed)
}

// Session encapsulates a communication channel to an endpoint
type Session interface {
	Info() SessionInfo

	// Send sends the payload to the endpoint
	Send(payload []byte) error

	// SendWithContext sends the payload to the endpoint with the passed context
	SendWithContext(ctx context.Context, payload []byte) error

	// SendError sends an error to the endpoint with the passed payload
	SendError(payload []byte) error

	// SendErrorWithContext sends an error to the endpoint with the passed payload and context
	SendErrorWithContext(ctx context.Context, payload []byte) error

	// Receive returns a channel of messages received from the endpoint
	Receive() <-chan *Message

	// Close releases all the resources allocated by this session
	Close()
}
