/*
Copyright IBM Corp All Rights Reserved.

SPDX-License-Identifier: Apache-2.0
*/

package runtimeconfig_test

import (
	. "github.com/onsi/ginkgo/v2"

	"github.com/hyperledger-labs/fabric-smart-client/integration"
	"github.com/hyperledger-labs/fabric-smart-client/integration/fabric/iou"
	"github.com/hyperledger-labs/fabric-smart-client/integration/fabric/runtimeconfig"
	"github.com/hyperledger-labs/fabric-smart-client/integration/nwo/fsc"
)

var _ = Describe("EndToEnd", func() {
	Describe("IOU Reconfiguration at Runtime With Websockets", Label("T1"), func() {
		s := NewTestSuite(fsc.WebSocket, integration.NoReplication, true)
		BeforeEach(s.Setup)
		AfterEach(s.TearDown)
		It("succeeded", s.TestSucceeded)
	})
})

type TestSuite struct {
	*integration.TestSuite
}

func NewTestSuite(commType fsc.P2PCommunicationType, nodeOpts *integration.ReplicationOptions, tlsEnabled bool) *TestSuite {
	return &TestSuite{TestSuite: integration.NewTestSuite(func() (*integration.Infrastructure, error) {
		return integration.Generate(StartPort(), integration.WithRaceDetection, runtimeconfig.Topology(&runtimeconfig.Opts{
			CommType:        commType,
			ReplicationOpts: nodeOpts,
			TLSEnabled:      tlsEnabled,
		})...)
	})}
}

func (s *TestSuite) TestSucceeded() {
	// The FSC nodes boot with only `fabric.enabled: true` in their core.yaml: the Fabric network
	// configuration and crypto material were generated by NWO, but not baked into any node. Inject
	// the full configuration into every FSC node at runtime before exercising the IOU flow.
	runtimeconfig.InjectAll(s.II)

	iou.InitApprover(s.II, "approver1")
	iou.InitApprover(s.II, "approver2")
	iouState := iou.CreateIOU(s.II, "", 10, "approver1")
	iou.CheckState(s.II, "borrower", iouState, 10)
	iou.CheckState(s.II, "lender", iouState, 10)
	iou.UpdateIOU(s.II, iouState, 5, "approver2")
	iou.CheckState(s.II, "borrower", iouState, 5)
	iou.CheckState(s.II, "lender", iouState, 5)
}
