linters:
  enable:
    - dupl
    - errname
    - errorlint
    - errcheck
    # The linter 'execinquery' is deprecated (since v1.58.0) due to: The repository of the linter has been archived by the owner.
    - forcetypeassert
    - ginkgolinter
    - goconst
    - gocritic
    - godot
    - gosimple
    - gofumpt
    - gosec
    - govet
    - goimports
    - ireturn
    - ineffassign
    - lll
    - misspell
    - nilerr
    - prealloc
    - promlinter
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
    - gocognit

linters-settings:
  errcheck:
    # Report about not checking of errors in type assertions: `a := b.(MyStruct)`.
    # Such cases aren't reported by default.
    # Default: false
    check-type-assertions: true
  errorlint:
    # Check whether fmt.Errorf uses the %w verb for formatting errors.
    # See the https://github.com/polyfloyd/go-errorlint for caveats.
    # Default: true
    errorf: true
    # Check for plain type assertions and type switches.
    # Default: true
    asserts: false
    # Check for plain error comparisons.
    # Default: true
    comparison: true
  govet:
    # Enable all analyzers.
    # Default: false
    enable-all: true
    disable:
      - fieldalignment
  lll:
    # Max line length, lines longer will be reported.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option.
    # Default: 120.
    line-length: 120
  gofumpt:
    # Choose whether to use the extra rules.
    # Default: false
    extra-rules: true
  gosec:
    # To specify a set of rules to explicitly exclude.
    # Available rules: https://github.com/securego/gosec#available-rules
    excludes:
      - G204
      # G404: Use of weak random number generator (math/rand instead of crypto/rand)
      - G404
      # G306: Expect WriteFile permissions to be 0600 or less
      - G306
  gocognit:
    # Minimal code complexity to report.
    # Default: 30 (but we recommend 10-20)
    min-complexity: 15
  revive:
    ignore-generated-header: true
    enable-all-rules: true
    rules:
      - name: argument-limit
        arguments: [4]
      - name: line-length-limit
        arguments: [120]
      - name: file-header
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: banned-characters
        disabled: true
      - name: cognitive-complexity
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: function-length
        disabled: true
      - name: function-result-limit
        arguments: [3]
      - name: add-constant
        disabled: true
      - name: unhandled-error
        arguments: ["fmt.Printf", "fmt.Println"]
      - name: confusing-naming
        # Due to a bug, this rule fails multiple implementations of the same interface.
        disabled: true
  ireturn:
    # By default, it allows using errors, empty interfaces, anonymous interfaces,
    # and interfaces provided by the standard library.
    allow:
      - error
      - empty
      - anon
      - stdlib
      - generic
      - (or|er)$
      - T
      - github.com/prometheus/client_golang/prometheus.Counter
      - github.com/prometheus/client_golang/prometheus.Gauge
      - github.com/prometheus/client_golang/prometheus.Histogram

issues:
  # The list of ids of default excludes to include or disable.
  # https://golangci-lint.run/usage/false-positives/#default-exclusions
  # Default: []
  include:
    - EXC0001
    - EXC0002
    - EXC0003
    - EXC0004
    - EXC0005
    - EXC0006
    - EXC0007
    - EXC0009
    - EXC0010
    - EXC0011
    - EXC0012
    - EXC0013
    - EXC0014
  # Which dirs to skip: issues from them won't be reported.
  # Can use regexp here: `generated.*`, regexp is applied on full path,
  # including the path prefix if one is set.
  # Default value is empty list,
  # but default dirs are skipped independently of this option's value (see skip-dirs-use-default).
  # "/" will be replaced by current OS file path separator to properly work on Windows.
  exclude-dirs:
    - wgclient # may not be a priority
    - sigverification # may not be a priority

  # Enables skipping of directories:
  # - vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  # Default: true
  exclude-dirs-use-default: false