// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/hyperledger-labs/fabric-smart-client/platform/fabric/core/generic/chaincode"
	"github.com/hyperledger-labs/fabric-smart-client/platform/fabric/driver"
)

type Discover struct {
	CallStub        func() ([]driver.DiscoveredPeer, error)
	callMutex       sync.RWMutex
	callArgsForCall []struct {
	}
	callReturns struct {
		result1 []driver.DiscoveredPeer
		result2 error
	}
	callReturnsOnCall map[int]struct {
		result1 []driver.DiscoveredPeer
		result2 error
	}
	ChaincodeVersionStub        func() (string, error)
	chaincodeVersionMutex       sync.RWMutex
	chaincodeVersionArgsForCall []struct {
	}
	chaincodeVersionReturns struct {
		result1 string
		result2 error
	}
	chaincodeVersionReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	WithFilterByMSPIDsStub        func(...string) driver.ChaincodeDiscover
	withFilterByMSPIDsMutex       sync.RWMutex
	withFilterByMSPIDsArgsForCall []struct {
		arg1 []string
	}
	withFilterByMSPIDsReturns struct {
		result1 driver.ChaincodeDiscover
	}
	withFilterByMSPIDsReturnsOnCall map[int]struct {
		result1 driver.ChaincodeDiscover
	}
	WithForQueryStub        func() driver.ChaincodeDiscover
	withForQueryMutex       sync.RWMutex
	withForQueryArgsForCall []struct {
	}
	withForQueryReturns struct {
		result1 driver.ChaincodeDiscover
	}
	withForQueryReturnsOnCall map[int]struct {
		result1 driver.ChaincodeDiscover
	}
	WithImplicitCollectionsStub        func(...string) driver.ChaincodeDiscover
	withImplicitCollectionsMutex       sync.RWMutex
	withImplicitCollectionsArgsForCall []struct {
		arg1 []string
	}
	withImplicitCollectionsReturns struct {
		result1 driver.ChaincodeDiscover
	}
	withImplicitCollectionsReturnsOnCall map[int]struct {
		result1 driver.ChaincodeDiscover
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Discover) Call() ([]driver.DiscoveredPeer, error) {
	fake.callMutex.Lock()
	ret, specificReturn := fake.callReturnsOnCall[len(fake.callArgsForCall)]
	fake.callArgsForCall = append(fake.callArgsForCall, struct {
	}{})
	stub := fake.CallStub
	fakeReturns := fake.callReturns
	fake.recordInvocation("Call", []interface{}{})
	fake.callMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Discover) CallCallCount() int {
	fake.callMutex.RLock()
	defer fake.callMutex.RUnlock()
	return len(fake.callArgsForCall)
}

func (fake *Discover) CallCalls(stub func() ([]driver.DiscoveredPeer, error)) {
	fake.callMutex.Lock()
	defer fake.callMutex.Unlock()
	fake.CallStub = stub
}

func (fake *Discover) CallReturns(result1 []driver.DiscoveredPeer, result2 error) {
	fake.callMutex.Lock()
	defer fake.callMutex.Unlock()
	fake.CallStub = nil
	fake.callReturns = struct {
		result1 []driver.DiscoveredPeer
		result2 error
	}{result1, result2}
}

func (fake *Discover) CallReturnsOnCall(i int, result1 []driver.DiscoveredPeer, result2 error) {
	fake.callMutex.Lock()
	defer fake.callMutex.Unlock()
	fake.CallStub = nil
	if fake.callReturnsOnCall == nil {
		fake.callReturnsOnCall = make(map[int]struct {
			result1 []driver.DiscoveredPeer
			result2 error
		})
	}
	fake.callReturnsOnCall[i] = struct {
		result1 []driver.DiscoveredPeer
		result2 error
	}{result1, result2}
}

func (fake *Discover) ChaincodeVersion() (string, error) {
	fake.chaincodeVersionMutex.Lock()
	ret, specificReturn := fake.chaincodeVersionReturnsOnCall[len(fake.chaincodeVersionArgsForCall)]
	fake.chaincodeVersionArgsForCall = append(fake.chaincodeVersionArgsForCall, struct {
	}{})
	stub := fake.ChaincodeVersionStub
	fakeReturns := fake.chaincodeVersionReturns
	fake.recordInvocation("ChaincodeVersion", []interface{}{})
	fake.chaincodeVersionMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Discover) ChaincodeVersionCallCount() int {
	fake.chaincodeVersionMutex.RLock()
	defer fake.chaincodeVersionMutex.RUnlock()
	return len(fake.chaincodeVersionArgsForCall)
}

func (fake *Discover) ChaincodeVersionCalls(stub func() (string, error)) {
	fake.chaincodeVersionMutex.Lock()
	defer fake.chaincodeVersionMutex.Unlock()
	fake.ChaincodeVersionStub = stub
}

func (fake *Discover) ChaincodeVersionReturns(result1 string, result2 error) {
	fake.chaincodeVersionMutex.Lock()
	defer fake.chaincodeVersionMutex.Unlock()
	fake.ChaincodeVersionStub = nil
	fake.chaincodeVersionReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *Discover) ChaincodeVersionReturnsOnCall(i int, result1 string, result2 error) {
	fake.chaincodeVersionMutex.Lock()
	defer fake.chaincodeVersionMutex.Unlock()
	fake.ChaincodeVersionStub = nil
	if fake.chaincodeVersionReturnsOnCall == nil {
		fake.chaincodeVersionReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.chaincodeVersionReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *Discover) WithFilterByMSPIDs(arg1 ...string) driver.ChaincodeDiscover {
	fake.withFilterByMSPIDsMutex.Lock()
	ret, specificReturn := fake.withFilterByMSPIDsReturnsOnCall[len(fake.withFilterByMSPIDsArgsForCall)]
	fake.withFilterByMSPIDsArgsForCall = append(fake.withFilterByMSPIDsArgsForCall, struct {
		arg1 []string
	}{arg1})
	stub := fake.WithFilterByMSPIDsStub
	fakeReturns := fake.withFilterByMSPIDsReturns
	fake.recordInvocation("WithFilterByMSPIDs", []interface{}{arg1})
	fake.withFilterByMSPIDsMutex.Unlock()
	if stub != nil {
		return stub(arg1...)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Discover) WithFilterByMSPIDsCallCount() int {
	fake.withFilterByMSPIDsMutex.RLock()
	defer fake.withFilterByMSPIDsMutex.RUnlock()
	return len(fake.withFilterByMSPIDsArgsForCall)
}

func (fake *Discover) WithFilterByMSPIDsCalls(stub func(...string) driver.ChaincodeDiscover) {
	fake.withFilterByMSPIDsMutex.Lock()
	defer fake.withFilterByMSPIDsMutex.Unlock()
	fake.WithFilterByMSPIDsStub = stub
}

func (fake *Discover) WithFilterByMSPIDsArgsForCall(i int) []string {
	fake.withFilterByMSPIDsMutex.RLock()
	defer fake.withFilterByMSPIDsMutex.RUnlock()
	argsForCall := fake.withFilterByMSPIDsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Discover) WithFilterByMSPIDsReturns(result1 driver.ChaincodeDiscover) {
	fake.withFilterByMSPIDsMutex.Lock()
	defer fake.withFilterByMSPIDsMutex.Unlock()
	fake.WithFilterByMSPIDsStub = nil
	fake.withFilterByMSPIDsReturns = struct {
		result1 driver.ChaincodeDiscover
	}{result1}
}

func (fake *Discover) WithFilterByMSPIDsReturnsOnCall(i int, result1 driver.ChaincodeDiscover) {
	fake.withFilterByMSPIDsMutex.Lock()
	defer fake.withFilterByMSPIDsMutex.Unlock()
	fake.WithFilterByMSPIDsStub = nil
	if fake.withFilterByMSPIDsReturnsOnCall == nil {
		fake.withFilterByMSPIDsReturnsOnCall = make(map[int]struct {
			result1 driver.ChaincodeDiscover
		})
	}
	fake.withFilterByMSPIDsReturnsOnCall[i] = struct {
		result1 driver.ChaincodeDiscover
	}{result1}
}

func (fake *Discover) WithForQuery() driver.ChaincodeDiscover {
	fake.withForQueryMutex.Lock()
	ret, specificReturn := fake.withForQueryReturnsOnCall[len(fake.withForQueryArgsForCall)]
	fake.withForQueryArgsForCall = append(fake.withForQueryArgsForCall, struct {
	}{})
	stub := fake.WithForQueryStub
	fakeReturns := fake.withForQueryReturns
	fake.recordInvocation("WithForQuery", []interface{}{})
	fake.withForQueryMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Discover) WithForQueryCallCount() int {
	fake.withForQueryMutex.RLock()
	defer fake.withForQueryMutex.RUnlock()
	return len(fake.withForQueryArgsForCall)
}

func (fake *Discover) WithForQueryCalls(stub func() driver.ChaincodeDiscover) {
	fake.withForQueryMutex.Lock()
	defer fake.withForQueryMutex.Unlock()
	fake.WithForQueryStub = stub
}

func (fake *Discover) WithForQueryReturns(result1 driver.ChaincodeDiscover) {
	fake.withForQueryMutex.Lock()
	defer fake.withForQueryMutex.Unlock()
	fake.WithForQueryStub = nil
	fake.withForQueryReturns = struct {
		result1 driver.ChaincodeDiscover
	}{result1}
}

func (fake *Discover) WithForQueryReturnsOnCall(i int, result1 driver.ChaincodeDiscover) {
	fake.withForQueryMutex.Lock()
	defer fake.withForQueryMutex.Unlock()
	fake.WithForQueryStub = nil
	if fake.withForQueryReturnsOnCall == nil {
		fake.withForQueryReturnsOnCall = make(map[int]struct {
			result1 driver.ChaincodeDiscover
		})
	}
	fake.withForQueryReturnsOnCall[i] = struct {
		result1 driver.ChaincodeDiscover
	}{result1}
}

func (fake *Discover) WithImplicitCollections(arg1 ...string) driver.ChaincodeDiscover {
	fake.withImplicitCollectionsMutex.Lock()
	ret, specificReturn := fake.withImplicitCollectionsReturnsOnCall[len(fake.withImplicitCollectionsArgsForCall)]
	fake.withImplicitCollectionsArgsForCall = append(fake.withImplicitCollectionsArgsForCall, struct {
		arg1 []string
	}{arg1})
	stub := fake.WithImplicitCollectionsStub
	fakeReturns := fake.withImplicitCollectionsReturns
	fake.recordInvocation("WithImplicitCollections", []interface{}{arg1})
	fake.withImplicitCollectionsMutex.Unlock()
	if stub != nil {
		return stub(arg1...)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Discover) WithImplicitCollectionsCallCount() int {
	fake.withImplicitCollectionsMutex.RLock()
	defer fake.withImplicitCollectionsMutex.RUnlock()
	return len(fake.withImplicitCollectionsArgsForCall)
}

func (fake *Discover) WithImplicitCollectionsCalls(stub func(...string) driver.ChaincodeDiscover) {
	fake.withImplicitCollectionsMutex.Lock()
	defer fake.withImplicitCollectionsMutex.Unlock()
	fake.WithImplicitCollectionsStub = stub
}

func (fake *Discover) WithImplicitCollectionsArgsForCall(i int) []string {
	fake.withImplicitCollectionsMutex.RLock()
	defer fake.withImplicitCollectionsMutex.RUnlock()
	argsForCall := fake.withImplicitCollectionsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Discover) WithImplicitCollectionsReturns(result1 driver.ChaincodeDiscover) {
	fake.withImplicitCollectionsMutex.Lock()
	defer fake.withImplicitCollectionsMutex.Unlock()
	fake.WithImplicitCollectionsStub = nil
	fake.withImplicitCollectionsReturns = struct {
		result1 driver.ChaincodeDiscover
	}{result1}
}

func (fake *Discover) WithImplicitCollectionsReturnsOnCall(i int, result1 driver.ChaincodeDiscover) {
	fake.withImplicitCollectionsMutex.Lock()
	defer fake.withImplicitCollectionsMutex.Unlock()
	fake.WithImplicitCollectionsStub = nil
	if fake.withImplicitCollectionsReturnsOnCall == nil {
		fake.withImplicitCollectionsReturnsOnCall = make(map[int]struct {
			result1 driver.ChaincodeDiscover
		})
	}
	fake.withImplicitCollectionsReturnsOnCall[i] = struct {
		result1 driver.ChaincodeDiscover
	}{result1}
}

func (fake *Discover) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.callMutex.RLock()
	defer fake.callMutex.RUnlock()
	fake.chaincodeVersionMutex.RLock()
	defer fake.chaincodeVersionMutex.RUnlock()
	fake.withFilterByMSPIDsMutex.RLock()
	defer fake.withFilterByMSPIDsMutex.RUnlock()
	fake.withForQueryMutex.RLock()
	defer fake.withForQueryMutex.RUnlock()
	fake.withImplicitCollectionsMutex.RLock()
	defer fake.withImplicitCollectionsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Discover) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ chaincode.Discover = new(Discover)
