// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/hyperledger-labs/fabric-smart-client/platform/fabric/core/generic/chaincode"
	"github.com/hyperledger-labs/fabric-smart-client/platform/fabric/core/generic/config"
	"github.com/hyperledger-labs/fabric-smart-client/platform/fabric/core/generic/peer"
	"github.com/hyperledger-labs/fabric-smart-client/platform/fabric/driver"
	"github.com/hyperledger-labs/fabric-smart-client/platform/view/services/grpc"
)

type Channel struct {
	ChaincodeStub        func(string) driver.Chaincode
	chaincodeMutex       sync.RWMutex
	chaincodeArgsForCall []struct {
		arg1 string
	}
	chaincodeReturns struct {
		result1 driver.Chaincode
	}
	chaincodeReturnsOnCall map[int]struct {
		result1 driver.Chaincode
	}
	ConfigStub        func() *config.Channel
	configMutex       sync.RWMutex
	configArgsForCall []struct {
	}
	configReturns struct {
		result1 *config.Channel
	}
	configReturnsOnCall map[int]struct {
		result1 *config.Channel
	}
	IsFinalStub        func(context.Context, string) error
	isFinalMutex       sync.RWMutex
	isFinalArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	isFinalReturns struct {
		result1 error
	}
	isFinalReturnsOnCall map[int]struct {
		result1 error
	}
	MSPManagerStub        func() driver.MSPManager
	mSPManagerMutex       sync.RWMutex
	mSPManagerArgsForCall []struct {
	}
	mSPManagerReturns struct {
		result1 driver.MSPManager
	}
	mSPManagerReturnsOnCall map[int]struct {
		result1 driver.MSPManager
	}
	NameStub        func() string
	nameMutex       sync.RWMutex
	nameArgsForCall []struct {
	}
	nameReturns struct {
		result1 string
	}
	nameReturnsOnCall map[int]struct {
		result1 string
	}
	NewPeerClientForAddressStub        func(grpc.ConnectionConfig) (peer.Client, error)
	newPeerClientForAddressMutex       sync.RWMutex
	newPeerClientForAddressArgsForCall []struct {
		arg1 grpc.ConnectionConfig
	}
	newPeerClientForAddressReturns struct {
		result1 peer.Client
		result2 error
	}
	newPeerClientForAddressReturnsOnCall map[int]struct {
		result1 peer.Client
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Channel) Chaincode(arg1 string) driver.Chaincode {
	fake.chaincodeMutex.Lock()
	ret, specificReturn := fake.chaincodeReturnsOnCall[len(fake.chaincodeArgsForCall)]
	fake.chaincodeArgsForCall = append(fake.chaincodeArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ChaincodeStub
	fakeReturns := fake.chaincodeReturns
	fake.recordInvocation("Chaincode", []interface{}{arg1})
	fake.chaincodeMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Channel) ChaincodeCallCount() int {
	fake.chaincodeMutex.RLock()
	defer fake.chaincodeMutex.RUnlock()
	return len(fake.chaincodeArgsForCall)
}

func (fake *Channel) ChaincodeCalls(stub func(string) driver.Chaincode) {
	fake.chaincodeMutex.Lock()
	defer fake.chaincodeMutex.Unlock()
	fake.ChaincodeStub = stub
}

func (fake *Channel) ChaincodeArgsForCall(i int) string {
	fake.chaincodeMutex.RLock()
	defer fake.chaincodeMutex.RUnlock()
	argsForCall := fake.chaincodeArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Channel) ChaincodeReturns(result1 driver.Chaincode) {
	fake.chaincodeMutex.Lock()
	defer fake.chaincodeMutex.Unlock()
	fake.ChaincodeStub = nil
	fake.chaincodeReturns = struct {
		result1 driver.Chaincode
	}{result1}
}

func (fake *Channel) ChaincodeReturnsOnCall(i int, result1 driver.Chaincode) {
	fake.chaincodeMutex.Lock()
	defer fake.chaincodeMutex.Unlock()
	fake.ChaincodeStub = nil
	if fake.chaincodeReturnsOnCall == nil {
		fake.chaincodeReturnsOnCall = make(map[int]struct {
			result1 driver.Chaincode
		})
	}
	fake.chaincodeReturnsOnCall[i] = struct {
		result1 driver.Chaincode
	}{result1}
}

func (fake *Channel) Config() *config.Channel {
	fake.configMutex.Lock()
	ret, specificReturn := fake.configReturnsOnCall[len(fake.configArgsForCall)]
	fake.configArgsForCall = append(fake.configArgsForCall, struct {
	}{})
	stub := fake.ConfigStub
	fakeReturns := fake.configReturns
	fake.recordInvocation("Config", []interface{}{})
	fake.configMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Channel) ConfigCallCount() int {
	fake.configMutex.RLock()
	defer fake.configMutex.RUnlock()
	return len(fake.configArgsForCall)
}

func (fake *Channel) ConfigCalls(stub func() *config.Channel) {
	fake.configMutex.Lock()
	defer fake.configMutex.Unlock()
	fake.ConfigStub = stub
}

func (fake *Channel) ConfigReturns(result1 *config.Channel) {
	fake.configMutex.Lock()
	defer fake.configMutex.Unlock()
	fake.ConfigStub = nil
	fake.configReturns = struct {
		result1 *config.Channel
	}{result1}
}

func (fake *Channel) ConfigReturnsOnCall(i int, result1 *config.Channel) {
	fake.configMutex.Lock()
	defer fake.configMutex.Unlock()
	fake.ConfigStub = nil
	if fake.configReturnsOnCall == nil {
		fake.configReturnsOnCall = make(map[int]struct {
			result1 *config.Channel
		})
	}
	fake.configReturnsOnCall[i] = struct {
		result1 *config.Channel
	}{result1}
}

func (fake *Channel) IsFinal(arg1 context.Context, arg2 string) error {
	fake.isFinalMutex.Lock()
	ret, specificReturn := fake.isFinalReturnsOnCall[len(fake.isFinalArgsForCall)]
	fake.isFinalArgsForCall = append(fake.isFinalArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.IsFinalStub
	fakeReturns := fake.isFinalReturns
	fake.recordInvocation("IsFinal", []interface{}{arg1, arg2})
	fake.isFinalMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Channel) IsFinalCallCount() int {
	fake.isFinalMutex.RLock()
	defer fake.isFinalMutex.RUnlock()
	return len(fake.isFinalArgsForCall)
}

func (fake *Channel) IsFinalCalls(stub func(context.Context, string) error) {
	fake.isFinalMutex.Lock()
	defer fake.isFinalMutex.Unlock()
	fake.IsFinalStub = stub
}

func (fake *Channel) IsFinalArgsForCall(i int) (context.Context, string) {
	fake.isFinalMutex.RLock()
	defer fake.isFinalMutex.RUnlock()
	argsForCall := fake.isFinalArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Channel) IsFinalReturns(result1 error) {
	fake.isFinalMutex.Lock()
	defer fake.isFinalMutex.Unlock()
	fake.IsFinalStub = nil
	fake.isFinalReturns = struct {
		result1 error
	}{result1}
}

func (fake *Channel) IsFinalReturnsOnCall(i int, result1 error) {
	fake.isFinalMutex.Lock()
	defer fake.isFinalMutex.Unlock()
	fake.IsFinalStub = nil
	if fake.isFinalReturnsOnCall == nil {
		fake.isFinalReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.isFinalReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Channel) MSPManager() driver.MSPManager {
	fake.mSPManagerMutex.Lock()
	ret, specificReturn := fake.mSPManagerReturnsOnCall[len(fake.mSPManagerArgsForCall)]
	fake.mSPManagerArgsForCall = append(fake.mSPManagerArgsForCall, struct {
	}{})
	stub := fake.MSPManagerStub
	fakeReturns := fake.mSPManagerReturns
	fake.recordInvocation("MSPManager", []interface{}{})
	fake.mSPManagerMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Channel) MSPManagerCallCount() int {
	fake.mSPManagerMutex.RLock()
	defer fake.mSPManagerMutex.RUnlock()
	return len(fake.mSPManagerArgsForCall)
}

func (fake *Channel) MSPManagerCalls(stub func() driver.MSPManager) {
	fake.mSPManagerMutex.Lock()
	defer fake.mSPManagerMutex.Unlock()
	fake.MSPManagerStub = stub
}

func (fake *Channel) MSPManagerReturns(result1 driver.MSPManager) {
	fake.mSPManagerMutex.Lock()
	defer fake.mSPManagerMutex.Unlock()
	fake.MSPManagerStub = nil
	fake.mSPManagerReturns = struct {
		result1 driver.MSPManager
	}{result1}
}

func (fake *Channel) MSPManagerReturnsOnCall(i int, result1 driver.MSPManager) {
	fake.mSPManagerMutex.Lock()
	defer fake.mSPManagerMutex.Unlock()
	fake.MSPManagerStub = nil
	if fake.mSPManagerReturnsOnCall == nil {
		fake.mSPManagerReturnsOnCall = make(map[int]struct {
			result1 driver.MSPManager
		})
	}
	fake.mSPManagerReturnsOnCall[i] = struct {
		result1 driver.MSPManager
	}{result1}
}

func (fake *Channel) Name() string {
	fake.nameMutex.Lock()
	ret, specificReturn := fake.nameReturnsOnCall[len(fake.nameArgsForCall)]
	fake.nameArgsForCall = append(fake.nameArgsForCall, struct {
	}{})
	stub := fake.NameStub
	fakeReturns := fake.nameReturns
	fake.recordInvocation("Name", []interface{}{})
	fake.nameMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Channel) NameCallCount() int {
	fake.nameMutex.RLock()
	defer fake.nameMutex.RUnlock()
	return len(fake.nameArgsForCall)
}

func (fake *Channel) NameCalls(stub func() string) {
	fake.nameMutex.Lock()
	defer fake.nameMutex.Unlock()
	fake.NameStub = stub
}

func (fake *Channel) NameReturns(result1 string) {
	fake.nameMutex.Lock()
	defer fake.nameMutex.Unlock()
	fake.NameStub = nil
	fake.nameReturns = struct {
		result1 string
	}{result1}
}

func (fake *Channel) NameReturnsOnCall(i int, result1 string) {
	fake.nameMutex.Lock()
	defer fake.nameMutex.Unlock()
	fake.NameStub = nil
	if fake.nameReturnsOnCall == nil {
		fake.nameReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.nameReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *Channel) NewPeerClientForAddress(arg1 grpc.ConnectionConfig) (peer.Client, error) {
	fake.newPeerClientForAddressMutex.Lock()
	ret, specificReturn := fake.newPeerClientForAddressReturnsOnCall[len(fake.newPeerClientForAddressArgsForCall)]
	fake.newPeerClientForAddressArgsForCall = append(fake.newPeerClientForAddressArgsForCall, struct {
		arg1 grpc.ConnectionConfig
	}{arg1})
	stub := fake.NewPeerClientForAddressStub
	fakeReturns := fake.newPeerClientForAddressReturns
	fake.recordInvocation("NewPeerClientForAddress", []interface{}{arg1})
	fake.newPeerClientForAddressMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Channel) NewPeerClientForAddressCallCount() int {
	fake.newPeerClientForAddressMutex.RLock()
	defer fake.newPeerClientForAddressMutex.RUnlock()
	return len(fake.newPeerClientForAddressArgsForCall)
}

func (fake *Channel) NewPeerClientForAddressCalls(stub func(grpc.ConnectionConfig) (peer.Client, error)) {
	fake.newPeerClientForAddressMutex.Lock()
	defer fake.newPeerClientForAddressMutex.Unlock()
	fake.NewPeerClientForAddressStub = stub
}

func (fake *Channel) NewPeerClientForAddressArgsForCall(i int) grpc.ConnectionConfig {
	fake.newPeerClientForAddressMutex.RLock()
	defer fake.newPeerClientForAddressMutex.RUnlock()
	argsForCall := fake.newPeerClientForAddressArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Channel) NewPeerClientForAddressReturns(result1 peer.Client, result2 error) {
	fake.newPeerClientForAddressMutex.Lock()
	defer fake.newPeerClientForAddressMutex.Unlock()
	fake.NewPeerClientForAddressStub = nil
	fake.newPeerClientForAddressReturns = struct {
		result1 peer.Client
		result2 error
	}{result1, result2}
}

func (fake *Channel) NewPeerClientForAddressReturnsOnCall(i int, result1 peer.Client, result2 error) {
	fake.newPeerClientForAddressMutex.Lock()
	defer fake.newPeerClientForAddressMutex.Unlock()
	fake.NewPeerClientForAddressStub = nil
	if fake.newPeerClientForAddressReturnsOnCall == nil {
		fake.newPeerClientForAddressReturnsOnCall = make(map[int]struct {
			result1 peer.Client
			result2 error
		})
	}
	fake.newPeerClientForAddressReturnsOnCall[i] = struct {
		result1 peer.Client
		result2 error
	}{result1, result2}
}

func (fake *Channel) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.chaincodeMutex.RLock()
	defer fake.chaincodeMutex.RUnlock()
	fake.configMutex.RLock()
	defer fake.configMutex.RUnlock()
	fake.isFinalMutex.RLock()
	defer fake.isFinalMutex.RUnlock()
	fake.mSPManagerMutex.RLock()
	defer fake.mSPManagerMutex.RUnlock()
	fake.nameMutex.RLock()
	defer fake.nameMutex.RUnlock()
	fake.newPeerClientForAddressMutex.RLock()
	defer fake.newPeerClientForAddressMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Channel) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ chaincode.Channel = new(Channel)
