// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"sync"

	"github.com/hyperledger-labs/fabric-smart-client/platform/fabric/driver"
)

type ChaincodeConfig struct {
	IDStub        func() string
	iDMutex       sync.RWMutex
	iDArgsForCall []struct {
	}
	iDReturns struct {
		result1 string
	}
	iDReturnsOnCall map[int]struct {
		result1 string
	}
	IsPrivateStub        func() bool
	isPrivateMutex       sync.RWMutex
	isPrivateArgsForCall []struct {
	}
	isPrivateReturns struct {
		result1 bool
	}
	isPrivateReturnsOnCall map[int]struct {
		result1 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ChaincodeConfig) ID() string {
	fake.iDMutex.Lock()
	ret, specificReturn := fake.iDReturnsOnCall[len(fake.iDArgsForCall)]
	fake.iDArgsForCall = append(fake.iDArgsForCall, struct {
	}{})
	stub := fake.IDStub
	fakeReturns := fake.iDReturns
	fake.recordInvocation("ID", []interface{}{})
	fake.iDMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ChaincodeConfig) IDCallCount() int {
	fake.iDMutex.RLock()
	defer fake.iDMutex.RUnlock()
	return len(fake.iDArgsForCall)
}

func (fake *ChaincodeConfig) IDCalls(stub func() string) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = stub
}

func (fake *ChaincodeConfig) IDReturns(result1 string) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = nil
	fake.iDReturns = struct {
		result1 string
	}{result1}
}

func (fake *ChaincodeConfig) IDReturnsOnCall(i int, result1 string) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = nil
	if fake.iDReturnsOnCall == nil {
		fake.iDReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.iDReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *ChaincodeConfig) IsPrivate() bool {
	fake.isPrivateMutex.Lock()
	ret, specificReturn := fake.isPrivateReturnsOnCall[len(fake.isPrivateArgsForCall)]
	fake.isPrivateArgsForCall = append(fake.isPrivateArgsForCall, struct {
	}{})
	stub := fake.IsPrivateStub
	fakeReturns := fake.isPrivateReturns
	fake.recordInvocation("IsPrivate", []interface{}{})
	fake.isPrivateMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ChaincodeConfig) IsPrivateCallCount() int {
	fake.isPrivateMutex.RLock()
	defer fake.isPrivateMutex.RUnlock()
	return len(fake.isPrivateArgsForCall)
}

func (fake *ChaincodeConfig) IsPrivateCalls(stub func() bool) {
	fake.isPrivateMutex.Lock()
	defer fake.isPrivateMutex.Unlock()
	fake.IsPrivateStub = stub
}

func (fake *ChaincodeConfig) IsPrivateReturns(result1 bool) {
	fake.isPrivateMutex.Lock()
	defer fake.isPrivateMutex.Unlock()
	fake.IsPrivateStub = nil
	fake.isPrivateReturns = struct {
		result1 bool
	}{result1}
}

func (fake *ChaincodeConfig) IsPrivateReturnsOnCall(i int, result1 bool) {
	fake.isPrivateMutex.Lock()
	defer fake.isPrivateMutex.Unlock()
	fake.IsPrivateStub = nil
	if fake.isPrivateReturnsOnCall == nil {
		fake.isPrivateReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.isPrivateReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *ChaincodeConfig) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ChaincodeConfig) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ driver.ChaincodeConfig = new(ChaincodeConfig)
