// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"sync"

	"github.com/hyperledger-labs/fabric-smart-client/platform/fabric/core/generic/discovery"
)

type Response struct {
	ForChannelStub        func(string) discovery.ChannelResponse
	forChannelMutex       sync.RWMutex
	forChannelArgsForCall []struct {
		arg1 string
	}
	forChannelReturns struct {
		result1 discovery.ChannelResponse
	}
	forChannelReturnsOnCall map[int]struct {
		result1 discovery.ChannelResponse
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Response) ForChannel(arg1 string) discovery.ChannelResponse {
	fake.forChannelMutex.Lock()
	ret, specificReturn := fake.forChannelReturnsOnCall[len(fake.forChannelArgsForCall)]
	fake.forChannelArgsForCall = append(fake.forChannelArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ForChannelStub
	fakeReturns := fake.forChannelReturns
	fake.recordInvocation("ForChannel", []interface{}{arg1})
	fake.forChannelMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Response) ForChannelCallCount() int {
	fake.forChannelMutex.RLock()
	defer fake.forChannelMutex.RUnlock()
	return len(fake.forChannelArgsForCall)
}

func (fake *Response) ForChannelCalls(stub func(string) discovery.ChannelResponse) {
	fake.forChannelMutex.Lock()
	defer fake.forChannelMutex.Unlock()
	fake.ForChannelStub = stub
}

func (fake *Response) ForChannelArgsForCall(i int) string {
	fake.forChannelMutex.RLock()
	defer fake.forChannelMutex.RUnlock()
	argsForCall := fake.forChannelArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Response) ForChannelReturns(result1 discovery.ChannelResponse) {
	fake.forChannelMutex.Lock()
	defer fake.forChannelMutex.Unlock()
	fake.ForChannelStub = nil
	fake.forChannelReturns = struct {
		result1 discovery.ChannelResponse
	}{result1}
}

func (fake *Response) ForChannelReturnsOnCall(i int, result1 discovery.ChannelResponse) {
	fake.forChannelMutex.Lock()
	defer fake.forChannelMutex.Unlock()
	fake.ForChannelStub = nil
	if fake.forChannelReturnsOnCall == nil {
		fake.forChannelReturnsOnCall = make(map[int]struct {
			result1 discovery.ChannelResponse
		})
	}
	fake.forChannelReturnsOnCall[i] = struct {
		result1 discovery.ChannelResponse
	}{result1}
}

func (fake *Response) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Response) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ discovery.Response = new(Response)
