// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"sync"

	"github.com/hyperledger-labs/fabric-smart-client/platform/fabricx/core/channel/config"
	"github.com/hyperledger-labs/fabric-smart-client/platform/fabricx/core/committer/queryservice"
)

type QueryService struct {
	GetConfigTransactionStub        func() (*queryservice.ConfigTransactionInfo, error)
	getConfigTransactionMutex       sync.RWMutex
	getConfigTransactionArgsForCall []struct {
	}
	getConfigTransactionReturns struct {
		result1 *queryservice.ConfigTransactionInfo
		result2 error
	}
	getConfigTransactionReturnsOnCall map[int]struct {
		result1 *queryservice.ConfigTransactionInfo
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *QueryService) GetConfigTransaction() (*queryservice.ConfigTransactionInfo, error) {
	fake.getConfigTransactionMutex.Lock()
	ret, specificReturn := fake.getConfigTransactionReturnsOnCall[len(fake.getConfigTransactionArgsForCall)]
	fake.getConfigTransactionArgsForCall = append(fake.getConfigTransactionArgsForCall, struct {
	}{})
	stub := fake.GetConfigTransactionStub
	fakeReturns := fake.getConfigTransactionReturns
	fake.recordInvocation("GetConfigTransaction", []interface{}{})
	fake.getConfigTransactionMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *QueryService) GetConfigTransactionCallCount() int {
	fake.getConfigTransactionMutex.RLock()
	defer fake.getConfigTransactionMutex.RUnlock()
	return len(fake.getConfigTransactionArgsForCall)
}

func (fake *QueryService) GetConfigTransactionCalls(stub func() (*queryservice.ConfigTransactionInfo, error)) {
	fake.getConfigTransactionMutex.Lock()
	defer fake.getConfigTransactionMutex.Unlock()
	fake.GetConfigTransactionStub = stub
}

func (fake *QueryService) GetConfigTransactionReturns(result1 *queryservice.ConfigTransactionInfo, result2 error) {
	fake.getConfigTransactionMutex.Lock()
	defer fake.getConfigTransactionMutex.Unlock()
	fake.GetConfigTransactionStub = nil
	fake.getConfigTransactionReturns = struct {
		result1 *queryservice.ConfigTransactionInfo
		result2 error
	}{result1, result2}
}

func (fake *QueryService) GetConfigTransactionReturnsOnCall(i int, result1 *queryservice.ConfigTransactionInfo, result2 error) {
	fake.getConfigTransactionMutex.Lock()
	defer fake.getConfigTransactionMutex.Unlock()
	fake.GetConfigTransactionStub = nil
	if fake.getConfigTransactionReturnsOnCall == nil {
		fake.getConfigTransactionReturnsOnCall = make(map[int]struct {
			result1 *queryservice.ConfigTransactionInfo
			result2 error
		})
	}
	fake.getConfigTransactionReturnsOnCall[i] = struct {
		result1 *queryservice.ConfigTransactionInfo
		result2 error
	}{result1, result2}
}

func (fake *QueryService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *QueryService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ config.QueryService = new(QueryService)
