// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"context"
	"sync"

	"github.com/hyperledger/fabric-protos-go-apiv2/common"
	"github.com/hyperledger/fabric-x-common/api/committerpb"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

type FakeBlockQueryServiceClient struct {
	GetBlockByNumberStub        func(context.Context, *committerpb.BlockNumber, ...grpc.CallOption) (*common.Block, error)
	getBlockByNumberMutex       sync.RWMutex
	getBlockByNumberArgsForCall []struct {
		arg1 context.Context
		arg2 *committerpb.BlockNumber
		arg3 []grpc.CallOption
	}
	getBlockByNumberReturns struct {
		result1 *common.Block
		result2 error
	}
	getBlockByNumberReturnsOnCall map[int]struct {
		result1 *common.Block
		result2 error
	}
	GetBlockByTxIDStub        func(context.Context, *committerpb.TxID, ...grpc.CallOption) (*common.Block, error)
	getBlockByTxIDMutex       sync.RWMutex
	getBlockByTxIDArgsForCall []struct {
		arg1 context.Context
		arg2 *committerpb.TxID
		arg3 []grpc.CallOption
	}
	getBlockByTxIDReturns struct {
		result1 *common.Block
		result2 error
	}
	getBlockByTxIDReturnsOnCall map[int]struct {
		result1 *common.Block
		result2 error
	}
	GetBlockchainInfoStub        func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*common.BlockchainInfo, error)
	getBlockchainInfoMutex       sync.RWMutex
	getBlockchainInfoArgsForCall []struct {
		arg1 context.Context
		arg2 *emptypb.Empty
		arg3 []grpc.CallOption
	}
	getBlockchainInfoReturns struct {
		result1 *common.BlockchainInfo
		result2 error
	}
	getBlockchainInfoReturnsOnCall map[int]struct {
		result1 *common.BlockchainInfo
		result2 error
	}
	GetTxByIDStub        func(context.Context, *committerpb.TxID, ...grpc.CallOption) (*common.Envelope, error)
	getTxByIDMutex       sync.RWMutex
	getTxByIDArgsForCall []struct {
		arg1 context.Context
		arg2 *committerpb.TxID
		arg3 []grpc.CallOption
	}
	getTxByIDReturns struct {
		result1 *common.Envelope
		result2 error
	}
	getTxByIDReturnsOnCall map[int]struct {
		result1 *common.Envelope
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBlockQueryServiceClient) GetBlockByNumber(arg1 context.Context, arg2 *committerpb.BlockNumber, arg3 ...grpc.CallOption) (*common.Block, error) {
	fake.getBlockByNumberMutex.Lock()
	ret, specificReturn := fake.getBlockByNumberReturnsOnCall[len(fake.getBlockByNumberArgsForCall)]
	fake.getBlockByNumberArgsForCall = append(fake.getBlockByNumberArgsForCall, struct {
		arg1 context.Context
		arg2 *committerpb.BlockNumber
		arg3 []grpc.CallOption
	}{arg1, arg2, arg3})
	stub := fake.GetBlockByNumberStub
	fakeReturns := fake.getBlockByNumberReturns
	fake.recordInvocation("GetBlockByNumber", []interface{}{arg1, arg2, arg3})
	fake.getBlockByNumberMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBlockQueryServiceClient) GetBlockByNumberCallCount() int {
	fake.getBlockByNumberMutex.RLock()
	defer fake.getBlockByNumberMutex.RUnlock()
	return len(fake.getBlockByNumberArgsForCall)
}

func (fake *FakeBlockQueryServiceClient) GetBlockByNumberCalls(stub func(context.Context, *committerpb.BlockNumber, ...grpc.CallOption) (*common.Block, error)) {
	fake.getBlockByNumberMutex.Lock()
	defer fake.getBlockByNumberMutex.Unlock()
	fake.GetBlockByNumberStub = stub
}

func (fake *FakeBlockQueryServiceClient) GetBlockByNumberArgsForCall(i int) (context.Context, *committerpb.BlockNumber, []grpc.CallOption) {
	fake.getBlockByNumberMutex.RLock()
	defer fake.getBlockByNumberMutex.RUnlock()
	argsForCall := fake.getBlockByNumberArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeBlockQueryServiceClient) GetBlockByNumberReturns(result1 *common.Block, result2 error) {
	fake.getBlockByNumberMutex.Lock()
	defer fake.getBlockByNumberMutex.Unlock()
	fake.GetBlockByNumberStub = nil
	fake.getBlockByNumberReturns = struct {
		result1 *common.Block
		result2 error
	}{result1, result2}
}

func (fake *FakeBlockQueryServiceClient) GetBlockByNumberReturnsOnCall(i int, result1 *common.Block, result2 error) {
	fake.getBlockByNumberMutex.Lock()
	defer fake.getBlockByNumberMutex.Unlock()
	fake.GetBlockByNumberStub = nil
	if fake.getBlockByNumberReturnsOnCall == nil {
		fake.getBlockByNumberReturnsOnCall = make(map[int]struct {
			result1 *common.Block
			result2 error
		})
	}
	fake.getBlockByNumberReturnsOnCall[i] = struct {
		result1 *common.Block
		result2 error
	}{result1, result2}
}

func (fake *FakeBlockQueryServiceClient) GetBlockByTxID(arg1 context.Context, arg2 *committerpb.TxID, arg3 ...grpc.CallOption) (*common.Block, error) {
	fake.getBlockByTxIDMutex.Lock()
	ret, specificReturn := fake.getBlockByTxIDReturnsOnCall[len(fake.getBlockByTxIDArgsForCall)]
	fake.getBlockByTxIDArgsForCall = append(fake.getBlockByTxIDArgsForCall, struct {
		arg1 context.Context
		arg2 *committerpb.TxID
		arg3 []grpc.CallOption
	}{arg1, arg2, arg3})
	stub := fake.GetBlockByTxIDStub
	fakeReturns := fake.getBlockByTxIDReturns
	fake.recordInvocation("GetBlockByTxID", []interface{}{arg1, arg2, arg3})
	fake.getBlockByTxIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBlockQueryServiceClient) GetBlockByTxIDCallCount() int {
	fake.getBlockByTxIDMutex.RLock()
	defer fake.getBlockByTxIDMutex.RUnlock()
	return len(fake.getBlockByTxIDArgsForCall)
}

func (fake *FakeBlockQueryServiceClient) GetBlockByTxIDCalls(stub func(context.Context, *committerpb.TxID, ...grpc.CallOption) (*common.Block, error)) {
	fake.getBlockByTxIDMutex.Lock()
	defer fake.getBlockByTxIDMutex.Unlock()
	fake.GetBlockByTxIDStub = stub
}

func (fake *FakeBlockQueryServiceClient) GetBlockByTxIDArgsForCall(i int) (context.Context, *committerpb.TxID, []grpc.CallOption) {
	fake.getBlockByTxIDMutex.RLock()
	defer fake.getBlockByTxIDMutex.RUnlock()
	argsForCall := fake.getBlockByTxIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeBlockQueryServiceClient) GetBlockByTxIDReturns(result1 *common.Block, result2 error) {
	fake.getBlockByTxIDMutex.Lock()
	defer fake.getBlockByTxIDMutex.Unlock()
	fake.GetBlockByTxIDStub = nil
	fake.getBlockByTxIDReturns = struct {
		result1 *common.Block
		result2 error
	}{result1, result2}
}

func (fake *FakeBlockQueryServiceClient) GetBlockByTxIDReturnsOnCall(i int, result1 *common.Block, result2 error) {
	fake.getBlockByTxIDMutex.Lock()
	defer fake.getBlockByTxIDMutex.Unlock()
	fake.GetBlockByTxIDStub = nil
	if fake.getBlockByTxIDReturnsOnCall == nil {
		fake.getBlockByTxIDReturnsOnCall = make(map[int]struct {
			result1 *common.Block
			result2 error
		})
	}
	fake.getBlockByTxIDReturnsOnCall[i] = struct {
		result1 *common.Block
		result2 error
	}{result1, result2}
}

func (fake *FakeBlockQueryServiceClient) GetBlockchainInfo(arg1 context.Context, arg2 *emptypb.Empty, arg3 ...grpc.CallOption) (*common.BlockchainInfo, error) {
	fake.getBlockchainInfoMutex.Lock()
	ret, specificReturn := fake.getBlockchainInfoReturnsOnCall[len(fake.getBlockchainInfoArgsForCall)]
	fake.getBlockchainInfoArgsForCall = append(fake.getBlockchainInfoArgsForCall, struct {
		arg1 context.Context
		arg2 *emptypb.Empty
		arg3 []grpc.CallOption
	}{arg1, arg2, arg3})
	stub := fake.GetBlockchainInfoStub
	fakeReturns := fake.getBlockchainInfoReturns
	fake.recordInvocation("GetBlockchainInfo", []interface{}{arg1, arg2, arg3})
	fake.getBlockchainInfoMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBlockQueryServiceClient) GetBlockchainInfoCallCount() int {
	fake.getBlockchainInfoMutex.RLock()
	defer fake.getBlockchainInfoMutex.RUnlock()
	return len(fake.getBlockchainInfoArgsForCall)
}

func (fake *FakeBlockQueryServiceClient) GetBlockchainInfoCalls(stub func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*common.BlockchainInfo, error)) {
	fake.getBlockchainInfoMutex.Lock()
	defer fake.getBlockchainInfoMutex.Unlock()
	fake.GetBlockchainInfoStub = stub
}

func (fake *FakeBlockQueryServiceClient) GetBlockchainInfoArgsForCall(i int) (context.Context, *emptypb.Empty, []grpc.CallOption) {
	fake.getBlockchainInfoMutex.RLock()
	defer fake.getBlockchainInfoMutex.RUnlock()
	argsForCall := fake.getBlockchainInfoArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeBlockQueryServiceClient) GetBlockchainInfoReturns(result1 *common.BlockchainInfo, result2 error) {
	fake.getBlockchainInfoMutex.Lock()
	defer fake.getBlockchainInfoMutex.Unlock()
	fake.GetBlockchainInfoStub = nil
	fake.getBlockchainInfoReturns = struct {
		result1 *common.BlockchainInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeBlockQueryServiceClient) GetBlockchainInfoReturnsOnCall(i int, result1 *common.BlockchainInfo, result2 error) {
	fake.getBlockchainInfoMutex.Lock()
	defer fake.getBlockchainInfoMutex.Unlock()
	fake.GetBlockchainInfoStub = nil
	if fake.getBlockchainInfoReturnsOnCall == nil {
		fake.getBlockchainInfoReturnsOnCall = make(map[int]struct {
			result1 *common.BlockchainInfo
			result2 error
		})
	}
	fake.getBlockchainInfoReturnsOnCall[i] = struct {
		result1 *common.BlockchainInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeBlockQueryServiceClient) GetTxByID(arg1 context.Context, arg2 *committerpb.TxID, arg3 ...grpc.CallOption) (*common.Envelope, error) {
	fake.getTxByIDMutex.Lock()
	ret, specificReturn := fake.getTxByIDReturnsOnCall[len(fake.getTxByIDArgsForCall)]
	fake.getTxByIDArgsForCall = append(fake.getTxByIDArgsForCall, struct {
		arg1 context.Context
		arg2 *committerpb.TxID
		arg3 []grpc.CallOption
	}{arg1, arg2, arg3})
	stub := fake.GetTxByIDStub
	fakeReturns := fake.getTxByIDReturns
	fake.recordInvocation("GetTxByID", []interface{}{arg1, arg2, arg3})
	fake.getTxByIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBlockQueryServiceClient) GetTxByIDCallCount() int {
	fake.getTxByIDMutex.RLock()
	defer fake.getTxByIDMutex.RUnlock()
	return len(fake.getTxByIDArgsForCall)
}

func (fake *FakeBlockQueryServiceClient) GetTxByIDCalls(stub func(context.Context, *committerpb.TxID, ...grpc.CallOption) (*common.Envelope, error)) {
	fake.getTxByIDMutex.Lock()
	defer fake.getTxByIDMutex.Unlock()
	fake.GetTxByIDStub = stub
}

func (fake *FakeBlockQueryServiceClient) GetTxByIDArgsForCall(i int) (context.Context, *committerpb.TxID, []grpc.CallOption) {
	fake.getTxByIDMutex.RLock()
	defer fake.getTxByIDMutex.RUnlock()
	argsForCall := fake.getTxByIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeBlockQueryServiceClient) GetTxByIDReturns(result1 *common.Envelope, result2 error) {
	fake.getTxByIDMutex.Lock()
	defer fake.getTxByIDMutex.Unlock()
	fake.GetTxByIDStub = nil
	fake.getTxByIDReturns = struct {
		result1 *common.Envelope
		result2 error
	}{result1, result2}
}

func (fake *FakeBlockQueryServiceClient) GetTxByIDReturnsOnCall(i int, result1 *common.Envelope, result2 error) {
	fake.getTxByIDMutex.Lock()
	defer fake.getTxByIDMutex.Unlock()
	fake.GetTxByIDStub = nil
	if fake.getTxByIDReturnsOnCall == nil {
		fake.getTxByIDReturnsOnCall = make(map[int]struct {
			result1 *common.Envelope
			result2 error
		})
	}
	fake.getTxByIDReturnsOnCall[i] = struct {
		result1 *common.Envelope
		result2 error
	}{result1, result2}
}

func (fake *FakeBlockQueryServiceClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBlockQueryServiceClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ committerpb.BlockQueryServiceClient = new(FakeBlockQueryServiceClient)
