@startuml
'- force wrapping of longer text
'skinparam wrapWidth 400
!pragma teoz true
hide footbox

actor "Borrower" as Borrower
actor "Lender" as Lender
participant "Ordering Service" as Orderer

Borrower -> Borrower: Create IOU State
Borrower -> Borrower: Prepare Transaction
Borrower -> Lender: Run CollectEndorsementsView
Lender -> Lender: Check Transaction
Lender -> Borrower: Run EndorseView
Borrower -> Orderer: Run OrderingView
Lender -> Borrower: Run EndorseView

@enduml