@startuml
'- force wrapping of longer text
'skinparam wrapWidth 400
!pragma teoz true
hide footbox

actor "Borrower" as Borrower
actor "Lender" as Lender
actor "Approver" as Approver
participant "Fabric" as Fabric

Borrower -> Borrower: Create IOU State
Borrower -> Borrower: Prepare Transaction
Borrower -> Lender: Run CollectEndorsementsView
Lender -> Lender: Check Transaction
Lender -> Borrower: Run EndorseView
Borrower -> Fabric: Run OrderingView

@enduml