blank_issues_enabled: false

contact_links:
  - name: 📖 Contribution Guide
    url: https://github.com/hyperledger-labs/fabric-smart-client/blob/main/CONTRIBUTING.md
    about: Learn how to get started with contributing

  - name: 💬 Ask a Question
    url: https://discord.com/channels/905194001349627914/945691888348967012
    about: Get help from the Fabric Smart Client community on Discord