// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	drivera "github.com/hyperledger-labs/fabric-smart-client/platform/common/driver"
	"github.com/hyperledger-labs/fabric-smart-client/platform/fabric/driver"
)

type FakeVault struct {
	CloseStub        func() error
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
	}
	closeReturns struct {
		result1 error
	}
	closeReturnsOnCall map[int]struct {
		result1 error
	}
	CommitTXStub        func(context.Context, drivera.TxID, drivera.BlockNum, drivera.TxNum) error
	commitTXMutex       sync.RWMutex
	commitTXArgsForCall []struct {
		arg1 context.Context
		arg2 drivera.TxID
		arg3 drivera.BlockNum
		arg4 drivera.TxNum
	}
	commitTXReturns struct {
		result1 error
	}
	commitTXReturnsOnCall map[int]struct {
		result1 error
	}
	DiscardTxStub        func(context.Context, drivera.TxID, string) error
	discardTxMutex       sync.RWMutex
	discardTxArgsForCall []struct {
		arg1 context.Context
		arg2 drivera.TxID
		arg3 string
	}
	discardTxReturns struct {
		result1 error
	}
	discardTxReturnsOnCall map[int]struct {
		result1 error
	}
	InspectRWSetStub        func(context.Context, []byte, ...drivera.Namespace) (driver.RWSet, error)
	inspectRWSetMutex       sync.RWMutex
	inspectRWSetArgsForCall []struct {
		arg1 context.Context
		arg2 []byte
		arg3 []drivera.Namespace
	}
	inspectRWSetReturns struct {
		result1 driver.RWSet
		result2 error
	}
	inspectRWSetReturnsOnCall map[int]struct {
		result1 driver.RWSet
		result2 error
	}
	MatchStub        func(context.Context, drivera.TxID, []byte) error
	matchMutex       sync.RWMutex
	matchArgsForCall []struct {
		arg1 context.Context
		arg2 drivera.TxID
		arg3 []byte
	}
	matchReturns struct {
		result1 error
	}
	matchReturnsOnCall map[int]struct {
		result1 error
	}
	NewQueryExecutorStub        func(context.Context) (drivera.QueryExecutor, error)
	newQueryExecutorMutex       sync.RWMutex
	newQueryExecutorArgsForCall []struct {
		arg1 context.Context
	}
	newQueryExecutorReturns struct {
		result1 drivera.QueryExecutor
		result2 error
	}
	newQueryExecutorReturnsOnCall map[int]struct {
		result1 drivera.QueryExecutor
		result2 error
	}
	NewRWSetStub        func(context.Context, drivera.TxID) (drivera.RWSet, error)
	newRWSetMutex       sync.RWMutex
	newRWSetArgsForCall []struct {
		arg1 context.Context
		arg2 drivera.TxID
	}
	newRWSetReturns struct {
		result1 drivera.RWSet
		result2 error
	}
	newRWSetReturnsOnCall map[int]struct {
		result1 drivera.RWSet
		result2 error
	}
	NewRWSetFromBytesStub        func(context.Context, drivera.TxID, []byte) (drivera.RWSet, error)
	newRWSetFromBytesMutex       sync.RWMutex
	newRWSetFromBytesArgsForCall []struct {
		arg1 context.Context
		arg2 drivera.TxID
		arg3 []byte
	}
	newRWSetFromBytesReturns struct {
		result1 drivera.RWSet
		result2 error
	}
	newRWSetFromBytesReturnsOnCall map[int]struct {
		result1 drivera.RWSet
		result2 error
	}
	RWSExistsStub        func(context.Context, drivera.TxID) bool
	rWSExistsMutex       sync.RWMutex
	rWSExistsArgsForCall []struct {
		arg1 context.Context
		arg2 drivera.TxID
	}
	rWSExistsReturns struct {
		result1 bool
	}
	rWSExistsReturnsOnCall map[int]struct {
		result1 bool
	}
	SetDiscardedStub        func(context.Context, drivera.TxID, string) error
	setDiscardedMutex       sync.RWMutex
	setDiscardedArgsForCall []struct {
		arg1 context.Context
		arg2 drivera.TxID
		arg3 string
	}
	setDiscardedReturns struct {
		result1 error
	}
	setDiscardedReturnsOnCall map[int]struct {
		result1 error
	}
	StatusStub        func(context.Context, drivera.TxID) (driver.ValidationCode, string, error)
	statusMutex       sync.RWMutex
	statusArgsForCall []struct {
		arg1 context.Context
		arg2 drivera.TxID
	}
	statusReturns struct {
		result1 driver.ValidationCode
		result2 string
		result3 error
	}
	statusReturnsOnCall map[int]struct {
		result1 driver.ValidationCode
		result2 string
		result3 error
	}
	StatusesStub        func(context.Context, ...drivera.TxID) ([]drivera.TxValidationStatus[driver.ValidationCode], error)
	statusesMutex       sync.RWMutex
	statusesArgsForCall []struct {
		arg1 context.Context
		arg2 []drivera.TxID
	}
	statusesReturns struct {
		result1 []drivera.TxValidationStatus[driver.ValidationCode]
		result2 error
	}
	statusesReturnsOnCall map[int]struct {
		result1 []drivera.TxValidationStatus[driver.ValidationCode]
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeVault) Close() error {
	fake.closeMutex.Lock()
	ret, specificReturn := fake.closeReturnsOnCall[len(fake.closeArgsForCall)]
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
	}{})
	stub := fake.CloseStub
	fakeReturns := fake.closeReturns
	fake.recordInvocation("Close", []interface{}{})
	fake.closeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeVault) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *FakeVault) CloseCalls(stub func() error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *FakeVault) CloseReturns(result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	fake.closeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeVault) CloseReturnsOnCall(i int, result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	if fake.closeReturnsOnCall == nil {
		fake.closeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.closeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeVault) CommitTX(arg1 context.Context, arg2 drivera.TxID, arg3 drivera.BlockNum, arg4 drivera.TxNum) error {
	fake.commitTXMutex.Lock()
	ret, specificReturn := fake.commitTXReturnsOnCall[len(fake.commitTXArgsForCall)]
	fake.commitTXArgsForCall = append(fake.commitTXArgsForCall, struct {
		arg1 context.Context
		arg2 drivera.TxID
		arg3 drivera.BlockNum
		arg4 drivera.TxNum
	}{arg1, arg2, arg3, arg4})
	stub := fake.CommitTXStub
	fakeReturns := fake.commitTXReturns
	fake.recordInvocation("CommitTX", []interface{}{arg1, arg2, arg3, arg4})
	fake.commitTXMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeVault) CommitTXCallCount() int {
	fake.commitTXMutex.RLock()
	defer fake.commitTXMutex.RUnlock()
	return len(fake.commitTXArgsForCall)
}

func (fake *FakeVault) CommitTXCalls(stub func(context.Context, drivera.TxID, drivera.BlockNum, drivera.TxNum) error) {
	fake.commitTXMutex.Lock()
	defer fake.commitTXMutex.Unlock()
	fake.CommitTXStub = stub
}

func (fake *FakeVault) CommitTXArgsForCall(i int) (context.Context, drivera.TxID, drivera.BlockNum, drivera.TxNum) {
	fake.commitTXMutex.RLock()
	defer fake.commitTXMutex.RUnlock()
	argsForCall := fake.commitTXArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeVault) CommitTXReturns(result1 error) {
	fake.commitTXMutex.Lock()
	defer fake.commitTXMutex.Unlock()
	fake.CommitTXStub = nil
	fake.commitTXReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeVault) CommitTXReturnsOnCall(i int, result1 error) {
	fake.commitTXMutex.Lock()
	defer fake.commitTXMutex.Unlock()
	fake.CommitTXStub = nil
	if fake.commitTXReturnsOnCall == nil {
		fake.commitTXReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.commitTXReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeVault) DiscardTx(arg1 context.Context, arg2 drivera.TxID, arg3 string) error {
	fake.discardTxMutex.Lock()
	ret, specificReturn := fake.discardTxReturnsOnCall[len(fake.discardTxArgsForCall)]
	fake.discardTxArgsForCall = append(fake.discardTxArgsForCall, struct {
		arg1 context.Context
		arg2 drivera.TxID
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.DiscardTxStub
	fakeReturns := fake.discardTxReturns
	fake.recordInvocation("DiscardTx", []interface{}{arg1, arg2, arg3})
	fake.discardTxMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeVault) DiscardTxCallCount() int {
	fake.discardTxMutex.RLock()
	defer fake.discardTxMutex.RUnlock()
	return len(fake.discardTxArgsForCall)
}

func (fake *FakeVault) DiscardTxCalls(stub func(context.Context, drivera.TxID, string) error) {
	fake.discardTxMutex.Lock()
	defer fake.discardTxMutex.Unlock()
	fake.DiscardTxStub = stub
}

func (fake *FakeVault) DiscardTxArgsForCall(i int) (context.Context, drivera.TxID, string) {
	fake.discardTxMutex.RLock()
	defer fake.discardTxMutex.RUnlock()
	argsForCall := fake.discardTxArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeVault) DiscardTxReturns(result1 error) {
	fake.discardTxMutex.Lock()
	defer fake.discardTxMutex.Unlock()
	fake.DiscardTxStub = nil
	fake.discardTxReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeVault) DiscardTxReturnsOnCall(i int, result1 error) {
	fake.discardTxMutex.Lock()
	defer fake.discardTxMutex.Unlock()
	fake.DiscardTxStub = nil
	if fake.discardTxReturnsOnCall == nil {
		fake.discardTxReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.discardTxReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeVault) InspectRWSet(arg1 context.Context, arg2 []byte, arg3 ...drivera.Namespace) (driver.RWSet, error) {
	var arg2Copy []byte
	if arg2 != nil {
		arg2Copy = make([]byte, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.inspectRWSetMutex.Lock()
	ret, specificReturn := fake.inspectRWSetReturnsOnCall[len(fake.inspectRWSetArgsForCall)]
	fake.inspectRWSetArgsForCall = append(fake.inspectRWSetArgsForCall, struct {
		arg1 context.Context
		arg2 []byte
		arg3 []drivera.Namespace
	}{arg1, arg2Copy, arg3})
	stub := fake.InspectRWSetStub
	fakeReturns := fake.inspectRWSetReturns
	fake.recordInvocation("InspectRWSet", []interface{}{arg1, arg2Copy, arg3})
	fake.inspectRWSetMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeVault) InspectRWSetCallCount() int {
	fake.inspectRWSetMutex.RLock()
	defer fake.inspectRWSetMutex.RUnlock()
	return len(fake.inspectRWSetArgsForCall)
}

func (fake *FakeVault) InspectRWSetCalls(stub func(context.Context, []byte, ...drivera.Namespace) (driver.RWSet, error)) {
	fake.inspectRWSetMutex.Lock()
	defer fake.inspectRWSetMutex.Unlock()
	fake.InspectRWSetStub = stub
}

func (fake *FakeVault) InspectRWSetArgsForCall(i int) (context.Context, []byte, []drivera.Namespace) {
	fake.inspectRWSetMutex.RLock()
	defer fake.inspectRWSetMutex.RUnlock()
	argsForCall := fake.inspectRWSetArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeVault) InspectRWSetReturns(result1 driver.RWSet, result2 error) {
	fake.inspectRWSetMutex.Lock()
	defer fake.inspectRWSetMutex.Unlock()
	fake.InspectRWSetStub = nil
	fake.inspectRWSetReturns = struct {
		result1 driver.RWSet
		result2 error
	}{result1, result2}
}

func (fake *FakeVault) InspectRWSetReturnsOnCall(i int, result1 driver.RWSet, result2 error) {
	fake.inspectRWSetMutex.Lock()
	defer fake.inspectRWSetMutex.Unlock()
	fake.InspectRWSetStub = nil
	if fake.inspectRWSetReturnsOnCall == nil {
		fake.inspectRWSetReturnsOnCall = make(map[int]struct {
			result1 driver.RWSet
			result2 error
		})
	}
	fake.inspectRWSetReturnsOnCall[i] = struct {
		result1 driver.RWSet
		result2 error
	}{result1, result2}
}

func (fake *FakeVault) Match(arg1 context.Context, arg2 drivera.TxID, arg3 []byte) error {
	var arg3Copy []byte
	if arg3 != nil {
		arg3Copy = make([]byte, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.matchMutex.Lock()
	ret, specificReturn := fake.matchReturnsOnCall[len(fake.matchArgsForCall)]
	fake.matchArgsForCall = append(fake.matchArgsForCall, struct {
		arg1 context.Context
		arg2 drivera.TxID
		arg3 []byte
	}{arg1, arg2, arg3Copy})
	stub := fake.MatchStub
	fakeReturns := fake.matchReturns
	fake.recordInvocation("Match", []interface{}{arg1, arg2, arg3Copy})
	fake.matchMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeVault) MatchCallCount() int {
	fake.matchMutex.RLock()
	defer fake.matchMutex.RUnlock()
	return len(fake.matchArgsForCall)
}

func (fake *FakeVault) MatchCalls(stub func(context.Context, drivera.TxID, []byte) error) {
	fake.matchMutex.Lock()
	defer fake.matchMutex.Unlock()
	fake.MatchStub = stub
}

func (fake *FakeVault) MatchArgsForCall(i int) (context.Context, drivera.TxID, []byte) {
	fake.matchMutex.RLock()
	defer fake.matchMutex.RUnlock()
	argsForCall := fake.matchArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeVault) MatchReturns(result1 error) {
	fake.matchMutex.Lock()
	defer fake.matchMutex.Unlock()
	fake.MatchStub = nil
	fake.matchReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeVault) MatchReturnsOnCall(i int, result1 error) {
	fake.matchMutex.Lock()
	defer fake.matchMutex.Unlock()
	fake.MatchStub = nil
	if fake.matchReturnsOnCall == nil {
		fake.matchReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.matchReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeVault) NewQueryExecutor(arg1 context.Context) (drivera.QueryExecutor, error) {
	fake.newQueryExecutorMutex.Lock()
	ret, specificReturn := fake.newQueryExecutorReturnsOnCall[len(fake.newQueryExecutorArgsForCall)]
	fake.newQueryExecutorArgsForCall = append(fake.newQueryExecutorArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.NewQueryExecutorStub
	fakeReturns := fake.newQueryExecutorReturns
	fake.recordInvocation("NewQueryExecutor", []interface{}{arg1})
	fake.newQueryExecutorMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeVault) NewQueryExecutorCallCount() int {
	fake.newQueryExecutorMutex.RLock()
	defer fake.newQueryExecutorMutex.RUnlock()
	return len(fake.newQueryExecutorArgsForCall)
}

func (fake *FakeVault) NewQueryExecutorCalls(stub func(context.Context) (drivera.QueryExecutor, error)) {
	fake.newQueryExecutorMutex.Lock()
	defer fake.newQueryExecutorMutex.Unlock()
	fake.NewQueryExecutorStub = stub
}

func (fake *FakeVault) NewQueryExecutorArgsForCall(i int) context.Context {
	fake.newQueryExecutorMutex.RLock()
	defer fake.newQueryExecutorMutex.RUnlock()
	argsForCall := fake.newQueryExecutorArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeVault) NewQueryExecutorReturns(result1 drivera.QueryExecutor, result2 error) {
	fake.newQueryExecutorMutex.Lock()
	defer fake.newQueryExecutorMutex.Unlock()
	fake.NewQueryExecutorStub = nil
	fake.newQueryExecutorReturns = struct {
		result1 drivera.QueryExecutor
		result2 error
	}{result1, result2}
}

func (fake *FakeVault) NewQueryExecutorReturnsOnCall(i int, result1 drivera.QueryExecutor, result2 error) {
	fake.newQueryExecutorMutex.Lock()
	defer fake.newQueryExecutorMutex.Unlock()
	fake.NewQueryExecutorStub = nil
	if fake.newQueryExecutorReturnsOnCall == nil {
		fake.newQueryExecutorReturnsOnCall = make(map[int]struct {
			result1 drivera.QueryExecutor
			result2 error
		})
	}
	fake.newQueryExecutorReturnsOnCall[i] = struct {
		result1 drivera.QueryExecutor
		result2 error
	}{result1, result2}
}

func (fake *FakeVault) NewRWSet(arg1 context.Context, arg2 drivera.TxID) (drivera.RWSet, error) {
	fake.newRWSetMutex.Lock()
	ret, specificReturn := fake.newRWSetReturnsOnCall[len(fake.newRWSetArgsForCall)]
	fake.newRWSetArgsForCall = append(fake.newRWSetArgsForCall, struct {
		arg1 context.Context
		arg2 drivera.TxID
	}{arg1, arg2})
	stub := fake.NewRWSetStub
	fakeReturns := fake.newRWSetReturns
	fake.recordInvocation("NewRWSet", []interface{}{arg1, arg2})
	fake.newRWSetMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeVault) NewRWSetCallCount() int {
	fake.newRWSetMutex.RLock()
	defer fake.newRWSetMutex.RUnlock()
	return len(fake.newRWSetArgsForCall)
}

func (fake *FakeVault) NewRWSetCalls(stub func(context.Context, drivera.TxID) (drivera.RWSet, error)) {
	fake.newRWSetMutex.Lock()
	defer fake.newRWSetMutex.Unlock()
	fake.NewRWSetStub = stub
}

func (fake *FakeVault) NewRWSetArgsForCall(i int) (context.Context, drivera.TxID) {
	fake.newRWSetMutex.RLock()
	defer fake.newRWSetMutex.RUnlock()
	argsForCall := fake.newRWSetArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeVault) NewRWSetReturns(result1 drivera.RWSet, result2 error) {
	fake.newRWSetMutex.Lock()
	defer fake.newRWSetMutex.Unlock()
	fake.NewRWSetStub = nil
	fake.newRWSetReturns = struct {
		result1 drivera.RWSet
		result2 error
	}{result1, result2}
}

func (fake *FakeVault) NewRWSetReturnsOnCall(i int, result1 drivera.RWSet, result2 error) {
	fake.newRWSetMutex.Lock()
	defer fake.newRWSetMutex.Unlock()
	fake.NewRWSetStub = nil
	if fake.newRWSetReturnsOnCall == nil {
		fake.newRWSetReturnsOnCall = make(map[int]struct {
			result1 drivera.RWSet
			result2 error
		})
	}
	fake.newRWSetReturnsOnCall[i] = struct {
		result1 drivera.RWSet
		result2 error
	}{result1, result2}
}

func (fake *FakeVault) NewRWSetFromBytes(arg1 context.Context, arg2 drivera.TxID, arg3 []byte) (drivera.RWSet, error) {
	var arg3Copy []byte
	if arg3 != nil {
		arg3Copy = make([]byte, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.newRWSetFromBytesMutex.Lock()
	ret, specificReturn := fake.newRWSetFromBytesReturnsOnCall[len(fake.newRWSetFromBytesArgsForCall)]
	fake.newRWSetFromBytesArgsForCall = append(fake.newRWSetFromBytesArgsForCall, struct {
		arg1 context.Context
		arg2 drivera.TxID
		arg3 []byte
	}{arg1, arg2, arg3Copy})
	stub := fake.NewRWSetFromBytesStub
	fakeReturns := fake.newRWSetFromBytesReturns
	fake.recordInvocation("NewRWSetFromBytes", []interface{}{arg1, arg2, arg3Copy})
	fake.newRWSetFromBytesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeVault) NewRWSetFromBytesCallCount() int {
	fake.newRWSetFromBytesMutex.RLock()
	defer fake.newRWSetFromBytesMutex.RUnlock()
	return len(fake.newRWSetFromBytesArgsForCall)
}

func (fake *FakeVault) NewRWSetFromBytesCalls(stub func(context.Context, drivera.TxID, []byte) (drivera.RWSet, error)) {
	fake.newRWSetFromBytesMutex.Lock()
	defer fake.newRWSetFromBytesMutex.Unlock()
	fake.NewRWSetFromBytesStub = stub
}

func (fake *FakeVault) NewRWSetFromBytesArgsForCall(i int) (context.Context, drivera.TxID, []byte) {
	fake.newRWSetFromBytesMutex.RLock()
	defer fake.newRWSetFromBytesMutex.RUnlock()
	argsForCall := fake.newRWSetFromBytesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeVault) NewRWSetFromBytesReturns(result1 drivera.RWSet, result2 error) {
	fake.newRWSetFromBytesMutex.Lock()
	defer fake.newRWSetFromBytesMutex.Unlock()
	fake.NewRWSetFromBytesStub = nil
	fake.newRWSetFromBytesReturns = struct {
		result1 drivera.RWSet
		result2 error
	}{result1, result2}
}

func (fake *FakeVault) NewRWSetFromBytesReturnsOnCall(i int, result1 drivera.RWSet, result2 error) {
	fake.newRWSetFromBytesMutex.Lock()
	defer fake.newRWSetFromBytesMutex.Unlock()
	fake.NewRWSetFromBytesStub = nil
	if fake.newRWSetFromBytesReturnsOnCall == nil {
		fake.newRWSetFromBytesReturnsOnCall = make(map[int]struct {
			result1 drivera.RWSet
			result2 error
		})
	}
	fake.newRWSetFromBytesReturnsOnCall[i] = struct {
		result1 drivera.RWSet
		result2 error
	}{result1, result2}
}

func (fake *FakeVault) RWSExists(arg1 context.Context, arg2 drivera.TxID) bool {
	fake.rWSExistsMutex.Lock()
	ret, specificReturn := fake.rWSExistsReturnsOnCall[len(fake.rWSExistsArgsForCall)]
	fake.rWSExistsArgsForCall = append(fake.rWSExistsArgsForCall, struct {
		arg1 context.Context
		arg2 drivera.TxID
	}{arg1, arg2})
	stub := fake.RWSExistsStub
	fakeReturns := fake.rWSExistsReturns
	fake.recordInvocation("RWSExists", []interface{}{arg1, arg2})
	fake.rWSExistsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeVault) RWSExistsCallCount() int {
	fake.rWSExistsMutex.RLock()
	defer fake.rWSExistsMutex.RUnlock()
	return len(fake.rWSExistsArgsForCall)
}

func (fake *FakeVault) RWSExistsCalls(stub func(context.Context, drivera.TxID) bool) {
	fake.rWSExistsMutex.Lock()
	defer fake.rWSExistsMutex.Unlock()
	fake.RWSExistsStub = stub
}

func (fake *FakeVault) RWSExistsArgsForCall(i int) (context.Context, drivera.TxID) {
	fake.rWSExistsMutex.RLock()
	defer fake.rWSExistsMutex.RUnlock()
	argsForCall := fake.rWSExistsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeVault) RWSExistsReturns(result1 bool) {
	fake.rWSExistsMutex.Lock()
	defer fake.rWSExistsMutex.Unlock()
	fake.RWSExistsStub = nil
	fake.rWSExistsReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeVault) RWSExistsReturnsOnCall(i int, result1 bool) {
	fake.rWSExistsMutex.Lock()
	defer fake.rWSExistsMutex.Unlock()
	fake.RWSExistsStub = nil
	if fake.rWSExistsReturnsOnCall == nil {
		fake.rWSExistsReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.rWSExistsReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeVault) SetDiscarded(arg1 context.Context, arg2 drivera.TxID, arg3 string) error {
	fake.setDiscardedMutex.Lock()
	ret, specificReturn := fake.setDiscardedReturnsOnCall[len(fake.setDiscardedArgsForCall)]
	fake.setDiscardedArgsForCall = append(fake.setDiscardedArgsForCall, struct {
		arg1 context.Context
		arg2 drivera.TxID
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.SetDiscardedStub
	fakeReturns := fake.setDiscardedReturns
	fake.recordInvocation("SetDiscarded", []interface{}{arg1, arg2, arg3})
	fake.setDiscardedMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeVault) SetDiscardedCallCount() int {
	fake.setDiscardedMutex.RLock()
	defer fake.setDiscardedMutex.RUnlock()
	return len(fake.setDiscardedArgsForCall)
}

func (fake *FakeVault) SetDiscardedCalls(stub func(context.Context, drivera.TxID, string) error) {
	fake.setDiscardedMutex.Lock()
	defer fake.setDiscardedMutex.Unlock()
	fake.SetDiscardedStub = stub
}

func (fake *FakeVault) SetDiscardedArgsForCall(i int) (context.Context, drivera.TxID, string) {
	fake.setDiscardedMutex.RLock()
	defer fake.setDiscardedMutex.RUnlock()
	argsForCall := fake.setDiscardedArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeVault) SetDiscardedReturns(result1 error) {
	fake.setDiscardedMutex.Lock()
	defer fake.setDiscardedMutex.Unlock()
	fake.SetDiscardedStub = nil
	fake.setDiscardedReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeVault) SetDiscardedReturnsOnCall(i int, result1 error) {
	fake.setDiscardedMutex.Lock()
	defer fake.setDiscardedMutex.Unlock()
	fake.SetDiscardedStub = nil
	if fake.setDiscardedReturnsOnCall == nil {
		fake.setDiscardedReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.setDiscardedReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeVault) Status(arg1 context.Context, arg2 drivera.TxID) (driver.ValidationCode, string, error) {
	fake.statusMutex.Lock()
	ret, specificReturn := fake.statusReturnsOnCall[len(fake.statusArgsForCall)]
	fake.statusArgsForCall = append(fake.statusArgsForCall, struct {
		arg1 context.Context
		arg2 drivera.TxID
	}{arg1, arg2})
	stub := fake.StatusStub
	fakeReturns := fake.statusReturns
	fake.recordInvocation("Status", []interface{}{arg1, arg2})
	fake.statusMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeVault) StatusCallCount() int {
	fake.statusMutex.RLock()
	defer fake.statusMutex.RUnlock()
	return len(fake.statusArgsForCall)
}

func (fake *FakeVault) StatusCalls(stub func(context.Context, drivera.TxID) (driver.ValidationCode, string, error)) {
	fake.statusMutex.Lock()
	defer fake.statusMutex.Unlock()
	fake.StatusStub = stub
}

func (fake *FakeVault) StatusArgsForCall(i int) (context.Context, drivera.TxID) {
	fake.statusMutex.RLock()
	defer fake.statusMutex.RUnlock()
	argsForCall := fake.statusArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeVault) StatusReturns(result1 driver.ValidationCode, result2 string, result3 error) {
	fake.statusMutex.Lock()
	defer fake.statusMutex.Unlock()
	fake.StatusStub = nil
	fake.statusReturns = struct {
		result1 driver.ValidationCode
		result2 string
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeVault) StatusReturnsOnCall(i int, result1 driver.ValidationCode, result2 string, result3 error) {
	fake.statusMutex.Lock()
	defer fake.statusMutex.Unlock()
	fake.StatusStub = nil
	if fake.statusReturnsOnCall == nil {
		fake.statusReturnsOnCall = make(map[int]struct {
			result1 driver.ValidationCode
			result2 string
			result3 error
		})
	}
	fake.statusReturnsOnCall[i] = struct {
		result1 driver.ValidationCode
		result2 string
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeVault) Statuses(arg1 context.Context, arg2 ...drivera.TxID) ([]drivera.TxValidationStatus[driver.ValidationCode], error) {
	fake.statusesMutex.Lock()
	ret, specificReturn := fake.statusesReturnsOnCall[len(fake.statusesArgsForCall)]
	fake.statusesArgsForCall = append(fake.statusesArgsForCall, struct {
		arg1 context.Context
		arg2 []drivera.TxID
	}{arg1, arg2})
	stub := fake.StatusesStub
	fakeReturns := fake.statusesReturns
	fake.recordInvocation("Statuses", []interface{}{arg1, arg2})
	fake.statusesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeVault) StatusesCallCount() int {
	fake.statusesMutex.RLock()
	defer fake.statusesMutex.RUnlock()
	return len(fake.statusesArgsForCall)
}

func (fake *FakeVault) StatusesCalls(stub func(context.Context, ...drivera.TxID) ([]drivera.TxValidationStatus[driver.ValidationCode], error)) {
	fake.statusesMutex.Lock()
	defer fake.statusesMutex.Unlock()
	fake.StatusesStub = stub
}

func (fake *FakeVault) StatusesArgsForCall(i int) (context.Context, []drivera.TxID) {
	fake.statusesMutex.RLock()
	defer fake.statusesMutex.RUnlock()
	argsForCall := fake.statusesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeVault) StatusesReturns(result1 []drivera.TxValidationStatus[driver.ValidationCode], result2 error) {
	fake.statusesMutex.Lock()
	defer fake.statusesMutex.Unlock()
	fake.StatusesStub = nil
	fake.statusesReturns = struct {
		result1 []drivera.TxValidationStatus[driver.ValidationCode]
		result2 error
	}{result1, result2}
}

func (fake *FakeVault) StatusesReturnsOnCall(i int, result1 []drivera.TxValidationStatus[driver.ValidationCode], result2 error) {
	fake.statusesMutex.Lock()
	defer fake.statusesMutex.Unlock()
	fake.StatusesStub = nil
	if fake.statusesReturnsOnCall == nil {
		fake.statusesReturnsOnCall = make(map[int]struct {
			result1 []drivera.TxValidationStatus[driver.ValidationCode]
			result2 error
		})
	}
	fake.statusesReturnsOnCall[i] = struct {
		result1 []drivera.TxValidationStatus[driver.ValidationCode]
		result2 error
	}{result1, result2}
}

func (fake *FakeVault) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeVault) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ driver.Vault = new(FakeVault)
