/*
Copyright IBM Corp. All Rights Reserved.

SPDX-License-Identifier: Apache-2.0
*/

package network

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"

	"github.com/hyperledger-labs/fabric-smart-client/integration/nwo/fabric/commands"
	"github.com/hyperledger-labs/fabric-smart-client/integration/nwo/fabric/topology"
	"github.com/onsi/gomega"
	"github.com/onsi/gomega/gexec"
)

// namespaceApproverOrgs returns the list of org names that appear
// in the channel LifecycleEndorsement policy
func namespaceApproverOrgs(n *Network) ([]string, error) {
	// This regex extracts the org name from policy expressions
	mspMemberPolicyRE := regexp.MustCompile(`'([^']+)MSP\.member'`)

	fabricTopology := n.Topology()
	if fabricTopology == nil {
		return nil, fmt.Errorf("fabric topology not available")
	}

	for _, profile := range fabricTopology.Profiles {
		if profile.Name != "OrgsChannel" {
			continue
		}

		for _, policy := range profile.Policies {
			if policy.Name != "LifecycleEndorsement" {
				continue
			}

			matches := mspMemberPolicyRE.FindAllStringSubmatch(policy.Rule, -1)
			if len(matches) == 0 {
				return nil, fmt.Errorf("no MSP orgs found in LifecycleEndorsement policy [%s]", policy.Rule)
			}

			orgs := make([]string, 0, len(matches))
			seen := map[string]struct{}{}
			for _, match := range matches {
				org := match[1]
				if _, ok := seen[org]; ok {
					continue
				}
				seen[org] = struct{}{}
				orgs = append(orgs, org)
			}
			return orgs, nil
		}

		return nil, fmt.Errorf("LifecycleEndorsement policy not found in profile [%s]", profile.Name)
	}

	return nil, fmt.Errorf("profile [OrgsChannel] not found")
}

// namespaceApproverOrg is a helper that returns a single org, the first one
func namespaceApproverOrg(n *Network) (string, error) {
	orgs, err := namespaceApproverOrgs(n)
	if err != nil {
		return "", err
	}
	if len(orgs) == 0 {
		return "", fmt.Errorf("no namespace approver orgs found")
	}
	return orgs[0], nil
}

func createMetanamespaceKey(n *Network) error {
	orgName, err := namespaceApproverOrg(n)
	if err != nil {
		return err
	}

	peers := n.PeersInOrg(orgName)
	if len(peers) == 0 {
		return fmt.Errorf("no peers found for namespace approver org [%s]", orgName)
	}

	certPath := n.PeerUserCert(peers[0], "Admin")
	certBytes, err := os.ReadFile(certPath)
	if err != nil {
		return err
	}

	pkPath := filepath.Join(n.RootDir, n.Prefix, "crypto", "sc_pubkey.pem")
	logger.Infof("Write admin pk for org [%s] from [%s] to [%s]", orgName, certPath, pkPath)
	return os.WriteFile(pkPath, certBytes, 0o644)
}

func createChannelBlock(n *Network, c *topology.Channel) commands.OutputBlock {
	return commands.OutputBlock{
		NetworkPrefix: n.Prefix,
		ChannelID:     c.Name,
		Profile:       c.Profile,
		ConfigPath:    filepath.Join(n.Context.RootDir(), n.Prefix),
		OutputBlock:   n.OutputBlockPath(c.Name),
	}
}

// bootstrapIdemix creates the idemix-related crypto material.
func bootstrapIdemix(n *Network) {
	for _, org := range n.IdemixOrgs() {
		output := n.IdemixOrgMSPDir(org)
		// - ca-keygen
		sess, err := n.Idemixgen(commands.CAKeyGen{
			NetworkPrefix: n.Prefix,
			Output:        output,
		})
		gomega.Expect(err).NotTo(gomega.HaveOccurred())
		gomega.Eventually(sess, n.EventuallyTimeout).Should(gexec.Exit(0))
	}
}

func bootstrapExtraIdentities(n *Network) {
	for i, peer := range n.Peers {
		for j, identity := range peer.Identities {
			switch identity.MSPType {
			case "idemix":
				org := n.Organization(identity.Org)
				output := n.IdemixOrgMSPDir(org)
				userOutput := filepath.Join(n.PeerLocalIdemixExtraIdentitiesDir(peer), identity.ID)
				sess, err := n.Idemixgen(commands.SignerConfig{
					NetworkPrefix:    n.Prefix,
					CAInput:          output,
					Output:           userOutput,
					OrgUnit:          org.Domain,
					EnrollmentID:     identity.EnrollmentID,
					RevocationHandle: fmt.Sprintf("1%d%d", i, j),
				})
				gomega.Expect(err).NotTo(gomega.HaveOccurred())
				gomega.Eventually(sess, n.EventuallyTimeout).Should(gexec.Exit(0))
			case "bccsp":
				// Nothing to do here cause the extra identities are generated by crypto gen.
			default:
				gomega.Expect(identity.MSPType).To(gomega.Equal("idemix"))
			}
		}
	}
}
