/*
Copyright IBM Corp. All Rights Reserved.

SPDX-License-Identifier: Apache-2.0
*/

package view_test

import (
	"context"
	"testing"

	"github.com/hyperledger-labs/fabric-smart-client/platform/view/services/metrics/disabled"
	"github.com/hyperledger-labs/fabric-smart-client/platform/view/services/view"
	"github.com/hyperledger-labs/fabric-smart-client/platform/view/services/view/mock"
	view2 "github.com/hyperledger-labs/fabric-smart-client/platform/view/view"
	"github.com/stretchr/testify/require"
)

func TestManagerWithMockFactory(t *testing.T) {
	t.Parallel()
	ip := &mock.IdentityProvider{}
	registry := view.NewRegistry()
	mp := &disabled.Provider{}

	metrics := view.NewMetrics(mp)
	cf := &mock.ContextFactory{}
	manager := view.NewManager(ip, registry, metrics, cf)

	t.Run("InitiateContextCallsFactory", func(t *testing.T) {
		t.Parallel()
		v := &mock.View{}
		parentCtx := &mock.ParentContext{}
		parentCtx.ContextReturns(context.Background())
		parentCtx.IDReturns("ctx-id-1")
		cf.NewForInitiatorReturns(parentCtx, nil)

		ctx, err := manager.InitiateContext(context.Background(), v)
		require.NoError(t, err)
		require.NotNil(t, ctx)
		require.Equal(t, 1, cf.NewForInitiatorCallCount())

		_, contextID, _, initiator := cf.NewForInitiatorArgsForCall(0)
		require.Empty(t, contextID) // Expect empty because it will be generated by the factory if empty
		require.Equal(t, v, initiator)
	})

	t.Run("NewSessionContextCallsFactory", func(t *testing.T) {
		t.Parallel()
		session := &mock.Session{}
		session.InfoReturns(view2.SessionInfo{ID: "s1", Caller: view2.Identity("alice")})
		party := view2.Identity("alice")

		parentCtx := &mock.ParentContext{}
		parentCtx.ContextReturns(context.Background())
		parentCtx.IDReturns("ctx-id-2")
		cf.NewForResponderReturns(parentCtx, nil)

		ctx, isNew, err := manager.NewResponderContext(context.Background(), "ctx-id-2", session, ip.DefaultIdentity(), party)
		require.NoError(t, err)
		require.True(t, isNew)
		require.NotNil(t, ctx)
		require.Equal(t, 1, cf.NewForResponderCallCount())

		_, contextID, me, sess, p := cf.NewForResponderArgsForCall(0)
		require.Equal(t, "ctx-id-2", contextID)
		require.Equal(t, ip.DefaultIdentity(), me)
		require.Equal(t, session, sess)
		require.Equal(t, party, p)
	})
}
