/*
Copyright IBM Corp. All Rights Reserved.

SPDX-License-Identifier: Apache-2.0
*/

package idemix_test

import (
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	idemixconfig "github.com/IBM/idemix/msp/config"
	"github.com/hyperledger-labs/fabric-smart-client/pkg/utils/proto"
	idemix2 "github.com/hyperledger-labs/fabric-smart-client/platform/fabric/core/generic/msp/idemix"
	fabricmsp "github.com/hyperledger-labs/fabric-smart-client/platform/fabric/core/msp"
	"github.com/hyperledger-labs/fabric-smart-client/platform/view/services/sig"
	"github.com/hyperledger-labs/fabric-smart-client/platform/view/services/storage/driver"
	mem "github.com/hyperledger-labs/fabric-smart-client/platform/view/services/storage/driver/memory"
	"github.com/hyperledger-labs/fabric-smart-client/platform/view/services/storage/kvs"
	"github.com/stretchr/testify/require"
)

const curvesRoot = "./testdata/curves"

// curveIDForDir derives the idemixgen curve identifier (e.g. "BLS12_381_BBS") from a
// fixture directory produced by testdata/curves/generate.sh, of the form
// testdata/curves/<scheme>/<CURVE>[/admin]. fabricmsp.GetLocalMspConfigWithType never
// populates IdemixMSPConfig.CurveId itself (idemixgen does not persist the curve name in
// any of the on-disk fixture files), so tests must set it explicitly to exercise anything
// beyond each scheme's default curve.
func curveIDForDir(dir string) string {
	parts := strings.Split(filepath.ToSlash(dir), "/")
	for i, part := range parts {
		if part == "admin" && i > 0 {
			return parts[i-1]
		}
	}
	return parts[len(parts)-1]
}

// curveDirs returns, for every scheme (dlog, aries) and curve fixture generated by
// testdata/curves/generate.sh, the directory containing that curve's member MSP
// configuration (msp/, user/) and admin identity (admin/msp/, admin/user/), so tests can
// exercise every supported curve/scheme combination.
func curveDirs(t *testing.T) []string {
	t.Helper()

	schemes, err := os.ReadDir(curvesRoot)
	require.NoError(t, err)

	var dirs []string
	for _, scheme := range schemes {
		if !scheme.IsDir() {
			continue
		}
		schemeDir := filepath.Join(curvesRoot, scheme.Name())
		curves, err := os.ReadDir(schemeDir)
		require.NoError(t, err)
		for _, curve := range curves {
			if !curve.IsDir() {
				continue
			}
			dirs = append(dirs, filepath.Join(schemeDir, curve.Name()))
		}
	}
	sort.Strings(dirs)
	require.NotEmpty(t, dirs, "no curve fixtures found under %s", curvesRoot)

	return dirs
}

func newSignerInfo(t *testing.T) driver.SignerInfoStore {
	t.Helper()
	s, err := mem.NewDriver().NewSignerInfo("")
	require.NoError(t, err)
	return s
}

func newAuditInfo(t *testing.T) driver.AuditInfoStore {
	t.Helper()
	s, err := mem.NewDriver().NewAuditInfo("")
	require.NoError(t, err)
	return s
}

func newKVS(t *testing.T) driver.KeyValueStore {
	t.Helper()
	s, err := mem.NewDriver().NewKVS("")
	require.NoError(t, err)
	return s
}

func newProvider(t *testing.T, dir string) *idemix2.Provider {
	t.Helper()

	kvss, err := kvs.New(newKVS(t), "", kvs.DefaultCacheSize)
	require.NoError(t, err)

	sigService := sig.NewService(sig.NewMultiplexDeserializer(), newAuditInfo(t), newSignerInfo(t))

	mspConfig, err := fabricmsp.GetLocalMspConfigWithType(dir, nil, "idemix", "idemix")
	require.NoError(t, err)

	var idemixCfg idemixconfig.IdemixMSPConfig
	require.NoError(t, proto.Unmarshal(mspConfig.Config, &idemixCfg))
	idemixCfg.CurveId = curveIDForDir(dir)
	mspConfig.Config, err = proto.Marshal(&idemixCfg)
	require.NoError(t, err)

	p, err := idemix2.NewProvider(mspConfig, kvss, sigService)
	require.NoError(t, err)
	require.NotNil(t, p)

	return p
}

func TestProvider(t *testing.T) { //nolint:paralleltest
	for _, dir := range curveDirs(t) {
		t.Run(dir, func(t *testing.T) { //nolint:paralleltest
			newProvider(t, dir)
		})
	}
}

func TestIdentityStandard(t *testing.T) { //nolint:paralleltest
	for _, dir := range curveDirs(t) {
		t.Run(dir, func(t *testing.T) { //nolint:paralleltest
			p := newProvider(t, dir)

			id, audit, err := p.Identity(nil)
			require.NoError(t, err)
			require.NotNil(t, id)
			require.Nil(t, audit)

			signer, err := p.DeserializeSigner(id)
			require.NoError(t, err)
			verifier, err := p.DeserializeVerifier(id)
			require.NoError(t, err)

			sigma, err := signer.Sign([]byte("hello world!!!"))
			require.NoError(t, err)
			require.NoError(t, verifier.Verify([]byte("hello world!!!"), sigma))
		})
	}
}

func TestProvider_DeserializeSigner(t *testing.T) { //nolint:paralleltest
	for _, dir := range curveDirs(t) {
		t.Run(dir, func(t *testing.T) { //nolint:paralleltest
			p := newProvider(t, dir)
			p2 := newProvider(t, filepath.Join(dir, "admin"))

			id, _, err := p.Identity(nil)
			require.NoError(t, err)

			id2, _, err := p2.Identity(nil)
			require.NoError(t, err)

			// This must work
			signer, err := p.DeserializeSigner(id)
			require.NoError(t, err)
			verifier, err := p.DeserializeVerifier(id)
			require.NoError(t, err)
			msg := []byte("Hello World!!!")
			sigma, err := signer.Sign(msg)
			require.NoError(t, err)
			require.NoError(t, verifier.Verify(msg, sigma))

			// Try to deserialize id2 with provider for id, must fail
			_, err = p.DeserializeSigner(id2)
			require.Error(t, err)
			_, err = p.DeserializeVerifier(id2)
			require.NoError(t, err)

			// this must work
			des := sig.NewMultiplexDeserializer()
			des.AddDeserializer(p)
			des.AddDeserializer(p2)
			signer, err = des.DeserializeSigner(id)
			require.NoError(t, err)
			verifier, err = des.DeserializeVerifier(id)
			require.NoError(t, err)
			sigma, err = signer.Sign(msg)
			require.NoError(t, err)
			require.NoError(t, verifier.Verify(msg, sigma))
		})
	}
}

func TestProvider_IdentityManagerMethods(t *testing.T) { //nolint:paralleltest
	for _, dir := range curveDirs(t) {
		t.Run(dir, func(t *testing.T) { //nolint:paralleltest
			p := newProvider(t, dir)

			id, _, err := p.Identity(nil)
			require.NoError(t, err)

			sigID, err := p.DeserializeSigner(id)
			require.NoError(t, err)
			require.NotNil(t, sigID)

			_, err = p.DeserializeVerifier(id)
			require.NoError(t, err)

			info, err := p.Info(id, nil)
			require.NoError(t, err)
			require.NotEmpty(t, info)
		})
	}
}
