// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"context"
	"sync"

	"github.com/hyperledger-labs/fabric-smart-client/platform/fabric/driver"
)

type FakeFinality struct {
	IsFinalStub        func(context.Context, string) error
	isFinalMutex       sync.RWMutex
	isFinalArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	isFinalReturns struct {
		result1 error
	}
	isFinalReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeFinality) IsFinal(arg1 context.Context, arg2 string) error {
	fake.isFinalMutex.Lock()
	ret, specificReturn := fake.isFinalReturnsOnCall[len(fake.isFinalArgsForCall)]
	fake.isFinalArgsForCall = append(fake.isFinalArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.IsFinalStub
	fakeReturns := fake.isFinalReturns
	fake.recordInvocation("IsFinal", []interface{}{arg1, arg2})
	fake.isFinalMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeFinality) IsFinalCallCount() int {
	fake.isFinalMutex.RLock()
	defer fake.isFinalMutex.RUnlock()
	return len(fake.isFinalArgsForCall)
}

func (fake *FakeFinality) IsFinalCalls(stub func(context.Context, string) error) {
	fake.isFinalMutex.Lock()
	defer fake.isFinalMutex.Unlock()
	fake.IsFinalStub = stub
}

func (fake *FakeFinality) IsFinalArgsForCall(i int) (context.Context, string) {
	fake.isFinalMutex.RLock()
	defer fake.isFinalMutex.RUnlock()
	argsForCall := fake.isFinalArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeFinality) IsFinalReturns(result1 error) {
	fake.isFinalMutex.Lock()
	defer fake.isFinalMutex.Unlock()
	fake.IsFinalStub = nil
	fake.isFinalReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeFinality) IsFinalReturnsOnCall(i int, result1 error) {
	fake.isFinalMutex.Lock()
	defer fake.isFinalMutex.Unlock()
	fake.IsFinalStub = nil
	if fake.isFinalReturnsOnCall == nil {
		fake.isFinalReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.isFinalReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeFinality) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeFinality) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ driver.Finality = new(FakeFinality)
