// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"sync"

	"github.com/hyperledger-labs/fabric-smart-client/platform/fabric/driver"
)

type FakeFabricNetworkServiceProvider struct {
	DefaultNameStub        func() string
	defaultNameMutex       sync.RWMutex
	defaultNameArgsForCall []struct {
	}
	defaultNameReturns struct {
		result1 string
	}
	defaultNameReturnsOnCall map[int]struct {
		result1 string
	}
	FabricNetworkServiceStub        func(string) (driver.FabricNetworkService, error)
	fabricNetworkServiceMutex       sync.RWMutex
	fabricNetworkServiceArgsForCall []struct {
		arg1 string
	}
	fabricNetworkServiceReturns struct {
		result1 driver.FabricNetworkService
		result2 error
	}
	fabricNetworkServiceReturnsOnCall map[int]struct {
		result1 driver.FabricNetworkService
		result2 error
	}
	NamesStub        func() []string
	namesMutex       sync.RWMutex
	namesArgsForCall []struct {
	}
	namesReturns struct {
		result1 []string
	}
	namesReturnsOnCall map[int]struct {
		result1 []string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeFabricNetworkServiceProvider) DefaultName() string {
	fake.defaultNameMutex.Lock()
	ret, specificReturn := fake.defaultNameReturnsOnCall[len(fake.defaultNameArgsForCall)]
	fake.defaultNameArgsForCall = append(fake.defaultNameArgsForCall, struct {
	}{})
	stub := fake.DefaultNameStub
	fakeReturns := fake.defaultNameReturns
	fake.recordInvocation("DefaultName", []interface{}{})
	fake.defaultNameMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeFabricNetworkServiceProvider) DefaultNameCallCount() int {
	fake.defaultNameMutex.RLock()
	defer fake.defaultNameMutex.RUnlock()
	return len(fake.defaultNameArgsForCall)
}

func (fake *FakeFabricNetworkServiceProvider) DefaultNameCalls(stub func() string) {
	fake.defaultNameMutex.Lock()
	defer fake.defaultNameMutex.Unlock()
	fake.DefaultNameStub = stub
}

func (fake *FakeFabricNetworkServiceProvider) DefaultNameReturns(result1 string) {
	fake.defaultNameMutex.Lock()
	defer fake.defaultNameMutex.Unlock()
	fake.DefaultNameStub = nil
	fake.defaultNameReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeFabricNetworkServiceProvider) DefaultNameReturnsOnCall(i int, result1 string) {
	fake.defaultNameMutex.Lock()
	defer fake.defaultNameMutex.Unlock()
	fake.DefaultNameStub = nil
	if fake.defaultNameReturnsOnCall == nil {
		fake.defaultNameReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.defaultNameReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeFabricNetworkServiceProvider) FabricNetworkService(arg1 string) (driver.FabricNetworkService, error) {
	fake.fabricNetworkServiceMutex.Lock()
	ret, specificReturn := fake.fabricNetworkServiceReturnsOnCall[len(fake.fabricNetworkServiceArgsForCall)]
	fake.fabricNetworkServiceArgsForCall = append(fake.fabricNetworkServiceArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.FabricNetworkServiceStub
	fakeReturns := fake.fabricNetworkServiceReturns
	fake.recordInvocation("FabricNetworkService", []interface{}{arg1})
	fake.fabricNetworkServiceMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeFabricNetworkServiceProvider) FabricNetworkServiceCallCount() int {
	fake.fabricNetworkServiceMutex.RLock()
	defer fake.fabricNetworkServiceMutex.RUnlock()
	return len(fake.fabricNetworkServiceArgsForCall)
}

func (fake *FakeFabricNetworkServiceProvider) FabricNetworkServiceCalls(stub func(string) (driver.FabricNetworkService, error)) {
	fake.fabricNetworkServiceMutex.Lock()
	defer fake.fabricNetworkServiceMutex.Unlock()
	fake.FabricNetworkServiceStub = stub
}

func (fake *FakeFabricNetworkServiceProvider) FabricNetworkServiceArgsForCall(i int) string {
	fake.fabricNetworkServiceMutex.RLock()
	defer fake.fabricNetworkServiceMutex.RUnlock()
	argsForCall := fake.fabricNetworkServiceArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeFabricNetworkServiceProvider) FabricNetworkServiceReturns(result1 driver.FabricNetworkService, result2 error) {
	fake.fabricNetworkServiceMutex.Lock()
	defer fake.fabricNetworkServiceMutex.Unlock()
	fake.FabricNetworkServiceStub = nil
	fake.fabricNetworkServiceReturns = struct {
		result1 driver.FabricNetworkService
		result2 error
	}{result1, result2}
}

func (fake *FakeFabricNetworkServiceProvider) FabricNetworkServiceReturnsOnCall(i int, result1 driver.FabricNetworkService, result2 error) {
	fake.fabricNetworkServiceMutex.Lock()
	defer fake.fabricNetworkServiceMutex.Unlock()
	fake.FabricNetworkServiceStub = nil
	if fake.fabricNetworkServiceReturnsOnCall == nil {
		fake.fabricNetworkServiceReturnsOnCall = make(map[int]struct {
			result1 driver.FabricNetworkService
			result2 error
		})
	}
	fake.fabricNetworkServiceReturnsOnCall[i] = struct {
		result1 driver.FabricNetworkService
		result2 error
	}{result1, result2}
}

func (fake *FakeFabricNetworkServiceProvider) Names() []string {
	fake.namesMutex.Lock()
	ret, specificReturn := fake.namesReturnsOnCall[len(fake.namesArgsForCall)]
	fake.namesArgsForCall = append(fake.namesArgsForCall, struct {
	}{})
	stub := fake.NamesStub
	fakeReturns := fake.namesReturns
	fake.recordInvocation("Names", []interface{}{})
	fake.namesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeFabricNetworkServiceProvider) NamesCallCount() int {
	fake.namesMutex.RLock()
	defer fake.namesMutex.RUnlock()
	return len(fake.namesArgsForCall)
}

func (fake *FakeFabricNetworkServiceProvider) NamesCalls(stub func() []string) {
	fake.namesMutex.Lock()
	defer fake.namesMutex.Unlock()
	fake.NamesStub = stub
}

func (fake *FakeFabricNetworkServiceProvider) NamesReturns(result1 []string) {
	fake.namesMutex.Lock()
	defer fake.namesMutex.Unlock()
	fake.NamesStub = nil
	fake.namesReturns = struct {
		result1 []string
	}{result1}
}

func (fake *FakeFabricNetworkServiceProvider) NamesReturnsOnCall(i int, result1 []string) {
	fake.namesMutex.Lock()
	defer fake.namesMutex.Unlock()
	fake.NamesStub = nil
	if fake.namesReturnsOnCall == nil {
		fake.namesReturnsOnCall = make(map[int]struct {
			result1 []string
		})
	}
	fake.namesReturnsOnCall[i] = struct {
		result1 []string
	}{result1}
}

func (fake *FakeFabricNetworkServiceProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeFabricNetworkServiceProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ driver.FabricNetworkServiceProvider = new(FakeFabricNetworkServiceProvider)
