// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"context"
	"sync"

	"github.com/hyperledger-labs/fabric-smart-client/platform/fabric/driver"
)

type FakeOrdering struct {
	BroadcastStub        func(context.Context, interface{}) error
	broadcastMutex       sync.RWMutex
	broadcastArgsForCall []struct {
		arg1 context.Context
		arg2 interface{}
	}
	broadcastReturns struct {
		result1 error
	}
	broadcastReturnsOnCall map[int]struct {
		result1 error
	}
	SetConsensusTypeStub        func(string) error
	setConsensusTypeMutex       sync.RWMutex
	setConsensusTypeArgsForCall []struct {
		arg1 string
	}
	setConsensusTypeReturns struct {
		result1 error
	}
	setConsensusTypeReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeOrdering) Broadcast(arg1 context.Context, arg2 interface{}) error {
	fake.broadcastMutex.Lock()
	ret, specificReturn := fake.broadcastReturnsOnCall[len(fake.broadcastArgsForCall)]
	fake.broadcastArgsForCall = append(fake.broadcastArgsForCall, struct {
		arg1 context.Context
		arg2 interface{}
	}{arg1, arg2})
	stub := fake.BroadcastStub
	fakeReturns := fake.broadcastReturns
	fake.recordInvocation("Broadcast", []interface{}{arg1, arg2})
	fake.broadcastMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeOrdering) BroadcastCallCount() int {
	fake.broadcastMutex.RLock()
	defer fake.broadcastMutex.RUnlock()
	return len(fake.broadcastArgsForCall)
}

func (fake *FakeOrdering) BroadcastCalls(stub func(context.Context, interface{}) error) {
	fake.broadcastMutex.Lock()
	defer fake.broadcastMutex.Unlock()
	fake.BroadcastStub = stub
}

func (fake *FakeOrdering) BroadcastArgsForCall(i int) (context.Context, interface{}) {
	fake.broadcastMutex.RLock()
	defer fake.broadcastMutex.RUnlock()
	argsForCall := fake.broadcastArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeOrdering) BroadcastReturns(result1 error) {
	fake.broadcastMutex.Lock()
	defer fake.broadcastMutex.Unlock()
	fake.BroadcastStub = nil
	fake.broadcastReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeOrdering) BroadcastReturnsOnCall(i int, result1 error) {
	fake.broadcastMutex.Lock()
	defer fake.broadcastMutex.Unlock()
	fake.BroadcastStub = nil
	if fake.broadcastReturnsOnCall == nil {
		fake.broadcastReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.broadcastReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeOrdering) SetConsensusType(arg1 string) error {
	fake.setConsensusTypeMutex.Lock()
	ret, specificReturn := fake.setConsensusTypeReturnsOnCall[len(fake.setConsensusTypeArgsForCall)]
	fake.setConsensusTypeArgsForCall = append(fake.setConsensusTypeArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.SetConsensusTypeStub
	fakeReturns := fake.setConsensusTypeReturns
	fake.recordInvocation("SetConsensusType", []interface{}{arg1})
	fake.setConsensusTypeMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeOrdering) SetConsensusTypeCallCount() int {
	fake.setConsensusTypeMutex.RLock()
	defer fake.setConsensusTypeMutex.RUnlock()
	return len(fake.setConsensusTypeArgsForCall)
}

func (fake *FakeOrdering) SetConsensusTypeCalls(stub func(string) error) {
	fake.setConsensusTypeMutex.Lock()
	defer fake.setConsensusTypeMutex.Unlock()
	fake.SetConsensusTypeStub = stub
}

func (fake *FakeOrdering) SetConsensusTypeArgsForCall(i int) string {
	fake.setConsensusTypeMutex.RLock()
	defer fake.setConsensusTypeMutex.RUnlock()
	argsForCall := fake.setConsensusTypeArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeOrdering) SetConsensusTypeReturns(result1 error) {
	fake.setConsensusTypeMutex.Lock()
	defer fake.setConsensusTypeMutex.Unlock()
	fake.SetConsensusTypeStub = nil
	fake.setConsensusTypeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeOrdering) SetConsensusTypeReturnsOnCall(i int, result1 error) {
	fake.setConsensusTypeMutex.Lock()
	defer fake.setConsensusTypeMutex.Unlock()
	fake.SetConsensusTypeStub = nil
	if fake.setConsensusTypeReturnsOnCall == nil {
		fake.setConsensusTypeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.setConsensusTypeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeOrdering) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeOrdering) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ driver.Ordering = new(FakeOrdering)
