// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"sync"

	"github.com/hyperledger-labs/fabric-smart-client/platform/fabric/driver"
)

type FakeSignedProposal struct {
	ChaincodeNameStub        func() string
	chaincodeNameMutex       sync.RWMutex
	chaincodeNameArgsForCall []struct {
	}
	chaincodeNameReturns struct {
		result1 string
	}
	chaincodeNameReturnsOnCall map[int]struct {
		result1 string
	}
	ChaincodeVersionStub        func() string
	chaincodeVersionMutex       sync.RWMutex
	chaincodeVersionArgsForCall []struct {
	}
	chaincodeVersionReturns struct {
		result1 string
	}
	chaincodeVersionReturnsOnCall map[int]struct {
		result1 string
	}
	InternalStub        func() any
	internalMutex       sync.RWMutex
	internalArgsForCall []struct {
	}
	internalReturns struct {
		result1 any
	}
	internalReturnsOnCall map[int]struct {
		result1 any
	}
	ProposalBytesStub        func() []byte
	proposalBytesMutex       sync.RWMutex
	proposalBytesArgsForCall []struct {
	}
	proposalBytesReturns struct {
		result1 []byte
	}
	proposalBytesReturnsOnCall map[int]struct {
		result1 []byte
	}
	ProposalHashStub        func() []byte
	proposalHashMutex       sync.RWMutex
	proposalHashArgsForCall []struct {
	}
	proposalHashReturns struct {
		result1 []byte
	}
	proposalHashReturnsOnCall map[int]struct {
		result1 []byte
	}
	SignatureStub        func() []byte
	signatureMutex       sync.RWMutex
	signatureArgsForCall []struct {
	}
	signatureReturns struct {
		result1 []byte
	}
	signatureReturnsOnCall map[int]struct {
		result1 []byte
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSignedProposal) ChaincodeName() string {
	fake.chaincodeNameMutex.Lock()
	ret, specificReturn := fake.chaincodeNameReturnsOnCall[len(fake.chaincodeNameArgsForCall)]
	fake.chaincodeNameArgsForCall = append(fake.chaincodeNameArgsForCall, struct {
	}{})
	stub := fake.ChaincodeNameStub
	fakeReturns := fake.chaincodeNameReturns
	fake.recordInvocation("ChaincodeName", []interface{}{})
	fake.chaincodeNameMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSignedProposal) ChaincodeNameCallCount() int {
	fake.chaincodeNameMutex.RLock()
	defer fake.chaincodeNameMutex.RUnlock()
	return len(fake.chaincodeNameArgsForCall)
}

func (fake *FakeSignedProposal) ChaincodeNameCalls(stub func() string) {
	fake.chaincodeNameMutex.Lock()
	defer fake.chaincodeNameMutex.Unlock()
	fake.ChaincodeNameStub = stub
}

func (fake *FakeSignedProposal) ChaincodeNameReturns(result1 string) {
	fake.chaincodeNameMutex.Lock()
	defer fake.chaincodeNameMutex.Unlock()
	fake.ChaincodeNameStub = nil
	fake.chaincodeNameReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeSignedProposal) ChaincodeNameReturnsOnCall(i int, result1 string) {
	fake.chaincodeNameMutex.Lock()
	defer fake.chaincodeNameMutex.Unlock()
	fake.ChaincodeNameStub = nil
	if fake.chaincodeNameReturnsOnCall == nil {
		fake.chaincodeNameReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.chaincodeNameReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeSignedProposal) ChaincodeVersion() string {
	fake.chaincodeVersionMutex.Lock()
	ret, specificReturn := fake.chaincodeVersionReturnsOnCall[len(fake.chaincodeVersionArgsForCall)]
	fake.chaincodeVersionArgsForCall = append(fake.chaincodeVersionArgsForCall, struct {
	}{})
	stub := fake.ChaincodeVersionStub
	fakeReturns := fake.chaincodeVersionReturns
	fake.recordInvocation("ChaincodeVersion", []interface{}{})
	fake.chaincodeVersionMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSignedProposal) ChaincodeVersionCallCount() int {
	fake.chaincodeVersionMutex.RLock()
	defer fake.chaincodeVersionMutex.RUnlock()
	return len(fake.chaincodeVersionArgsForCall)
}

func (fake *FakeSignedProposal) ChaincodeVersionCalls(stub func() string) {
	fake.chaincodeVersionMutex.Lock()
	defer fake.chaincodeVersionMutex.Unlock()
	fake.ChaincodeVersionStub = stub
}

func (fake *FakeSignedProposal) ChaincodeVersionReturns(result1 string) {
	fake.chaincodeVersionMutex.Lock()
	defer fake.chaincodeVersionMutex.Unlock()
	fake.ChaincodeVersionStub = nil
	fake.chaincodeVersionReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeSignedProposal) ChaincodeVersionReturnsOnCall(i int, result1 string) {
	fake.chaincodeVersionMutex.Lock()
	defer fake.chaincodeVersionMutex.Unlock()
	fake.ChaincodeVersionStub = nil
	if fake.chaincodeVersionReturnsOnCall == nil {
		fake.chaincodeVersionReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.chaincodeVersionReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeSignedProposal) Internal() any {
	fake.internalMutex.Lock()
	ret, specificReturn := fake.internalReturnsOnCall[len(fake.internalArgsForCall)]
	fake.internalArgsForCall = append(fake.internalArgsForCall, struct {
	}{})
	stub := fake.InternalStub
	fakeReturns := fake.internalReturns
	fake.recordInvocation("Internal", []interface{}{})
	fake.internalMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSignedProposal) InternalCallCount() int {
	fake.internalMutex.RLock()
	defer fake.internalMutex.RUnlock()
	return len(fake.internalArgsForCall)
}

func (fake *FakeSignedProposal) InternalCalls(stub func() any) {
	fake.internalMutex.Lock()
	defer fake.internalMutex.Unlock()
	fake.InternalStub = stub
}

func (fake *FakeSignedProposal) InternalReturns(result1 any) {
	fake.internalMutex.Lock()
	defer fake.internalMutex.Unlock()
	fake.InternalStub = nil
	fake.internalReturns = struct {
		result1 any
	}{result1}
}

func (fake *FakeSignedProposal) InternalReturnsOnCall(i int, result1 any) {
	fake.internalMutex.Lock()
	defer fake.internalMutex.Unlock()
	fake.InternalStub = nil
	if fake.internalReturnsOnCall == nil {
		fake.internalReturnsOnCall = make(map[int]struct {
			result1 any
		})
	}
	fake.internalReturnsOnCall[i] = struct {
		result1 any
	}{result1}
}

func (fake *FakeSignedProposal) ProposalBytes() []byte {
	fake.proposalBytesMutex.Lock()
	ret, specificReturn := fake.proposalBytesReturnsOnCall[len(fake.proposalBytesArgsForCall)]
	fake.proposalBytesArgsForCall = append(fake.proposalBytesArgsForCall, struct {
	}{})
	stub := fake.ProposalBytesStub
	fakeReturns := fake.proposalBytesReturns
	fake.recordInvocation("ProposalBytes", []interface{}{})
	fake.proposalBytesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSignedProposal) ProposalBytesCallCount() int {
	fake.proposalBytesMutex.RLock()
	defer fake.proposalBytesMutex.RUnlock()
	return len(fake.proposalBytesArgsForCall)
}

func (fake *FakeSignedProposal) ProposalBytesCalls(stub func() []byte) {
	fake.proposalBytesMutex.Lock()
	defer fake.proposalBytesMutex.Unlock()
	fake.ProposalBytesStub = stub
}

func (fake *FakeSignedProposal) ProposalBytesReturns(result1 []byte) {
	fake.proposalBytesMutex.Lock()
	defer fake.proposalBytesMutex.Unlock()
	fake.ProposalBytesStub = nil
	fake.proposalBytesReturns = struct {
		result1 []byte
	}{result1}
}

func (fake *FakeSignedProposal) ProposalBytesReturnsOnCall(i int, result1 []byte) {
	fake.proposalBytesMutex.Lock()
	defer fake.proposalBytesMutex.Unlock()
	fake.ProposalBytesStub = nil
	if fake.proposalBytesReturnsOnCall == nil {
		fake.proposalBytesReturnsOnCall = make(map[int]struct {
			result1 []byte
		})
	}
	fake.proposalBytesReturnsOnCall[i] = struct {
		result1 []byte
	}{result1}
}

func (fake *FakeSignedProposal) ProposalHash() []byte {
	fake.proposalHashMutex.Lock()
	ret, specificReturn := fake.proposalHashReturnsOnCall[len(fake.proposalHashArgsForCall)]
	fake.proposalHashArgsForCall = append(fake.proposalHashArgsForCall, struct {
	}{})
	stub := fake.ProposalHashStub
	fakeReturns := fake.proposalHashReturns
	fake.recordInvocation("ProposalHash", []interface{}{})
	fake.proposalHashMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSignedProposal) ProposalHashCallCount() int {
	fake.proposalHashMutex.RLock()
	defer fake.proposalHashMutex.RUnlock()
	return len(fake.proposalHashArgsForCall)
}

func (fake *FakeSignedProposal) ProposalHashCalls(stub func() []byte) {
	fake.proposalHashMutex.Lock()
	defer fake.proposalHashMutex.Unlock()
	fake.ProposalHashStub = stub
}

func (fake *FakeSignedProposal) ProposalHashReturns(result1 []byte) {
	fake.proposalHashMutex.Lock()
	defer fake.proposalHashMutex.Unlock()
	fake.ProposalHashStub = nil
	fake.proposalHashReturns = struct {
		result1 []byte
	}{result1}
}

func (fake *FakeSignedProposal) ProposalHashReturnsOnCall(i int, result1 []byte) {
	fake.proposalHashMutex.Lock()
	defer fake.proposalHashMutex.Unlock()
	fake.ProposalHashStub = nil
	if fake.proposalHashReturnsOnCall == nil {
		fake.proposalHashReturnsOnCall = make(map[int]struct {
			result1 []byte
		})
	}
	fake.proposalHashReturnsOnCall[i] = struct {
		result1 []byte
	}{result1}
}

func (fake *FakeSignedProposal) Signature() []byte {
	fake.signatureMutex.Lock()
	ret, specificReturn := fake.signatureReturnsOnCall[len(fake.signatureArgsForCall)]
	fake.signatureArgsForCall = append(fake.signatureArgsForCall, struct {
	}{})
	stub := fake.SignatureStub
	fakeReturns := fake.signatureReturns
	fake.recordInvocation("Signature", []interface{}{})
	fake.signatureMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSignedProposal) SignatureCallCount() int {
	fake.signatureMutex.RLock()
	defer fake.signatureMutex.RUnlock()
	return len(fake.signatureArgsForCall)
}

func (fake *FakeSignedProposal) SignatureCalls(stub func() []byte) {
	fake.signatureMutex.Lock()
	defer fake.signatureMutex.Unlock()
	fake.SignatureStub = stub
}

func (fake *FakeSignedProposal) SignatureReturns(result1 []byte) {
	fake.signatureMutex.Lock()
	defer fake.signatureMutex.Unlock()
	fake.SignatureStub = nil
	fake.signatureReturns = struct {
		result1 []byte
	}{result1}
}

func (fake *FakeSignedProposal) SignatureReturnsOnCall(i int, result1 []byte) {
	fake.signatureMutex.Lock()
	defer fake.signatureMutex.Unlock()
	fake.SignatureStub = nil
	if fake.signatureReturnsOnCall == nil {
		fake.signatureReturnsOnCall = make(map[int]struct {
			result1 []byte
		})
	}
	fake.signatureReturnsOnCall[i] = struct {
		result1 []byte
	}{result1}
}

func (fake *FakeSignedProposal) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSignedProposal) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ driver.SignedProposal = new(FakeSignedProposal)
