// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"sync"

	"github.com/hyperledger-labs/fabric-smart-client/platform/fabric/driver"
	"github.com/hyperledger/fabric-protos-go-apiv2/common"
)

type RWSetPayloadHandler struct {
	LoadStub        func(*common.Payload, *common.ChannelHeader) (driver.RWSet, driver.ProcessTransaction, error)
	loadMutex       sync.RWMutex
	loadArgsForCall []struct {
		arg1 *common.Payload
		arg2 *common.ChannelHeader
	}
	loadReturns struct {
		result1 driver.RWSet
		result2 driver.ProcessTransaction
		result3 error
	}
	loadReturnsOnCall map[int]struct {
		result1 driver.RWSet
		result2 driver.ProcessTransaction
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *RWSetPayloadHandler) Load(arg1 *common.Payload, arg2 *common.ChannelHeader) (driver.RWSet, driver.ProcessTransaction, error) {
	fake.loadMutex.Lock()
	ret, specificReturn := fake.loadReturnsOnCall[len(fake.loadArgsForCall)]
	fake.loadArgsForCall = append(fake.loadArgsForCall, struct {
		arg1 *common.Payload
		arg2 *common.ChannelHeader
	}{arg1, arg2})
	stub := fake.LoadStub
	fakeReturns := fake.loadReturns
	fake.recordInvocation("Load", []interface{}{arg1, arg2})
	fake.loadMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *RWSetPayloadHandler) LoadCallCount() int {
	fake.loadMutex.RLock()
	defer fake.loadMutex.RUnlock()
	return len(fake.loadArgsForCall)
}

func (fake *RWSetPayloadHandler) LoadCalls(stub func(*common.Payload, *common.ChannelHeader) (driver.RWSet, driver.ProcessTransaction, error)) {
	fake.loadMutex.Lock()
	defer fake.loadMutex.Unlock()
	fake.LoadStub = stub
}

func (fake *RWSetPayloadHandler) LoadArgsForCall(i int) (*common.Payload, *common.ChannelHeader) {
	fake.loadMutex.RLock()
	defer fake.loadMutex.RUnlock()
	argsForCall := fake.loadArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *RWSetPayloadHandler) LoadReturns(result1 driver.RWSet, result2 driver.ProcessTransaction, result3 error) {
	fake.loadMutex.Lock()
	defer fake.loadMutex.Unlock()
	fake.LoadStub = nil
	fake.loadReturns = struct {
		result1 driver.RWSet
		result2 driver.ProcessTransaction
		result3 error
	}{result1, result2, result3}
}

func (fake *RWSetPayloadHandler) LoadReturnsOnCall(i int, result1 driver.RWSet, result2 driver.ProcessTransaction, result3 error) {
	fake.loadMutex.Lock()
	defer fake.loadMutex.Unlock()
	fake.LoadStub = nil
	if fake.loadReturnsOnCall == nil {
		fake.loadReturnsOnCall = make(map[int]struct {
			result1 driver.RWSet
			result2 driver.ProcessTransaction
			result3 error
		})
	}
	fake.loadReturnsOnCall[i] = struct {
		result1 driver.RWSet
		result2 driver.ProcessTransaction
		result3 error
	}{result1, result2, result3}
}

func (fake *RWSetPayloadHandler) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *RWSetPayloadHandler) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ driver.RWSetPayloadHandler = new(RWSetPayloadHandler)
