#!/usr/bin/env bash
#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# find-protos.sh — validate and manage protoc-generated files
#
# USAGE
#   find-protos.sh [--delete] [ROOT]
#
# DESCRIPTION
#   Scans ROOT (default: current directory) for every .proto file and checks
#   that corresponding generated files (.pb.go and _grpc.pb.go) exist and carry
#   the protoc generation marker:
#
#       // Code generated by protoc-gen-go. DO NOT EDIT.
#
#   A proto file passes (OK) when all generated files are protoc output.
#   A proto file fails (FAIL) when generated files are missing or modified.
#
# OPTIONS
#   --delete   After a passing check, delete the generated files. Use this before
#              running proto generation to do a clean regeneration:
#
#                  ./scripts/find-protos.sh --delete
#
#              Generated files that don't have the protoc marker are NOT deleted
#              so that no work is lost.
#
# EXIT STATUS
#   0   All proto files passed (or no proto files found).
#   1   At least one proto file has missing or non-protoc generated files.
#
# BACKGROUND
#   In FSC, .pb.go and _grpc.pb.go files are owned exclusively by protoc. They
#   must never contain handwritten code. This script helps maintain that invariant.
set -euo pipefail

# Parse command-line arguments
DELETE=false
ROOT="."
for arg in "$@"; do
    case "$arg" in
        --delete) DELETE=true ;;
        *) ROOT="$arg" ;;
    esac
done

# Markers that identify protoc-generated files
PROTOC_MARKER="// Code generated by protoc-gen-go. DO NOT EDIT."
PROTOC_GRPC_MARKER="// Code generated by protoc-gen-go-grpc. DO NOT EDIT."

exit_code=0

# Process each .proto file found in the directory tree
while IFS= read -r proto_file; do
    # Skip testdata directories to match compile_proto.sh behavior
    # testdata dirs contain test fixtures that are not part of the build
    if [[ "$proto_file" == *"/testdata/"* ]]; then
        continue
    fi
    
    # Determine expected generated file names
    dir=$(dirname "$proto_file")
    base=$(basename "$proto_file" .proto)
    
    pb_go="${dir}/${base}.pb.go"           # Message definitions
    grpc_pb_go="${dir}/${base}_grpc.pb.go" # gRPC service definitions (optional)
    
    violations=()      # Files that exist but lack the protoc marker
    generated_files=() # Valid protoc-generated files
    
    # Check .pb.go file (always generated for any .proto file)
    if [[ -f "$pb_go" ]]; then
        generated_files+=("$pb_go")
        # Verify it has the protoc marker - if not, it may have been hand-edited
        if ! grep -qF "$PROTOC_MARKER" "$pb_go"; then
            violations+=("$pb_go")
        fi
    fi
    
    # Check _grpc.pb.go file (only generated if proto defines services)
    if [[ -f "$grpc_pb_go" ]]; then
        generated_files+=("$grpc_pb_go")
        # Verify it has the protoc-grpc marker
        if ! grep -qF "$PROTOC_GRPC_MARKER" "$grpc_pb_go"; then
            violations+=("$grpc_pb_go")
        fi
    fi
    
    # Report results for this proto file
    if [[ ${#violations[@]} -gt 0 ]]; then
        # FAIL: One or more generated files are missing markers or hand-edited
        echo "FAIL $proto_file"
        for v in "${violations[@]}"; do
            echo "     not protoc-generated: $v"
        done
        exit_code=1
    elif [[ ${#generated_files[@]} -gt 0 ]]; then
        # OK: All generated files have proper markers
        echo "OK   $proto_file"
        # If --delete flag is set, remove the validated generated files
        if [[ "$DELETE" == true ]]; then
            for gf in "${generated_files[@]}"; do
                rm -f "$gf"
                echo "     deleted: $gf"
            done
        fi
    else
        # WARN: Proto file exists but no generated files found
        echo "WARN $proto_file (no generated files found)"
    fi
done < <(find "$ROOT" -type f -name "*.proto" | sort)

exit "$exit_code"