// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"sync"

	"github.com/hyperledger-labs/fabric-smart-client/platform/fabric/core/generic/config"
	"github.com/hyperledger-labs/fabric-smart-client/platform/fabric/core/generic/msp/driver"
)

type Config struct {
	DefaultMSPStub        func() string
	defaultMSPMutex       sync.RWMutex
	defaultMSPArgsForCall []struct {
	}
	defaultMSPReturns struct {
		result1 string
	}
	defaultMSPReturnsOnCall map[int]struct {
		result1 string
	}
	MSPsStub        func() ([]config.MSP, error)
	mSPsMutex       sync.RWMutex
	mSPsArgsForCall []struct {
	}
	mSPsReturns struct {
		result1 []config.MSP
		result2 error
	}
	mSPsReturnsOnCall map[int]struct {
		result1 []config.MSP
		result2 error
	}
	NetworkNameStub        func() string
	networkNameMutex       sync.RWMutex
	networkNameArgsForCall []struct {
	}
	networkNameReturns struct {
		result1 string
	}
	networkNameReturnsOnCall map[int]struct {
		result1 string
	}
	TranslatePathStub        func(string) string
	translatePathMutex       sync.RWMutex
	translatePathArgsForCall []struct {
		arg1 string
	}
	translatePathReturns struct {
		result1 string
	}
	translatePathReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Config) DefaultMSP() string {
	fake.defaultMSPMutex.Lock()
	ret, specificReturn := fake.defaultMSPReturnsOnCall[len(fake.defaultMSPArgsForCall)]
	fake.defaultMSPArgsForCall = append(fake.defaultMSPArgsForCall, struct {
	}{})
	stub := fake.DefaultMSPStub
	fakeReturns := fake.defaultMSPReturns
	fake.recordInvocation("DefaultMSP", []interface{}{})
	fake.defaultMSPMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Config) DefaultMSPCallCount() int {
	fake.defaultMSPMutex.RLock()
	defer fake.defaultMSPMutex.RUnlock()
	return len(fake.defaultMSPArgsForCall)
}

func (fake *Config) DefaultMSPCalls(stub func() string) {
	fake.defaultMSPMutex.Lock()
	defer fake.defaultMSPMutex.Unlock()
	fake.DefaultMSPStub = stub
}

func (fake *Config) DefaultMSPReturns(result1 string) {
	fake.defaultMSPMutex.Lock()
	defer fake.defaultMSPMutex.Unlock()
	fake.DefaultMSPStub = nil
	fake.defaultMSPReturns = struct {
		result1 string
	}{result1}
}

func (fake *Config) DefaultMSPReturnsOnCall(i int, result1 string) {
	fake.defaultMSPMutex.Lock()
	defer fake.defaultMSPMutex.Unlock()
	fake.DefaultMSPStub = nil
	if fake.defaultMSPReturnsOnCall == nil {
		fake.defaultMSPReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.defaultMSPReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *Config) MSPs() ([]config.MSP, error) {
	fake.mSPsMutex.Lock()
	ret, specificReturn := fake.mSPsReturnsOnCall[len(fake.mSPsArgsForCall)]
	fake.mSPsArgsForCall = append(fake.mSPsArgsForCall, struct {
	}{})
	stub := fake.MSPsStub
	fakeReturns := fake.mSPsReturns
	fake.recordInvocation("MSPs", []interface{}{})
	fake.mSPsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Config) MSPsCallCount() int {
	fake.mSPsMutex.RLock()
	defer fake.mSPsMutex.RUnlock()
	return len(fake.mSPsArgsForCall)
}

func (fake *Config) MSPsCalls(stub func() ([]config.MSP, error)) {
	fake.mSPsMutex.Lock()
	defer fake.mSPsMutex.Unlock()
	fake.MSPsStub = stub
}

func (fake *Config) MSPsReturns(result1 []config.MSP, result2 error) {
	fake.mSPsMutex.Lock()
	defer fake.mSPsMutex.Unlock()
	fake.MSPsStub = nil
	fake.mSPsReturns = struct {
		result1 []config.MSP
		result2 error
	}{result1, result2}
}

func (fake *Config) MSPsReturnsOnCall(i int, result1 []config.MSP, result2 error) {
	fake.mSPsMutex.Lock()
	defer fake.mSPsMutex.Unlock()
	fake.MSPsStub = nil
	if fake.mSPsReturnsOnCall == nil {
		fake.mSPsReturnsOnCall = make(map[int]struct {
			result1 []config.MSP
			result2 error
		})
	}
	fake.mSPsReturnsOnCall[i] = struct {
		result1 []config.MSP
		result2 error
	}{result1, result2}
}

func (fake *Config) NetworkName() string {
	fake.networkNameMutex.Lock()
	ret, specificReturn := fake.networkNameReturnsOnCall[len(fake.networkNameArgsForCall)]
	fake.networkNameArgsForCall = append(fake.networkNameArgsForCall, struct {
	}{})
	stub := fake.NetworkNameStub
	fakeReturns := fake.networkNameReturns
	fake.recordInvocation("NetworkName", []interface{}{})
	fake.networkNameMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Config) NetworkNameCallCount() int {
	fake.networkNameMutex.RLock()
	defer fake.networkNameMutex.RUnlock()
	return len(fake.networkNameArgsForCall)
}

func (fake *Config) NetworkNameCalls(stub func() string) {
	fake.networkNameMutex.Lock()
	defer fake.networkNameMutex.Unlock()
	fake.NetworkNameStub = stub
}

func (fake *Config) NetworkNameReturns(result1 string) {
	fake.networkNameMutex.Lock()
	defer fake.networkNameMutex.Unlock()
	fake.NetworkNameStub = nil
	fake.networkNameReturns = struct {
		result1 string
	}{result1}
}

func (fake *Config) NetworkNameReturnsOnCall(i int, result1 string) {
	fake.networkNameMutex.Lock()
	defer fake.networkNameMutex.Unlock()
	fake.NetworkNameStub = nil
	if fake.networkNameReturnsOnCall == nil {
		fake.networkNameReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.networkNameReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *Config) TranslatePath(arg1 string) string {
	fake.translatePathMutex.Lock()
	ret, specificReturn := fake.translatePathReturnsOnCall[len(fake.translatePathArgsForCall)]
	fake.translatePathArgsForCall = append(fake.translatePathArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.TranslatePathStub
	fakeReturns := fake.translatePathReturns
	fake.recordInvocation("TranslatePath", []interface{}{arg1})
	fake.translatePathMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Config) TranslatePathCallCount() int {
	fake.translatePathMutex.RLock()
	defer fake.translatePathMutex.RUnlock()
	return len(fake.translatePathArgsForCall)
}

func (fake *Config) TranslatePathCalls(stub func(string) string) {
	fake.translatePathMutex.Lock()
	defer fake.translatePathMutex.Unlock()
	fake.TranslatePathStub = stub
}

func (fake *Config) TranslatePathArgsForCall(i int) string {
	fake.translatePathMutex.RLock()
	defer fake.translatePathMutex.RUnlock()
	argsForCall := fake.translatePathArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Config) TranslatePathReturns(result1 string) {
	fake.translatePathMutex.Lock()
	defer fake.translatePathMutex.Unlock()
	fake.TranslatePathStub = nil
	fake.translatePathReturns = struct {
		result1 string
	}{result1}
}

func (fake *Config) TranslatePathReturnsOnCall(i int, result1 string) {
	fake.translatePathMutex.Lock()
	defer fake.translatePathMutex.Unlock()
	fake.TranslatePathStub = nil
	if fake.translatePathReturnsOnCall == nil {
		fake.translatePathReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.translatePathReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *Config) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Config) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ driver.Config = new(Config)
