@startuml
skinparam componentStyle rectangle

title View Platform Architecture

package "Client Side" {
  [view.Client]
}

package "View SDK" {
  [view.Client] --> [grpc.GRPCServer] : GRPC
  [grpc.GRPCServer] --> [server.view.Server] : Forward call

  [server.view.Server] <--> [sig.Service] : Sig Request
  [server.view.Server] --> [view.Manager] : Initiate a View
  [server.view.Server] --> [id.Provider] : Access Control
  [server.view.Server] --> [trace.TracerProvider] : Report

  [view.Manager] <--> [view.Registry] : Lookup View
  [view.Manager] --> [comm.Service] : Message
  [view.Manager] --> [endpoint.Service] : Lookup Endpoint
  [view.Manager] <--> [sig.Service] : Identity Request
  [view.Manager] --> [trace.TracerProvider] : Report

  [comm.Service] --> [view.Manager] : Message

  [endpoint.Service] <--> [comm.Service] : Lookup Endpoint
  [endpoint.Service] <--> [Database]: DB Ops
  [endpoint.Service] <--> [config.Service]: Config Ops
  [endpoint.Service] --> [id.Provider] : ID Lookup

  [sig.Service] <--> [Database] : Dp Ops
}

node "Remote View SDK" {
  [Remote comm.Service]
}

[comm.Service] --> [Remote comm.Service] : Message
[Remote comm.Service] --> [comm.Service] : Message

@enduml
