// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"context"
	"sync"

	"github.com/hyperledger-labs/fabric-smart-client/platform/view/services/view"
	viewa "github.com/hyperledger-labs/fabric-smart-client/platform/view/view"
	"go.opentelemetry.io/otel/trace"
)

type MutableParentContext struct {
	CleanupStub        func()
	cleanupMutex       sync.RWMutex
	cleanupArgsForCall []struct {
	}
	ContextStub        func() context.Context
	contextMutex       sync.RWMutex
	contextArgsForCall []struct {
	}
	contextReturns struct {
		result1 context.Context
	}
	contextReturnsOnCall map[int]struct {
		result1 context.Context
	}
	DisposeStub        func()
	disposeMutex       sync.RWMutex
	disposeArgsForCall []struct {
	}
	GetServiceStub        func(any) (any, error)
	getServiceMutex       sync.RWMutex
	getServiceArgsForCall []struct {
		arg1 any
	}
	getServiceReturns struct {
		result1 any
		result2 error
	}
	getServiceReturnsOnCall map[int]struct {
		result1 any
		result2 error
	}
	GetSessionStub        func(viewa.View, viewa.Identity, ...viewa.View) (viewa.Session, error)
	getSessionMutex       sync.RWMutex
	getSessionArgsForCall []struct {
		arg1 viewa.View
		arg2 viewa.Identity
		arg3 []viewa.View
	}
	getSessionReturns struct {
		result1 viewa.Session
		result2 error
	}
	getSessionReturnsOnCall map[int]struct {
		result1 viewa.Session
		result2 error
	}
	GetSessionByIDStub        func(string, viewa.Identity) (viewa.Session, error)
	getSessionByIDMutex       sync.RWMutex
	getSessionByIDArgsForCall []struct {
		arg1 string
		arg2 viewa.Identity
	}
	getSessionByIDReturns struct {
		result1 viewa.Session
		result2 error
	}
	getSessionByIDReturnsOnCall map[int]struct {
		result1 viewa.Session
		result2 error
	}
	IDStub        func() string
	iDMutex       sync.RWMutex
	iDArgsForCall []struct {
	}
	iDReturns struct {
		result1 string
	}
	iDReturnsOnCall map[int]struct {
		result1 string
	}
	InitiatorStub        func() viewa.View
	initiatorMutex       sync.RWMutex
	initiatorArgsForCall []struct {
	}
	initiatorReturns struct {
		result1 viewa.View
	}
	initiatorReturnsOnCall map[int]struct {
		result1 viewa.View
	}
	IsMeStub        func(viewa.Identity) bool
	isMeMutex       sync.RWMutex
	isMeArgsForCall []struct {
		arg1 viewa.Identity
	}
	isMeReturns struct {
		result1 bool
	}
	isMeReturnsOnCall map[int]struct {
		result1 bool
	}
	MeStub        func() viewa.Identity
	meMutex       sync.RWMutex
	meArgsForCall []struct {
	}
	meReturns struct {
		result1 viewa.Identity
	}
	meReturnsOnCall map[int]struct {
		result1 viewa.Identity
	}
	OnErrorStub        func(func())
	onErrorMutex       sync.RWMutex
	onErrorArgsForCall []struct {
		arg1 func()
	}
	PutServiceStub        func(any) error
	putServiceMutex       sync.RWMutex
	putServiceArgsForCall []struct {
		arg1 any
	}
	putServiceReturns struct {
		result1 error
	}
	putServiceReturnsOnCall map[int]struct {
		result1 error
	}
	PutSessionStub        func(viewa.View, viewa.Identity, viewa.Session) error
	putSessionMutex       sync.RWMutex
	putSessionArgsForCall []struct {
		arg1 viewa.View
		arg2 viewa.Identity
		arg3 viewa.Session
	}
	putSessionReturns struct {
		result1 error
	}
	putSessionReturnsOnCall map[int]struct {
		result1 error
	}
	PutSessionByIDStub        func(string, viewa.Identity, viewa.Session) error
	putSessionByIDMutex       sync.RWMutex
	putSessionByIDArgsForCall []struct {
		arg1 string
		arg2 viewa.Identity
		arg3 viewa.Session
	}
	putSessionByIDReturns struct {
		result1 error
	}
	putSessionByIDReturnsOnCall map[int]struct {
		result1 error
	}
	ResetSessionsStub        func() error
	resetSessionsMutex       sync.RWMutex
	resetSessionsArgsForCall []struct {
	}
	resetSessionsReturns struct {
		result1 error
	}
	resetSessionsReturnsOnCall map[int]struct {
		result1 error
	}
	RunViewStub        func(viewa.View, ...viewa.RunViewOption) (any, error)
	runViewMutex       sync.RWMutex
	runViewArgsForCall []struct {
		arg1 viewa.View
		arg2 []viewa.RunViewOption
	}
	runViewReturns struct {
		result1 any
		result2 error
	}
	runViewReturnsOnCall map[int]struct {
		result1 any
		result2 error
	}
	SessionStub        func() viewa.Session
	sessionMutex       sync.RWMutex
	sessionArgsForCall []struct {
	}
	sessionReturns struct {
		result1 viewa.Session
	}
	sessionReturnsOnCall map[int]struct {
		result1 viewa.Session
	}
	StartSpanFromStub        func(context.Context, string, ...trace.SpanStartOption) (context.Context, trace.Span)
	startSpanFromMutex       sync.RWMutex
	startSpanFromArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 []trace.SpanStartOption
	}
	startSpanFromReturns struct {
		result1 context.Context
		result2 trace.Span
	}
	startSpanFromReturnsOnCall map[int]struct {
		result1 context.Context
		result2 trace.Span
	}
	invocations      map[string][][]any
	invocationsMutex sync.RWMutex
}

func (fake *MutableParentContext) Cleanup() {
	fake.cleanupMutex.Lock()
	fake.cleanupArgsForCall = append(fake.cleanupArgsForCall, struct {
	}{})
	stub := fake.CleanupStub
	fake.recordInvocation("Cleanup", []any{})
	fake.cleanupMutex.Unlock()
	if stub != nil {
		fake.CleanupStub()
	}
}

func (fake *MutableParentContext) CleanupCallCount() int {
	fake.cleanupMutex.RLock()
	defer fake.cleanupMutex.RUnlock()
	return len(fake.cleanupArgsForCall)
}

func (fake *MutableParentContext) CleanupCalls(stub func()) {
	fake.cleanupMutex.Lock()
	defer fake.cleanupMutex.Unlock()
	fake.CleanupStub = stub
}

func (fake *MutableParentContext) Context() context.Context {
	fake.contextMutex.Lock()
	ret, specificReturn := fake.contextReturnsOnCall[len(fake.contextArgsForCall)]
	fake.contextArgsForCall = append(fake.contextArgsForCall, struct {
	}{})
	stub := fake.ContextStub
	fakeReturns := fake.contextReturns
	fake.recordInvocation("Ctx", []any{})
	fake.contextMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *MutableParentContext) ContextCallCount() int {
	fake.contextMutex.RLock()
	defer fake.contextMutex.RUnlock()
	return len(fake.contextArgsForCall)
}

func (fake *MutableParentContext) ContextCalls(stub func() context.Context) {
	fake.contextMutex.Lock()
	defer fake.contextMutex.Unlock()
	fake.ContextStub = stub
}

func (fake *MutableParentContext) ContextReturns(result1 context.Context) {
	fake.contextMutex.Lock()
	defer fake.contextMutex.Unlock()
	fake.ContextStub = nil
	fake.contextReturns = struct {
		result1 context.Context
	}{result1}
}

func (fake *MutableParentContext) ContextReturnsOnCall(i int, result1 context.Context) {
	fake.contextMutex.Lock()
	defer fake.contextMutex.Unlock()
	fake.ContextStub = nil
	if fake.contextReturnsOnCall == nil {
		fake.contextReturnsOnCall = make(map[int]struct {
			result1 context.Context
		})
	}
	fake.contextReturnsOnCall[i] = struct {
		result1 context.Context
	}{result1}
}

func (fake *MutableParentContext) Dispose() {
	fake.disposeMutex.Lock()
	fake.disposeArgsForCall = append(fake.disposeArgsForCall, struct {
	}{})
	stub := fake.DisposeStub
	fake.recordInvocation("Dispose", []any{})
	fake.disposeMutex.Unlock()
	if stub != nil {
		fake.DisposeStub()
	}
}

func (fake *MutableParentContext) DisposeCallCount() int {
	fake.disposeMutex.RLock()
	defer fake.disposeMutex.RUnlock()
	return len(fake.disposeArgsForCall)
}

func (fake *MutableParentContext) DisposeCalls(stub func()) {
	fake.disposeMutex.Lock()
	defer fake.disposeMutex.Unlock()
	fake.DisposeStub = stub
}

func (fake *MutableParentContext) GetService(arg1 any) (any, error) {
	fake.getServiceMutex.Lock()
	ret, specificReturn := fake.getServiceReturnsOnCall[len(fake.getServiceArgsForCall)]
	fake.getServiceArgsForCall = append(fake.getServiceArgsForCall, struct {
		arg1 any
	}{arg1})
	stub := fake.GetServiceStub
	fakeReturns := fake.getServiceReturns
	fake.recordInvocation("GetService", []any{arg1})
	fake.getServiceMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *MutableParentContext) GetServiceCallCount() int {
	fake.getServiceMutex.RLock()
	defer fake.getServiceMutex.RUnlock()
	return len(fake.getServiceArgsForCall)
}

func (fake *MutableParentContext) GetServiceCalls(stub func(any) (any, error)) {
	fake.getServiceMutex.Lock()
	defer fake.getServiceMutex.Unlock()
	fake.GetServiceStub = stub
}

func (fake *MutableParentContext) GetServiceArgsForCall(i int) any {
	fake.getServiceMutex.RLock()
	defer fake.getServiceMutex.RUnlock()
	argsForCall := fake.getServiceArgsForCall[i]
	return argsForCall.arg1
}

func (fake *MutableParentContext) GetServiceReturns(result1 any, result2 error) {
	fake.getServiceMutex.Lock()
	defer fake.getServiceMutex.Unlock()
	fake.GetServiceStub = nil
	fake.getServiceReturns = struct {
		result1 any
		result2 error
	}{result1, result2}
}

func (fake *MutableParentContext) GetServiceReturnsOnCall(i int, result1 any, result2 error) {
	fake.getServiceMutex.Lock()
	defer fake.getServiceMutex.Unlock()
	fake.GetServiceStub = nil
	if fake.getServiceReturnsOnCall == nil {
		fake.getServiceReturnsOnCall = make(map[int]struct {
			result1 any
			result2 error
		})
	}
	fake.getServiceReturnsOnCall[i] = struct {
		result1 any
		result2 error
	}{result1, result2}
}

func (fake *MutableParentContext) GetSession(arg1 viewa.View, arg2 viewa.Identity, arg3 ...viewa.View) (viewa.Session, error) {
	fake.getSessionMutex.Lock()
	ret, specificReturn := fake.getSessionReturnsOnCall[len(fake.getSessionArgsForCall)]
	fake.getSessionArgsForCall = append(fake.getSessionArgsForCall, struct {
		arg1 viewa.View
		arg2 viewa.Identity
		arg3 []viewa.View
	}{arg1, arg2, arg3})
	stub := fake.GetSessionStub
	fakeReturns := fake.getSessionReturns
	fake.recordInvocation("GetSession", []any{arg1, arg2, arg3})
	fake.getSessionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *MutableParentContext) GetSessionCallCount() int {
	fake.getSessionMutex.RLock()
	defer fake.getSessionMutex.RUnlock()
	return len(fake.getSessionArgsForCall)
}

func (fake *MutableParentContext) GetSessionCalls(stub func(viewa.View, viewa.Identity, ...viewa.View) (viewa.Session, error)) {
	fake.getSessionMutex.Lock()
	defer fake.getSessionMutex.Unlock()
	fake.GetSessionStub = stub
}

func (fake *MutableParentContext) GetSessionArgsForCall(i int) (viewa.View, viewa.Identity, []viewa.View) {
	fake.getSessionMutex.RLock()
	defer fake.getSessionMutex.RUnlock()
	argsForCall := fake.getSessionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *MutableParentContext) GetSessionReturns(result1 viewa.Session, result2 error) {
	fake.getSessionMutex.Lock()
	defer fake.getSessionMutex.Unlock()
	fake.GetSessionStub = nil
	fake.getSessionReturns = struct {
		result1 viewa.Session
		result2 error
	}{result1, result2}
}

func (fake *MutableParentContext) GetSessionReturnsOnCall(i int, result1 viewa.Session, result2 error) {
	fake.getSessionMutex.Lock()
	defer fake.getSessionMutex.Unlock()
	fake.GetSessionStub = nil
	if fake.getSessionReturnsOnCall == nil {
		fake.getSessionReturnsOnCall = make(map[int]struct {
			result1 viewa.Session
			result2 error
		})
	}
	fake.getSessionReturnsOnCall[i] = struct {
		result1 viewa.Session
		result2 error
	}{result1, result2}
}

func (fake *MutableParentContext) GetSessionByID(arg1 string, arg2 viewa.Identity) (viewa.Session, error) {
	fake.getSessionByIDMutex.Lock()
	ret, specificReturn := fake.getSessionByIDReturnsOnCall[len(fake.getSessionByIDArgsForCall)]
	fake.getSessionByIDArgsForCall = append(fake.getSessionByIDArgsForCall, struct {
		arg1 string
		arg2 viewa.Identity
	}{arg1, arg2})
	stub := fake.GetSessionByIDStub
	fakeReturns := fake.getSessionByIDReturns
	fake.recordInvocation("GetSessionByID", []any{arg1, arg2})
	fake.getSessionByIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *MutableParentContext) GetSessionByIDCallCount() int {
	fake.getSessionByIDMutex.RLock()
	defer fake.getSessionByIDMutex.RUnlock()
	return len(fake.getSessionByIDArgsForCall)
}

func (fake *MutableParentContext) GetSessionByIDCalls(stub func(string, viewa.Identity) (viewa.Session, error)) {
	fake.getSessionByIDMutex.Lock()
	defer fake.getSessionByIDMutex.Unlock()
	fake.GetSessionByIDStub = stub
}

func (fake *MutableParentContext) GetSessionByIDArgsForCall(i int) (string, viewa.Identity) {
	fake.getSessionByIDMutex.RLock()
	defer fake.getSessionByIDMutex.RUnlock()
	argsForCall := fake.getSessionByIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *MutableParentContext) GetSessionByIDReturns(result1 viewa.Session, result2 error) {
	fake.getSessionByIDMutex.Lock()
	defer fake.getSessionByIDMutex.Unlock()
	fake.GetSessionByIDStub = nil
	fake.getSessionByIDReturns = struct {
		result1 viewa.Session
		result2 error
	}{result1, result2}
}

func (fake *MutableParentContext) GetSessionByIDReturnsOnCall(i int, result1 viewa.Session, result2 error) {
	fake.getSessionByIDMutex.Lock()
	defer fake.getSessionByIDMutex.Unlock()
	fake.GetSessionByIDStub = nil
	if fake.getSessionByIDReturnsOnCall == nil {
		fake.getSessionByIDReturnsOnCall = make(map[int]struct {
			result1 viewa.Session
			result2 error
		})
	}
	fake.getSessionByIDReturnsOnCall[i] = struct {
		result1 viewa.Session
		result2 error
	}{result1, result2}
}

func (fake *MutableParentContext) ID() string {
	fake.iDMutex.Lock()
	ret, specificReturn := fake.iDReturnsOnCall[len(fake.iDArgsForCall)]
	fake.iDArgsForCall = append(fake.iDArgsForCall, struct {
	}{})
	stub := fake.IDStub
	fakeReturns := fake.iDReturns
	fake.recordInvocation("ID", []any{})
	fake.iDMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *MutableParentContext) IDCallCount() int {
	fake.iDMutex.RLock()
	defer fake.iDMutex.RUnlock()
	return len(fake.iDArgsForCall)
}

func (fake *MutableParentContext) IDCalls(stub func() string) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = stub
}

func (fake *MutableParentContext) IDReturns(result1 string) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = nil
	fake.iDReturns = struct {
		result1 string
	}{result1}
}

func (fake *MutableParentContext) IDReturnsOnCall(i int, result1 string) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = nil
	if fake.iDReturnsOnCall == nil {
		fake.iDReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.iDReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *MutableParentContext) Initiator() viewa.View {
	fake.initiatorMutex.Lock()
	ret, specificReturn := fake.initiatorReturnsOnCall[len(fake.initiatorArgsForCall)]
	fake.initiatorArgsForCall = append(fake.initiatorArgsForCall, struct {
	}{})
	stub := fake.InitiatorStub
	fakeReturns := fake.initiatorReturns
	fake.recordInvocation("Initiator", []any{})
	fake.initiatorMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *MutableParentContext) InitiatorCallCount() int {
	fake.initiatorMutex.RLock()
	defer fake.initiatorMutex.RUnlock()
	return len(fake.initiatorArgsForCall)
}

func (fake *MutableParentContext) InitiatorCalls(stub func() viewa.View) {
	fake.initiatorMutex.Lock()
	defer fake.initiatorMutex.Unlock()
	fake.InitiatorStub = stub
}

func (fake *MutableParentContext) InitiatorReturns(result1 viewa.View) {
	fake.initiatorMutex.Lock()
	defer fake.initiatorMutex.Unlock()
	fake.InitiatorStub = nil
	fake.initiatorReturns = struct {
		result1 viewa.View
	}{result1}
}

func (fake *MutableParentContext) InitiatorReturnsOnCall(i int, result1 viewa.View) {
	fake.initiatorMutex.Lock()
	defer fake.initiatorMutex.Unlock()
	fake.InitiatorStub = nil
	if fake.initiatorReturnsOnCall == nil {
		fake.initiatorReturnsOnCall = make(map[int]struct {
			result1 viewa.View
		})
	}
	fake.initiatorReturnsOnCall[i] = struct {
		result1 viewa.View
	}{result1}
}

func (fake *MutableParentContext) IsMe(arg1 viewa.Identity) bool {
	fake.isMeMutex.Lock()
	ret, specificReturn := fake.isMeReturnsOnCall[len(fake.isMeArgsForCall)]
	fake.isMeArgsForCall = append(fake.isMeArgsForCall, struct {
		arg1 viewa.Identity
	}{arg1})
	stub := fake.IsMeStub
	fakeReturns := fake.isMeReturns
	fake.recordInvocation("IsMe", []any{arg1})
	fake.isMeMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *MutableParentContext) IsMeCallCount() int {
	fake.isMeMutex.RLock()
	defer fake.isMeMutex.RUnlock()
	return len(fake.isMeArgsForCall)
}

func (fake *MutableParentContext) IsMeCalls(stub func(viewa.Identity) bool) {
	fake.isMeMutex.Lock()
	defer fake.isMeMutex.Unlock()
	fake.IsMeStub = stub
}

func (fake *MutableParentContext) IsMeArgsForCall(i int) viewa.Identity {
	fake.isMeMutex.RLock()
	defer fake.isMeMutex.RUnlock()
	argsForCall := fake.isMeArgsForCall[i]
	return argsForCall.arg1
}

func (fake *MutableParentContext) IsMeReturns(result1 bool) {
	fake.isMeMutex.Lock()
	defer fake.isMeMutex.Unlock()
	fake.IsMeStub = nil
	fake.isMeReturns = struct {
		result1 bool
	}{result1}
}

func (fake *MutableParentContext) IsMeReturnsOnCall(i int, result1 bool) {
	fake.isMeMutex.Lock()
	defer fake.isMeMutex.Unlock()
	fake.IsMeStub = nil
	if fake.isMeReturnsOnCall == nil {
		fake.isMeReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.isMeReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *MutableParentContext) Me() viewa.Identity {
	fake.meMutex.Lock()
	ret, specificReturn := fake.meReturnsOnCall[len(fake.meArgsForCall)]
	fake.meArgsForCall = append(fake.meArgsForCall, struct {
	}{})
	stub := fake.MeStub
	fakeReturns := fake.meReturns
	fake.recordInvocation("Me", []any{})
	fake.meMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *MutableParentContext) MeCallCount() int {
	fake.meMutex.RLock()
	defer fake.meMutex.RUnlock()
	return len(fake.meArgsForCall)
}

func (fake *MutableParentContext) MeCalls(stub func() viewa.Identity) {
	fake.meMutex.Lock()
	defer fake.meMutex.Unlock()
	fake.MeStub = stub
}

func (fake *MutableParentContext) MeReturns(result1 viewa.Identity) {
	fake.meMutex.Lock()
	defer fake.meMutex.Unlock()
	fake.MeStub = nil
	fake.meReturns = struct {
		result1 viewa.Identity
	}{result1}
}

func (fake *MutableParentContext) MeReturnsOnCall(i int, result1 viewa.Identity) {
	fake.meMutex.Lock()
	defer fake.meMutex.Unlock()
	fake.MeStub = nil
	if fake.meReturnsOnCall == nil {
		fake.meReturnsOnCall = make(map[int]struct {
			result1 viewa.Identity
		})
	}
	fake.meReturnsOnCall[i] = struct {
		result1 viewa.Identity
	}{result1}
}

func (fake *MutableParentContext) OnError(arg1 func()) {
	fake.onErrorMutex.Lock()
	fake.onErrorArgsForCall = append(fake.onErrorArgsForCall, struct {
		arg1 func()
	}{arg1})
	stub := fake.OnErrorStub
	fake.recordInvocation("OnError", []any{arg1})
	fake.onErrorMutex.Unlock()
	if stub != nil {
		fake.OnErrorStub(arg1)
	}
}

func (fake *MutableParentContext) OnErrorCallCount() int {
	fake.onErrorMutex.RLock()
	defer fake.onErrorMutex.RUnlock()
	return len(fake.onErrorArgsForCall)
}

func (fake *MutableParentContext) OnErrorCalls(stub func(func())) {
	fake.onErrorMutex.Lock()
	defer fake.onErrorMutex.Unlock()
	fake.OnErrorStub = stub
}

func (fake *MutableParentContext) OnErrorArgsForCall(i int) func() {
	fake.onErrorMutex.RLock()
	defer fake.onErrorMutex.RUnlock()
	argsForCall := fake.onErrorArgsForCall[i]
	return argsForCall.arg1
}

func (fake *MutableParentContext) PutService(arg1 any) error {
	fake.putServiceMutex.Lock()
	ret, specificReturn := fake.putServiceReturnsOnCall[len(fake.putServiceArgsForCall)]
	fake.putServiceArgsForCall = append(fake.putServiceArgsForCall, struct {
		arg1 any
	}{arg1})
	stub := fake.PutServiceStub
	fakeReturns := fake.putServiceReturns
	fake.recordInvocation("PutService", []any{arg1})
	fake.putServiceMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *MutableParentContext) PutServiceCallCount() int {
	fake.putServiceMutex.RLock()
	defer fake.putServiceMutex.RUnlock()
	return len(fake.putServiceArgsForCall)
}

func (fake *MutableParentContext) PutServiceCalls(stub func(any) error) {
	fake.putServiceMutex.Lock()
	defer fake.putServiceMutex.Unlock()
	fake.PutServiceStub = stub
}

func (fake *MutableParentContext) PutServiceArgsForCall(i int) any {
	fake.putServiceMutex.RLock()
	defer fake.putServiceMutex.RUnlock()
	argsForCall := fake.putServiceArgsForCall[i]
	return argsForCall.arg1
}

func (fake *MutableParentContext) PutServiceReturns(result1 error) {
	fake.putServiceMutex.Lock()
	defer fake.putServiceMutex.Unlock()
	fake.PutServiceStub = nil
	fake.putServiceReturns = struct {
		result1 error
	}{result1}
}

func (fake *MutableParentContext) PutServiceReturnsOnCall(i int, result1 error) {
	fake.putServiceMutex.Lock()
	defer fake.putServiceMutex.Unlock()
	fake.PutServiceStub = nil
	if fake.putServiceReturnsOnCall == nil {
		fake.putServiceReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.putServiceReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *MutableParentContext) PutSession(arg1 viewa.View, arg2 viewa.Identity, arg3 viewa.Session) error {
	fake.putSessionMutex.Lock()
	ret, specificReturn := fake.putSessionReturnsOnCall[len(fake.putSessionArgsForCall)]
	fake.putSessionArgsForCall = append(fake.putSessionArgsForCall, struct {
		arg1 viewa.View
		arg2 viewa.Identity
		arg3 viewa.Session
	}{arg1, arg2, arg3})
	stub := fake.PutSessionStub
	fakeReturns := fake.putSessionReturns
	fake.recordInvocation("PutSession", []any{arg1, arg2, arg3})
	fake.putSessionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *MutableParentContext) PutSessionCallCount() int {
	fake.putSessionMutex.RLock()
	defer fake.putSessionMutex.RUnlock()
	return len(fake.putSessionArgsForCall)
}

func (fake *MutableParentContext) PutSessionCalls(stub func(viewa.View, viewa.Identity, viewa.Session) error) {
	fake.putSessionMutex.Lock()
	defer fake.putSessionMutex.Unlock()
	fake.PutSessionStub = stub
}

func (fake *MutableParentContext) PutSessionArgsForCall(i int) (viewa.View, viewa.Identity, viewa.Session) {
	fake.putSessionMutex.RLock()
	defer fake.putSessionMutex.RUnlock()
	argsForCall := fake.putSessionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *MutableParentContext) PutSessionReturns(result1 error) {
	fake.putSessionMutex.Lock()
	defer fake.putSessionMutex.Unlock()
	fake.PutSessionStub = nil
	fake.putSessionReturns = struct {
		result1 error
	}{result1}
}

func (fake *MutableParentContext) PutSessionReturnsOnCall(i int, result1 error) {
	fake.putSessionMutex.Lock()
	defer fake.putSessionMutex.Unlock()
	fake.PutSessionStub = nil
	if fake.putSessionReturnsOnCall == nil {
		fake.putSessionReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.putSessionReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *MutableParentContext) PutSessionByID(arg1 string, arg2 viewa.Identity, arg3 viewa.Session) error {
	fake.putSessionByIDMutex.Lock()
	ret, specificReturn := fake.putSessionByIDReturnsOnCall[len(fake.putSessionByIDArgsForCall)]
	fake.putSessionByIDArgsForCall = append(fake.putSessionByIDArgsForCall, struct {
		arg1 string
		arg2 viewa.Identity
		arg3 viewa.Session
	}{arg1, arg2, arg3})
	stub := fake.PutSessionByIDStub
	fakeReturns := fake.putSessionByIDReturns
	fake.recordInvocation("PutSessionByID", []any{arg1, arg2, arg3})
	fake.putSessionByIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *MutableParentContext) PutSessionByIDCallCount() int {
	fake.putSessionByIDMutex.RLock()
	defer fake.putSessionByIDMutex.RUnlock()
	return len(fake.putSessionByIDArgsForCall)
}

func (fake *MutableParentContext) PutSessionByIDCalls(stub func(string, viewa.Identity, viewa.Session) error) {
	fake.putSessionByIDMutex.Lock()
	defer fake.putSessionByIDMutex.Unlock()
	fake.PutSessionByIDStub = stub
}

func (fake *MutableParentContext) PutSessionByIDArgsForCall(i int) (string, viewa.Identity, viewa.Session) {
	fake.putSessionByIDMutex.RLock()
	defer fake.putSessionByIDMutex.RUnlock()
	argsForCall := fake.putSessionByIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *MutableParentContext) PutSessionByIDReturns(result1 error) {
	fake.putSessionByIDMutex.Lock()
	defer fake.putSessionByIDMutex.Unlock()
	fake.PutSessionByIDStub = nil
	fake.putSessionByIDReturns = struct {
		result1 error
	}{result1}
}

func (fake *MutableParentContext) PutSessionByIDReturnsOnCall(i int, result1 error) {
	fake.putSessionByIDMutex.Lock()
	defer fake.putSessionByIDMutex.Unlock()
	fake.PutSessionByIDStub = nil
	if fake.putSessionByIDReturnsOnCall == nil {
		fake.putSessionByIDReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.putSessionByIDReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *MutableParentContext) ResetSessions() error {
	fake.resetSessionsMutex.Lock()
	ret, specificReturn := fake.resetSessionsReturnsOnCall[len(fake.resetSessionsArgsForCall)]
	fake.resetSessionsArgsForCall = append(fake.resetSessionsArgsForCall, struct {
	}{})
	stub := fake.ResetSessionsStub
	fakeReturns := fake.resetSessionsReturns
	fake.recordInvocation("ResetSessions", []any{})
	fake.resetSessionsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *MutableParentContext) ResetSessionsCallCount() int {
	fake.resetSessionsMutex.RLock()
	defer fake.resetSessionsMutex.RUnlock()
	return len(fake.resetSessionsArgsForCall)
}

func (fake *MutableParentContext) ResetSessionsCalls(stub func() error) {
	fake.resetSessionsMutex.Lock()
	defer fake.resetSessionsMutex.Unlock()
	fake.ResetSessionsStub = stub
}

func (fake *MutableParentContext) ResetSessionsReturns(result1 error) {
	fake.resetSessionsMutex.Lock()
	defer fake.resetSessionsMutex.Unlock()
	fake.ResetSessionsStub = nil
	fake.resetSessionsReturns = struct {
		result1 error
	}{result1}
}

func (fake *MutableParentContext) ResetSessionsReturnsOnCall(i int, result1 error) {
	fake.resetSessionsMutex.Lock()
	defer fake.resetSessionsMutex.Unlock()
	fake.ResetSessionsStub = nil
	if fake.resetSessionsReturnsOnCall == nil {
		fake.resetSessionsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.resetSessionsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *MutableParentContext) RunView(arg1 viewa.View, arg2 ...viewa.RunViewOption) (any, error) {
	fake.runViewMutex.Lock()
	ret, specificReturn := fake.runViewReturnsOnCall[len(fake.runViewArgsForCall)]
	fake.runViewArgsForCall = append(fake.runViewArgsForCall, struct {
		arg1 viewa.View
		arg2 []viewa.RunViewOption
	}{arg1, arg2})
	stub := fake.RunViewStub
	fakeReturns := fake.runViewReturns
	fake.recordInvocation("RunView", []any{arg1, arg2})
	fake.runViewMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *MutableParentContext) RunViewCallCount() int {
	fake.runViewMutex.RLock()
	defer fake.runViewMutex.RUnlock()
	return len(fake.runViewArgsForCall)
}

func (fake *MutableParentContext) RunViewCalls(stub func(viewa.View, ...viewa.RunViewOption) (any, error)) {
	fake.runViewMutex.Lock()
	defer fake.runViewMutex.Unlock()
	fake.RunViewStub = stub
}

func (fake *MutableParentContext) RunViewArgsForCall(i int) (viewa.View, []viewa.RunViewOption) {
	fake.runViewMutex.RLock()
	defer fake.runViewMutex.RUnlock()
	argsForCall := fake.runViewArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *MutableParentContext) RunViewReturns(result1 any, result2 error) {
	fake.runViewMutex.Lock()
	defer fake.runViewMutex.Unlock()
	fake.RunViewStub = nil
	fake.runViewReturns = struct {
		result1 any
		result2 error
	}{result1, result2}
}

func (fake *MutableParentContext) RunViewReturnsOnCall(i int, result1 any, result2 error) {
	fake.runViewMutex.Lock()
	defer fake.runViewMutex.Unlock()
	fake.RunViewStub = nil
	if fake.runViewReturnsOnCall == nil {
		fake.runViewReturnsOnCall = make(map[int]struct {
			result1 any
			result2 error
		})
	}
	fake.runViewReturnsOnCall[i] = struct {
		result1 any
		result2 error
	}{result1, result2}
}

func (fake *MutableParentContext) Session() viewa.Session {
	fake.sessionMutex.Lock()
	ret, specificReturn := fake.sessionReturnsOnCall[len(fake.sessionArgsForCall)]
	fake.sessionArgsForCall = append(fake.sessionArgsForCall, struct {
	}{})
	stub := fake.SessionStub
	fakeReturns := fake.sessionReturns
	fake.recordInvocation("Session", []any{})
	fake.sessionMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *MutableParentContext) SessionCallCount() int {
	fake.sessionMutex.RLock()
	defer fake.sessionMutex.RUnlock()
	return len(fake.sessionArgsForCall)
}

func (fake *MutableParentContext) SessionCalls(stub func() viewa.Session) {
	fake.sessionMutex.Lock()
	defer fake.sessionMutex.Unlock()
	fake.SessionStub = stub
}

func (fake *MutableParentContext) SessionReturns(result1 viewa.Session) {
	fake.sessionMutex.Lock()
	defer fake.sessionMutex.Unlock()
	fake.SessionStub = nil
	fake.sessionReturns = struct {
		result1 viewa.Session
	}{result1}
}

func (fake *MutableParentContext) SessionReturnsOnCall(i int, result1 viewa.Session) {
	fake.sessionMutex.Lock()
	defer fake.sessionMutex.Unlock()
	fake.SessionStub = nil
	if fake.sessionReturnsOnCall == nil {
		fake.sessionReturnsOnCall = make(map[int]struct {
			result1 viewa.Session
		})
	}
	fake.sessionReturnsOnCall[i] = struct {
		result1 viewa.Session
	}{result1}
}

func (fake *MutableParentContext) StartSpanFrom(arg1 context.Context, arg2 string, arg3 ...trace.SpanStartOption) (context.Context, trace.Span) {
	fake.startSpanFromMutex.Lock()
	ret, specificReturn := fake.startSpanFromReturnsOnCall[len(fake.startSpanFromArgsForCall)]
	fake.startSpanFromArgsForCall = append(fake.startSpanFromArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 []trace.SpanStartOption
	}{arg1, arg2, arg3})
	stub := fake.StartSpanFromStub
	fakeReturns := fake.startSpanFromReturns
	fake.recordInvocation("StartSpanFrom", []any{arg1, arg2, arg3})
	fake.startSpanFromMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *MutableParentContext) StartSpanFromCallCount() int {
	fake.startSpanFromMutex.RLock()
	defer fake.startSpanFromMutex.RUnlock()
	return len(fake.startSpanFromArgsForCall)
}

func (fake *MutableParentContext) StartSpanFromCalls(stub func(context.Context, string, ...trace.SpanStartOption) (context.Context, trace.Span)) {
	fake.startSpanFromMutex.Lock()
	defer fake.startSpanFromMutex.Unlock()
	fake.StartSpanFromStub = stub
}

func (fake *MutableParentContext) StartSpanFromArgsForCall(i int) (context.Context, string, []trace.SpanStartOption) {
	fake.startSpanFromMutex.RLock()
	defer fake.startSpanFromMutex.RUnlock()
	argsForCall := fake.startSpanFromArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *MutableParentContext) StartSpanFromReturns(result1 context.Context, result2 trace.Span) {
	fake.startSpanFromMutex.Lock()
	defer fake.startSpanFromMutex.Unlock()
	fake.StartSpanFromStub = nil
	fake.startSpanFromReturns = struct {
		result1 context.Context
		result2 trace.Span
	}{result1, result2}
}

func (fake *MutableParentContext) StartSpanFromReturnsOnCall(i int, result1 context.Context, result2 trace.Span) {
	fake.startSpanFromMutex.Lock()
	defer fake.startSpanFromMutex.Unlock()
	fake.StartSpanFromStub = nil
	if fake.startSpanFromReturnsOnCall == nil {
		fake.startSpanFromReturnsOnCall = make(map[int]struct {
			result1 context.Context
			result2 trace.Span
		})
	}
	fake.startSpanFromReturnsOnCall[i] = struct {
		result1 context.Context
		result2 trace.Span
	}{result1, result2}
}

func (fake *MutableParentContext) Invocations() map[string][][]any {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]any{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *MutableParentContext) recordInvocation(key string, args []any) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]any{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]any{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ view.MutableParentContext = new(MutableParentContext)
