// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"sync"

	"github.com/hyperledger-labs/fabric-smart-client/platform/view/services/storage/driver"
)

type Driver struct {
	NewAuditInfoStub        func(driver.PersistenceName, ...string) (driver.AuditInfoStore, error)
	newAuditInfoMutex       sync.RWMutex
	newAuditInfoArgsForCall []struct {
		arg1 driver.PersistenceName
		arg2 []string
	}
	newAuditInfoReturns struct {
		result1 driver.AuditInfoStore
		result2 error
	}
	newAuditInfoReturnsOnCall map[int]struct {
		result1 driver.AuditInfoStore
		result2 error
	}
	NewBindingStub        func(driver.PersistenceName, ...string) (driver.BindingStore, error)
	newBindingMutex       sync.RWMutex
	newBindingArgsForCall []struct {
		arg1 driver.PersistenceName
		arg2 []string
	}
	newBindingReturns struct {
		result1 driver.BindingStore
		result2 error
	}
	newBindingReturnsOnCall map[int]struct {
		result1 driver.BindingStore
		result2 error
	}
	NewKVSStub        func(driver.PersistenceName, ...string) (driver.KeyValueStore, error)
	newKVSMutex       sync.RWMutex
	newKVSArgsForCall []struct {
		arg1 driver.PersistenceName
		arg2 []string
	}
	newKVSReturns struct {
		result1 driver.KeyValueStore
		result2 error
	}
	newKVSReturnsOnCall map[int]struct {
		result1 driver.KeyValueStore
		result2 error
	}
	NewSignerInfoStub        func(driver.PersistenceName, ...string) (driver.SignerInfoStore, error)
	newSignerInfoMutex       sync.RWMutex
	newSignerInfoArgsForCall []struct {
		arg1 driver.PersistenceName
		arg2 []string
	}
	newSignerInfoReturns struct {
		result1 driver.SignerInfoStore
		result2 error
	}
	newSignerInfoReturnsOnCall map[int]struct {
		result1 driver.SignerInfoStore
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Driver) NewAuditInfo(arg1 driver.PersistenceName, arg2 ...string) (driver.AuditInfoStore, error) {
	fake.newAuditInfoMutex.Lock()
	ret, specificReturn := fake.newAuditInfoReturnsOnCall[len(fake.newAuditInfoArgsForCall)]
	fake.newAuditInfoArgsForCall = append(fake.newAuditInfoArgsForCall, struct {
		arg1 driver.PersistenceName
		arg2 []string
	}{arg1, arg2})
	stub := fake.NewAuditInfoStub
	fakeReturns := fake.newAuditInfoReturns
	fake.recordInvocation("NewAuditInfo", []interface{}{arg1, arg2})
	fake.newAuditInfoMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Driver) NewAuditInfoCallCount() int {
	fake.newAuditInfoMutex.RLock()
	defer fake.newAuditInfoMutex.RUnlock()
	return len(fake.newAuditInfoArgsForCall)
}

func (fake *Driver) NewAuditInfoCalls(stub func(driver.PersistenceName, ...string) (driver.AuditInfoStore, error)) {
	fake.newAuditInfoMutex.Lock()
	defer fake.newAuditInfoMutex.Unlock()
	fake.NewAuditInfoStub = stub
}

func (fake *Driver) NewAuditInfoArgsForCall(i int) (driver.PersistenceName, []string) {
	fake.newAuditInfoMutex.RLock()
	defer fake.newAuditInfoMutex.RUnlock()
	argsForCall := fake.newAuditInfoArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Driver) NewAuditInfoReturns(result1 driver.AuditInfoStore, result2 error) {
	fake.newAuditInfoMutex.Lock()
	defer fake.newAuditInfoMutex.Unlock()
	fake.NewAuditInfoStub = nil
	fake.newAuditInfoReturns = struct {
		result1 driver.AuditInfoStore
		result2 error
	}{result1, result2}
}

func (fake *Driver) NewAuditInfoReturnsOnCall(i int, result1 driver.AuditInfoStore, result2 error) {
	fake.newAuditInfoMutex.Lock()
	defer fake.newAuditInfoMutex.Unlock()
	fake.NewAuditInfoStub = nil
	if fake.newAuditInfoReturnsOnCall == nil {
		fake.newAuditInfoReturnsOnCall = make(map[int]struct {
			result1 driver.AuditInfoStore
			result2 error
		})
	}
	fake.newAuditInfoReturnsOnCall[i] = struct {
		result1 driver.AuditInfoStore
		result2 error
	}{result1, result2}
}

func (fake *Driver) NewBinding(arg1 driver.PersistenceName, arg2 ...string) (driver.BindingStore, error) {
	fake.newBindingMutex.Lock()
	ret, specificReturn := fake.newBindingReturnsOnCall[len(fake.newBindingArgsForCall)]
	fake.newBindingArgsForCall = append(fake.newBindingArgsForCall, struct {
		arg1 driver.PersistenceName
		arg2 []string
	}{arg1, arg2})
	stub := fake.NewBindingStub
	fakeReturns := fake.newBindingReturns
	fake.recordInvocation("NewBinding", []interface{}{arg1, arg2})
	fake.newBindingMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Driver) NewBindingCallCount() int {
	fake.newBindingMutex.RLock()
	defer fake.newBindingMutex.RUnlock()
	return len(fake.newBindingArgsForCall)
}

func (fake *Driver) NewBindingCalls(stub func(driver.PersistenceName, ...string) (driver.BindingStore, error)) {
	fake.newBindingMutex.Lock()
	defer fake.newBindingMutex.Unlock()
	fake.NewBindingStub = stub
}

func (fake *Driver) NewBindingArgsForCall(i int) (driver.PersistenceName, []string) {
	fake.newBindingMutex.RLock()
	defer fake.newBindingMutex.RUnlock()
	argsForCall := fake.newBindingArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Driver) NewBindingReturns(result1 driver.BindingStore, result2 error) {
	fake.newBindingMutex.Lock()
	defer fake.newBindingMutex.Unlock()
	fake.NewBindingStub = nil
	fake.newBindingReturns = struct {
		result1 driver.BindingStore
		result2 error
	}{result1, result2}
}

func (fake *Driver) NewBindingReturnsOnCall(i int, result1 driver.BindingStore, result2 error) {
	fake.newBindingMutex.Lock()
	defer fake.newBindingMutex.Unlock()
	fake.NewBindingStub = nil
	if fake.newBindingReturnsOnCall == nil {
		fake.newBindingReturnsOnCall = make(map[int]struct {
			result1 driver.BindingStore
			result2 error
		})
	}
	fake.newBindingReturnsOnCall[i] = struct {
		result1 driver.BindingStore
		result2 error
	}{result1, result2}
}

func (fake *Driver) NewKVS(arg1 driver.PersistenceName, arg2 ...string) (driver.KeyValueStore, error) {
	fake.newKVSMutex.Lock()
	ret, specificReturn := fake.newKVSReturnsOnCall[len(fake.newKVSArgsForCall)]
	fake.newKVSArgsForCall = append(fake.newKVSArgsForCall, struct {
		arg1 driver.PersistenceName
		arg2 []string
	}{arg1, arg2})
	stub := fake.NewKVSStub
	fakeReturns := fake.newKVSReturns
	fake.recordInvocation("NewKVS", []interface{}{arg1, arg2})
	fake.newKVSMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Driver) NewKVSCallCount() int {
	fake.newKVSMutex.RLock()
	defer fake.newKVSMutex.RUnlock()
	return len(fake.newKVSArgsForCall)
}

func (fake *Driver) NewKVSCalls(stub func(driver.PersistenceName, ...string) (driver.KeyValueStore, error)) {
	fake.newKVSMutex.Lock()
	defer fake.newKVSMutex.Unlock()
	fake.NewKVSStub = stub
}

func (fake *Driver) NewKVSArgsForCall(i int) (driver.PersistenceName, []string) {
	fake.newKVSMutex.RLock()
	defer fake.newKVSMutex.RUnlock()
	argsForCall := fake.newKVSArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Driver) NewKVSReturns(result1 driver.KeyValueStore, result2 error) {
	fake.newKVSMutex.Lock()
	defer fake.newKVSMutex.Unlock()
	fake.NewKVSStub = nil
	fake.newKVSReturns = struct {
		result1 driver.KeyValueStore
		result2 error
	}{result1, result2}
}

func (fake *Driver) NewKVSReturnsOnCall(i int, result1 driver.KeyValueStore, result2 error) {
	fake.newKVSMutex.Lock()
	defer fake.newKVSMutex.Unlock()
	fake.NewKVSStub = nil
	if fake.newKVSReturnsOnCall == nil {
		fake.newKVSReturnsOnCall = make(map[int]struct {
			result1 driver.KeyValueStore
			result2 error
		})
	}
	fake.newKVSReturnsOnCall[i] = struct {
		result1 driver.KeyValueStore
		result2 error
	}{result1, result2}
}

func (fake *Driver) NewSignerInfo(arg1 driver.PersistenceName, arg2 ...string) (driver.SignerInfoStore, error) {
	fake.newSignerInfoMutex.Lock()
	ret, specificReturn := fake.newSignerInfoReturnsOnCall[len(fake.newSignerInfoArgsForCall)]
	fake.newSignerInfoArgsForCall = append(fake.newSignerInfoArgsForCall, struct {
		arg1 driver.PersistenceName
		arg2 []string
	}{arg1, arg2})
	stub := fake.NewSignerInfoStub
	fakeReturns := fake.newSignerInfoReturns
	fake.recordInvocation("NewSignerInfo", []interface{}{arg1, arg2})
	fake.newSignerInfoMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Driver) NewSignerInfoCallCount() int {
	fake.newSignerInfoMutex.RLock()
	defer fake.newSignerInfoMutex.RUnlock()
	return len(fake.newSignerInfoArgsForCall)
}

func (fake *Driver) NewSignerInfoCalls(stub func(driver.PersistenceName, ...string) (driver.SignerInfoStore, error)) {
	fake.newSignerInfoMutex.Lock()
	defer fake.newSignerInfoMutex.Unlock()
	fake.NewSignerInfoStub = stub
}

func (fake *Driver) NewSignerInfoArgsForCall(i int) (driver.PersistenceName, []string) {
	fake.newSignerInfoMutex.RLock()
	defer fake.newSignerInfoMutex.RUnlock()
	argsForCall := fake.newSignerInfoArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Driver) NewSignerInfoReturns(result1 driver.SignerInfoStore, result2 error) {
	fake.newSignerInfoMutex.Lock()
	defer fake.newSignerInfoMutex.Unlock()
	fake.NewSignerInfoStub = nil
	fake.newSignerInfoReturns = struct {
		result1 driver.SignerInfoStore
		result2 error
	}{result1, result2}
}

func (fake *Driver) NewSignerInfoReturnsOnCall(i int, result1 driver.SignerInfoStore, result2 error) {
	fake.newSignerInfoMutex.Lock()
	defer fake.newSignerInfoMutex.Unlock()
	fake.NewSignerInfoStub = nil
	if fake.newSignerInfoReturnsOnCall == nil {
		fake.newSignerInfoReturnsOnCall = make(map[int]struct {
			result1 driver.SignerInfoStore
			result2 error
		})
	}
	fake.newSignerInfoReturnsOnCall[i] = struct {
		result1 driver.SignerInfoStore
		result2 error
	}{result1, result2}
}

func (fake *Driver) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Driver) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ driver.Driver = new(Driver)
