// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"context"
	"sync"

	drivera "github.com/hyperledger-labs/fabric-smart-client/platform/common/driver"
	"github.com/hyperledger-labs/fabric-smart-client/platform/common/utils/collections/iterators"
	"github.com/hyperledger-labs/fabric-smart-client/platform/view/services/storage/driver"
)

type KeyValueStore struct {
	BeginUpdateStub        func() error
	beginUpdateMutex       sync.RWMutex
	beginUpdateArgsForCall []struct {
	}
	beginUpdateReturns struct {
		result1 error
	}
	beginUpdateReturnsOnCall map[int]struct {
		result1 error
	}
	CloseStub        func() error
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
	}
	closeReturns struct {
		result1 error
	}
	closeReturnsOnCall map[int]struct {
		result1 error
	}
	CommitStub        func() error
	commitMutex       sync.RWMutex
	commitArgsForCall []struct {
	}
	commitReturns struct {
		result1 error
	}
	commitReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteStateStub        func(context.Context, drivera.Namespace, drivera.PKey) error
	deleteStateMutex       sync.RWMutex
	deleteStateArgsForCall []struct {
		arg1 context.Context
		arg2 drivera.Namespace
		arg3 drivera.PKey
	}
	deleteStateReturns struct {
		result1 error
	}
	deleteStateReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteStatesStub        func(context.Context, drivera.Namespace, ...drivera.PKey) map[drivera.PKey]error
	deleteStatesMutex       sync.RWMutex
	deleteStatesArgsForCall []struct {
		arg1 context.Context
		arg2 drivera.Namespace
		arg3 []drivera.PKey
	}
	deleteStatesReturns struct {
		result1 map[drivera.PKey]error
	}
	deleteStatesReturnsOnCall map[int]struct {
		result1 map[drivera.PKey]error
	}
	DiscardStub        func() error
	discardMutex       sync.RWMutex
	discardArgsForCall []struct {
	}
	discardReturns struct {
		result1 error
	}
	discardReturnsOnCall map[int]struct {
		result1 error
	}
	GetStateStub        func(context.Context, drivera.Namespace, drivera.PKey) (drivera.UnversionedValue, error)
	getStateMutex       sync.RWMutex
	getStateArgsForCall []struct {
		arg1 context.Context
		arg2 drivera.Namespace
		arg3 drivera.PKey
	}
	getStateReturns struct {
		result1 drivera.UnversionedValue
		result2 error
	}
	getStateReturnsOnCall map[int]struct {
		result1 drivera.UnversionedValue
		result2 error
	}
	GetStateRangeScanIteratorStub        func(context.Context, drivera.Namespace, drivera.PKey, drivera.PKey) (iterators.Iterator[*drivera.UnversionedRead], error)
	getStateRangeScanIteratorMutex       sync.RWMutex
	getStateRangeScanIteratorArgsForCall []struct {
		arg1 context.Context
		arg2 drivera.Namespace
		arg3 drivera.PKey
		arg4 drivera.PKey
	}
	getStateRangeScanIteratorReturns struct {
		result1 iterators.Iterator[*drivera.UnversionedRead]
		result2 error
	}
	getStateRangeScanIteratorReturnsOnCall map[int]struct {
		result1 iterators.Iterator[*drivera.UnversionedRead]
		result2 error
	}
	GetStateSetIteratorStub        func(context.Context, drivera.Namespace, ...drivera.PKey) (iterators.Iterator[*drivera.UnversionedRead], error)
	getStateSetIteratorMutex       sync.RWMutex
	getStateSetIteratorArgsForCall []struct {
		arg1 context.Context
		arg2 drivera.Namespace
		arg3 []drivera.PKey
	}
	getStateSetIteratorReturns struct {
		result1 iterators.Iterator[*drivera.UnversionedRead]
		result2 error
	}
	getStateSetIteratorReturnsOnCall map[int]struct {
		result1 iterators.Iterator[*drivera.UnversionedRead]
		result2 error
	}
	SetStateStub        func(context.Context, drivera.Namespace, drivera.PKey, drivera.UnversionedValue) error
	setStateMutex       sync.RWMutex
	setStateArgsForCall []struct {
		arg1 context.Context
		arg2 drivera.Namespace
		arg3 drivera.PKey
		arg4 drivera.UnversionedValue
	}
	setStateReturns struct {
		result1 error
	}
	setStateReturnsOnCall map[int]struct {
		result1 error
	}
	SetStatesStub        func(context.Context, drivera.Namespace, map[drivera.PKey]drivera.UnversionedValue) map[drivera.PKey]error
	setStatesMutex       sync.RWMutex
	setStatesArgsForCall []struct {
		arg1 context.Context
		arg2 drivera.Namespace
		arg3 map[drivera.PKey]drivera.UnversionedValue
	}
	setStatesReturns struct {
		result1 map[drivera.PKey]error
	}
	setStatesReturnsOnCall map[int]struct {
		result1 map[drivera.PKey]error
	}
	StatsStub        func() any
	statsMutex       sync.RWMutex
	statsArgsForCall []struct {
	}
	statsReturns struct {
		result1 any
	}
	statsReturnsOnCall map[int]struct {
		result1 any
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *KeyValueStore) BeginUpdate() error {
	fake.beginUpdateMutex.Lock()
	ret, specificReturn := fake.beginUpdateReturnsOnCall[len(fake.beginUpdateArgsForCall)]
	fake.beginUpdateArgsForCall = append(fake.beginUpdateArgsForCall, struct {
	}{})
	stub := fake.BeginUpdateStub
	fakeReturns := fake.beginUpdateReturns
	fake.recordInvocation("BeginUpdate", []interface{}{})
	fake.beginUpdateMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *KeyValueStore) BeginUpdateCallCount() int {
	fake.beginUpdateMutex.RLock()
	defer fake.beginUpdateMutex.RUnlock()
	return len(fake.beginUpdateArgsForCall)
}

func (fake *KeyValueStore) BeginUpdateCalls(stub func() error) {
	fake.beginUpdateMutex.Lock()
	defer fake.beginUpdateMutex.Unlock()
	fake.BeginUpdateStub = stub
}

func (fake *KeyValueStore) BeginUpdateReturns(result1 error) {
	fake.beginUpdateMutex.Lock()
	defer fake.beginUpdateMutex.Unlock()
	fake.BeginUpdateStub = nil
	fake.beginUpdateReturns = struct {
		result1 error
	}{result1}
}

func (fake *KeyValueStore) BeginUpdateReturnsOnCall(i int, result1 error) {
	fake.beginUpdateMutex.Lock()
	defer fake.beginUpdateMutex.Unlock()
	fake.BeginUpdateStub = nil
	if fake.beginUpdateReturnsOnCall == nil {
		fake.beginUpdateReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.beginUpdateReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *KeyValueStore) Close() error {
	fake.closeMutex.Lock()
	ret, specificReturn := fake.closeReturnsOnCall[len(fake.closeArgsForCall)]
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
	}{})
	stub := fake.CloseStub
	fakeReturns := fake.closeReturns
	fake.recordInvocation("Close", []interface{}{})
	fake.closeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *KeyValueStore) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *KeyValueStore) CloseCalls(stub func() error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *KeyValueStore) CloseReturns(result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	fake.closeReturns = struct {
		result1 error
	}{result1}
}

func (fake *KeyValueStore) CloseReturnsOnCall(i int, result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	if fake.closeReturnsOnCall == nil {
		fake.closeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.closeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *KeyValueStore) Commit() error {
	fake.commitMutex.Lock()
	ret, specificReturn := fake.commitReturnsOnCall[len(fake.commitArgsForCall)]
	fake.commitArgsForCall = append(fake.commitArgsForCall, struct {
	}{})
	stub := fake.CommitStub
	fakeReturns := fake.commitReturns
	fake.recordInvocation("Commit", []interface{}{})
	fake.commitMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *KeyValueStore) CommitCallCount() int {
	fake.commitMutex.RLock()
	defer fake.commitMutex.RUnlock()
	return len(fake.commitArgsForCall)
}

func (fake *KeyValueStore) CommitCalls(stub func() error) {
	fake.commitMutex.Lock()
	defer fake.commitMutex.Unlock()
	fake.CommitStub = stub
}

func (fake *KeyValueStore) CommitReturns(result1 error) {
	fake.commitMutex.Lock()
	defer fake.commitMutex.Unlock()
	fake.CommitStub = nil
	fake.commitReturns = struct {
		result1 error
	}{result1}
}

func (fake *KeyValueStore) CommitReturnsOnCall(i int, result1 error) {
	fake.commitMutex.Lock()
	defer fake.commitMutex.Unlock()
	fake.CommitStub = nil
	if fake.commitReturnsOnCall == nil {
		fake.commitReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.commitReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *KeyValueStore) DeleteState(arg1 context.Context, arg2 drivera.Namespace, arg3 drivera.PKey) error {
	fake.deleteStateMutex.Lock()
	ret, specificReturn := fake.deleteStateReturnsOnCall[len(fake.deleteStateArgsForCall)]
	fake.deleteStateArgsForCall = append(fake.deleteStateArgsForCall, struct {
		arg1 context.Context
		arg2 drivera.Namespace
		arg3 drivera.PKey
	}{arg1, arg2, arg3})
	stub := fake.DeleteStateStub
	fakeReturns := fake.deleteStateReturns
	fake.recordInvocation("DeleteState", []interface{}{arg1, arg2, arg3})
	fake.deleteStateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *KeyValueStore) DeleteStateCallCount() int {
	fake.deleteStateMutex.RLock()
	defer fake.deleteStateMutex.RUnlock()
	return len(fake.deleteStateArgsForCall)
}

func (fake *KeyValueStore) DeleteStateCalls(stub func(context.Context, drivera.Namespace, drivera.PKey) error) {
	fake.deleteStateMutex.Lock()
	defer fake.deleteStateMutex.Unlock()
	fake.DeleteStateStub = stub
}

func (fake *KeyValueStore) DeleteStateArgsForCall(i int) (context.Context, drivera.Namespace, drivera.PKey) {
	fake.deleteStateMutex.RLock()
	defer fake.deleteStateMutex.RUnlock()
	argsForCall := fake.deleteStateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *KeyValueStore) DeleteStateReturns(result1 error) {
	fake.deleteStateMutex.Lock()
	defer fake.deleteStateMutex.Unlock()
	fake.DeleteStateStub = nil
	fake.deleteStateReturns = struct {
		result1 error
	}{result1}
}

func (fake *KeyValueStore) DeleteStateReturnsOnCall(i int, result1 error) {
	fake.deleteStateMutex.Lock()
	defer fake.deleteStateMutex.Unlock()
	fake.DeleteStateStub = nil
	if fake.deleteStateReturnsOnCall == nil {
		fake.deleteStateReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteStateReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *KeyValueStore) DeleteStates(arg1 context.Context, arg2 drivera.Namespace, arg3 ...drivera.PKey) map[drivera.PKey]error {
	fake.deleteStatesMutex.Lock()
	ret, specificReturn := fake.deleteStatesReturnsOnCall[len(fake.deleteStatesArgsForCall)]
	fake.deleteStatesArgsForCall = append(fake.deleteStatesArgsForCall, struct {
		arg1 context.Context
		arg2 drivera.Namespace
		arg3 []drivera.PKey
	}{arg1, arg2, arg3})
	stub := fake.DeleteStatesStub
	fakeReturns := fake.deleteStatesReturns
	fake.recordInvocation("DeleteStates", []interface{}{arg1, arg2, arg3})
	fake.deleteStatesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *KeyValueStore) DeleteStatesCallCount() int {
	fake.deleteStatesMutex.RLock()
	defer fake.deleteStatesMutex.RUnlock()
	return len(fake.deleteStatesArgsForCall)
}

func (fake *KeyValueStore) DeleteStatesCalls(stub func(context.Context, drivera.Namespace, ...drivera.PKey) map[drivera.PKey]error) {
	fake.deleteStatesMutex.Lock()
	defer fake.deleteStatesMutex.Unlock()
	fake.DeleteStatesStub = stub
}

func (fake *KeyValueStore) DeleteStatesArgsForCall(i int) (context.Context, drivera.Namespace, []drivera.PKey) {
	fake.deleteStatesMutex.RLock()
	defer fake.deleteStatesMutex.RUnlock()
	argsForCall := fake.deleteStatesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *KeyValueStore) DeleteStatesReturns(result1 map[drivera.PKey]error) {
	fake.deleteStatesMutex.Lock()
	defer fake.deleteStatesMutex.Unlock()
	fake.DeleteStatesStub = nil
	fake.deleteStatesReturns = struct {
		result1 map[drivera.PKey]error
	}{result1}
}

func (fake *KeyValueStore) DeleteStatesReturnsOnCall(i int, result1 map[drivera.PKey]error) {
	fake.deleteStatesMutex.Lock()
	defer fake.deleteStatesMutex.Unlock()
	fake.DeleteStatesStub = nil
	if fake.deleteStatesReturnsOnCall == nil {
		fake.deleteStatesReturnsOnCall = make(map[int]struct {
			result1 map[drivera.PKey]error
		})
	}
	fake.deleteStatesReturnsOnCall[i] = struct {
		result1 map[drivera.PKey]error
	}{result1}
}

func (fake *KeyValueStore) Discard() error {
	fake.discardMutex.Lock()
	ret, specificReturn := fake.discardReturnsOnCall[len(fake.discardArgsForCall)]
	fake.discardArgsForCall = append(fake.discardArgsForCall, struct {
	}{})
	stub := fake.DiscardStub
	fakeReturns := fake.discardReturns
	fake.recordInvocation("Discard", []interface{}{})
	fake.discardMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *KeyValueStore) DiscardCallCount() int {
	fake.discardMutex.RLock()
	defer fake.discardMutex.RUnlock()
	return len(fake.discardArgsForCall)
}

func (fake *KeyValueStore) DiscardCalls(stub func() error) {
	fake.discardMutex.Lock()
	defer fake.discardMutex.Unlock()
	fake.DiscardStub = stub
}

func (fake *KeyValueStore) DiscardReturns(result1 error) {
	fake.discardMutex.Lock()
	defer fake.discardMutex.Unlock()
	fake.DiscardStub = nil
	fake.discardReturns = struct {
		result1 error
	}{result1}
}

func (fake *KeyValueStore) DiscardReturnsOnCall(i int, result1 error) {
	fake.discardMutex.Lock()
	defer fake.discardMutex.Unlock()
	fake.DiscardStub = nil
	if fake.discardReturnsOnCall == nil {
		fake.discardReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.discardReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *KeyValueStore) GetState(arg1 context.Context, arg2 drivera.Namespace, arg3 drivera.PKey) (drivera.UnversionedValue, error) {
	fake.getStateMutex.Lock()
	ret, specificReturn := fake.getStateReturnsOnCall[len(fake.getStateArgsForCall)]
	fake.getStateArgsForCall = append(fake.getStateArgsForCall, struct {
		arg1 context.Context
		arg2 drivera.Namespace
		arg3 drivera.PKey
	}{arg1, arg2, arg3})
	stub := fake.GetStateStub
	fakeReturns := fake.getStateReturns
	fake.recordInvocation("GetState", []interface{}{arg1, arg2, arg3})
	fake.getStateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *KeyValueStore) GetStateCallCount() int {
	fake.getStateMutex.RLock()
	defer fake.getStateMutex.RUnlock()
	return len(fake.getStateArgsForCall)
}

func (fake *KeyValueStore) GetStateCalls(stub func(context.Context, drivera.Namespace, drivera.PKey) (drivera.UnversionedValue, error)) {
	fake.getStateMutex.Lock()
	defer fake.getStateMutex.Unlock()
	fake.GetStateStub = stub
}

func (fake *KeyValueStore) GetStateArgsForCall(i int) (context.Context, drivera.Namespace, drivera.PKey) {
	fake.getStateMutex.RLock()
	defer fake.getStateMutex.RUnlock()
	argsForCall := fake.getStateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *KeyValueStore) GetStateReturns(result1 drivera.UnversionedValue, result2 error) {
	fake.getStateMutex.Lock()
	defer fake.getStateMutex.Unlock()
	fake.GetStateStub = nil
	fake.getStateReturns = struct {
		result1 drivera.UnversionedValue
		result2 error
	}{result1, result2}
}

func (fake *KeyValueStore) GetStateReturnsOnCall(i int, result1 drivera.UnversionedValue, result2 error) {
	fake.getStateMutex.Lock()
	defer fake.getStateMutex.Unlock()
	fake.GetStateStub = nil
	if fake.getStateReturnsOnCall == nil {
		fake.getStateReturnsOnCall = make(map[int]struct {
			result1 drivera.UnversionedValue
			result2 error
		})
	}
	fake.getStateReturnsOnCall[i] = struct {
		result1 drivera.UnversionedValue
		result2 error
	}{result1, result2}
}

func (fake *KeyValueStore) GetStateRangeScanIterator(arg1 context.Context, arg2 drivera.Namespace, arg3 drivera.PKey, arg4 drivera.PKey) (iterators.Iterator[*drivera.UnversionedRead], error) {
	fake.getStateRangeScanIteratorMutex.Lock()
	ret, specificReturn := fake.getStateRangeScanIteratorReturnsOnCall[len(fake.getStateRangeScanIteratorArgsForCall)]
	fake.getStateRangeScanIteratorArgsForCall = append(fake.getStateRangeScanIteratorArgsForCall, struct {
		arg1 context.Context
		arg2 drivera.Namespace
		arg3 drivera.PKey
		arg4 drivera.PKey
	}{arg1, arg2, arg3, arg4})
	stub := fake.GetStateRangeScanIteratorStub
	fakeReturns := fake.getStateRangeScanIteratorReturns
	fake.recordInvocation("GetStateRangeScanIterator", []interface{}{arg1, arg2, arg3, arg4})
	fake.getStateRangeScanIteratorMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *KeyValueStore) GetStateRangeScanIteratorCallCount() int {
	fake.getStateRangeScanIteratorMutex.RLock()
	defer fake.getStateRangeScanIteratorMutex.RUnlock()
	return len(fake.getStateRangeScanIteratorArgsForCall)
}

func (fake *KeyValueStore) GetStateRangeScanIteratorCalls(stub func(context.Context, drivera.Namespace, drivera.PKey, drivera.PKey) (iterators.Iterator[*drivera.UnversionedRead], error)) {
	fake.getStateRangeScanIteratorMutex.Lock()
	defer fake.getStateRangeScanIteratorMutex.Unlock()
	fake.GetStateRangeScanIteratorStub = stub
}

func (fake *KeyValueStore) GetStateRangeScanIteratorArgsForCall(i int) (context.Context, drivera.Namespace, drivera.PKey, drivera.PKey) {
	fake.getStateRangeScanIteratorMutex.RLock()
	defer fake.getStateRangeScanIteratorMutex.RUnlock()
	argsForCall := fake.getStateRangeScanIteratorArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *KeyValueStore) GetStateRangeScanIteratorReturns(result1 iterators.Iterator[*drivera.UnversionedRead], result2 error) {
	fake.getStateRangeScanIteratorMutex.Lock()
	defer fake.getStateRangeScanIteratorMutex.Unlock()
	fake.GetStateRangeScanIteratorStub = nil
	fake.getStateRangeScanIteratorReturns = struct {
		result1 iterators.Iterator[*drivera.UnversionedRead]
		result2 error
	}{result1, result2}
}

func (fake *KeyValueStore) GetStateRangeScanIteratorReturnsOnCall(i int, result1 iterators.Iterator[*drivera.UnversionedRead], result2 error) {
	fake.getStateRangeScanIteratorMutex.Lock()
	defer fake.getStateRangeScanIteratorMutex.Unlock()
	fake.GetStateRangeScanIteratorStub = nil
	if fake.getStateRangeScanIteratorReturnsOnCall == nil {
		fake.getStateRangeScanIteratorReturnsOnCall = make(map[int]struct {
			result1 iterators.Iterator[*drivera.UnversionedRead]
			result2 error
		})
	}
	fake.getStateRangeScanIteratorReturnsOnCall[i] = struct {
		result1 iterators.Iterator[*drivera.UnversionedRead]
		result2 error
	}{result1, result2}
}

func (fake *KeyValueStore) GetStateSetIterator(arg1 context.Context, arg2 drivera.Namespace, arg3 ...drivera.PKey) (iterators.Iterator[*drivera.UnversionedRead], error) {
	fake.getStateSetIteratorMutex.Lock()
	ret, specificReturn := fake.getStateSetIteratorReturnsOnCall[len(fake.getStateSetIteratorArgsForCall)]
	fake.getStateSetIteratorArgsForCall = append(fake.getStateSetIteratorArgsForCall, struct {
		arg1 context.Context
		arg2 drivera.Namespace
		arg3 []drivera.PKey
	}{arg1, arg2, arg3})
	stub := fake.GetStateSetIteratorStub
	fakeReturns := fake.getStateSetIteratorReturns
	fake.recordInvocation("GetStateSetIterator", []interface{}{arg1, arg2, arg3})
	fake.getStateSetIteratorMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *KeyValueStore) GetStateSetIteratorCallCount() int {
	fake.getStateSetIteratorMutex.RLock()
	defer fake.getStateSetIteratorMutex.RUnlock()
	return len(fake.getStateSetIteratorArgsForCall)
}

func (fake *KeyValueStore) GetStateSetIteratorCalls(stub func(context.Context, drivera.Namespace, ...drivera.PKey) (iterators.Iterator[*drivera.UnversionedRead], error)) {
	fake.getStateSetIteratorMutex.Lock()
	defer fake.getStateSetIteratorMutex.Unlock()
	fake.GetStateSetIteratorStub = stub
}

func (fake *KeyValueStore) GetStateSetIteratorArgsForCall(i int) (context.Context, drivera.Namespace, []drivera.PKey) {
	fake.getStateSetIteratorMutex.RLock()
	defer fake.getStateSetIteratorMutex.RUnlock()
	argsForCall := fake.getStateSetIteratorArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *KeyValueStore) GetStateSetIteratorReturns(result1 iterators.Iterator[*drivera.UnversionedRead], result2 error) {
	fake.getStateSetIteratorMutex.Lock()
	defer fake.getStateSetIteratorMutex.Unlock()
	fake.GetStateSetIteratorStub = nil
	fake.getStateSetIteratorReturns = struct {
		result1 iterators.Iterator[*drivera.UnversionedRead]
		result2 error
	}{result1, result2}
}

func (fake *KeyValueStore) GetStateSetIteratorReturnsOnCall(i int, result1 iterators.Iterator[*drivera.UnversionedRead], result2 error) {
	fake.getStateSetIteratorMutex.Lock()
	defer fake.getStateSetIteratorMutex.Unlock()
	fake.GetStateSetIteratorStub = nil
	if fake.getStateSetIteratorReturnsOnCall == nil {
		fake.getStateSetIteratorReturnsOnCall = make(map[int]struct {
			result1 iterators.Iterator[*drivera.UnversionedRead]
			result2 error
		})
	}
	fake.getStateSetIteratorReturnsOnCall[i] = struct {
		result1 iterators.Iterator[*drivera.UnversionedRead]
		result2 error
	}{result1, result2}
}

func (fake *KeyValueStore) SetState(arg1 context.Context, arg2 drivera.Namespace, arg3 drivera.PKey, arg4 drivera.UnversionedValue) error {
	fake.setStateMutex.Lock()
	ret, specificReturn := fake.setStateReturnsOnCall[len(fake.setStateArgsForCall)]
	fake.setStateArgsForCall = append(fake.setStateArgsForCall, struct {
		arg1 context.Context
		arg2 drivera.Namespace
		arg3 drivera.PKey
		arg4 drivera.UnversionedValue
	}{arg1, arg2, arg3, arg4})
	stub := fake.SetStateStub
	fakeReturns := fake.setStateReturns
	fake.recordInvocation("SetState", []interface{}{arg1, arg2, arg3, arg4})
	fake.setStateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *KeyValueStore) SetStateCallCount() int {
	fake.setStateMutex.RLock()
	defer fake.setStateMutex.RUnlock()
	return len(fake.setStateArgsForCall)
}

func (fake *KeyValueStore) SetStateCalls(stub func(context.Context, drivera.Namespace, drivera.PKey, drivera.UnversionedValue) error) {
	fake.setStateMutex.Lock()
	defer fake.setStateMutex.Unlock()
	fake.SetStateStub = stub
}

func (fake *KeyValueStore) SetStateArgsForCall(i int) (context.Context, drivera.Namespace, drivera.PKey, drivera.UnversionedValue) {
	fake.setStateMutex.RLock()
	defer fake.setStateMutex.RUnlock()
	argsForCall := fake.setStateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *KeyValueStore) SetStateReturns(result1 error) {
	fake.setStateMutex.Lock()
	defer fake.setStateMutex.Unlock()
	fake.SetStateStub = nil
	fake.setStateReturns = struct {
		result1 error
	}{result1}
}

func (fake *KeyValueStore) SetStateReturnsOnCall(i int, result1 error) {
	fake.setStateMutex.Lock()
	defer fake.setStateMutex.Unlock()
	fake.SetStateStub = nil
	if fake.setStateReturnsOnCall == nil {
		fake.setStateReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.setStateReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *KeyValueStore) SetStates(arg1 context.Context, arg2 drivera.Namespace, arg3 map[drivera.PKey]drivera.UnversionedValue) map[drivera.PKey]error {
	fake.setStatesMutex.Lock()
	ret, specificReturn := fake.setStatesReturnsOnCall[len(fake.setStatesArgsForCall)]
	fake.setStatesArgsForCall = append(fake.setStatesArgsForCall, struct {
		arg1 context.Context
		arg2 drivera.Namespace
		arg3 map[drivera.PKey]drivera.UnversionedValue
	}{arg1, arg2, arg3})
	stub := fake.SetStatesStub
	fakeReturns := fake.setStatesReturns
	fake.recordInvocation("SetStates", []interface{}{arg1, arg2, arg3})
	fake.setStatesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *KeyValueStore) SetStatesCallCount() int {
	fake.setStatesMutex.RLock()
	defer fake.setStatesMutex.RUnlock()
	return len(fake.setStatesArgsForCall)
}

func (fake *KeyValueStore) SetStatesCalls(stub func(context.Context, drivera.Namespace, map[drivera.PKey]drivera.UnversionedValue) map[drivera.PKey]error) {
	fake.setStatesMutex.Lock()
	defer fake.setStatesMutex.Unlock()
	fake.SetStatesStub = stub
}

func (fake *KeyValueStore) SetStatesArgsForCall(i int) (context.Context, drivera.Namespace, map[drivera.PKey]drivera.UnversionedValue) {
	fake.setStatesMutex.RLock()
	defer fake.setStatesMutex.RUnlock()
	argsForCall := fake.setStatesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *KeyValueStore) SetStatesReturns(result1 map[drivera.PKey]error) {
	fake.setStatesMutex.Lock()
	defer fake.setStatesMutex.Unlock()
	fake.SetStatesStub = nil
	fake.setStatesReturns = struct {
		result1 map[drivera.PKey]error
	}{result1}
}

func (fake *KeyValueStore) SetStatesReturnsOnCall(i int, result1 map[drivera.PKey]error) {
	fake.setStatesMutex.Lock()
	defer fake.setStatesMutex.Unlock()
	fake.SetStatesStub = nil
	if fake.setStatesReturnsOnCall == nil {
		fake.setStatesReturnsOnCall = make(map[int]struct {
			result1 map[drivera.PKey]error
		})
	}
	fake.setStatesReturnsOnCall[i] = struct {
		result1 map[drivera.PKey]error
	}{result1}
}

func (fake *KeyValueStore) Stats() any {
	fake.statsMutex.Lock()
	ret, specificReturn := fake.statsReturnsOnCall[len(fake.statsArgsForCall)]
	fake.statsArgsForCall = append(fake.statsArgsForCall, struct {
	}{})
	stub := fake.StatsStub
	fakeReturns := fake.statsReturns
	fake.recordInvocation("Stats", []interface{}{})
	fake.statsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *KeyValueStore) StatsCallCount() int {
	fake.statsMutex.RLock()
	defer fake.statsMutex.RUnlock()
	return len(fake.statsArgsForCall)
}

func (fake *KeyValueStore) StatsCalls(stub func() any) {
	fake.statsMutex.Lock()
	defer fake.statsMutex.Unlock()
	fake.StatsStub = stub
}

func (fake *KeyValueStore) StatsReturns(result1 any) {
	fake.statsMutex.Lock()
	defer fake.statsMutex.Unlock()
	fake.StatsStub = nil
	fake.statsReturns = struct {
		result1 any
	}{result1}
}

func (fake *KeyValueStore) StatsReturnsOnCall(i int, result1 any) {
	fake.statsMutex.Lock()
	defer fake.statsMutex.Unlock()
	fake.StatsStub = nil
	if fake.statsReturnsOnCall == nil {
		fake.statsReturnsOnCall = make(map[int]struct {
			result1 any
		})
	}
	fake.statsReturnsOnCall[i] = struct {
		result1 any
	}{result1}
}

func (fake *KeyValueStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *KeyValueStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ driver.KeyValueStore = new(KeyValueStore)
