// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"sync"

	"github.com/hyperledger-labs/fabric-smart-client/platform/fabricx/core/committer/config"
)

type ServiceConfigProvider struct {
	NotificationServiceConfigStub        func(string) (*config.Config, error)
	notificationServiceConfigMutex       sync.RWMutex
	notificationServiceConfigArgsForCall []struct {
		arg1 string
	}
	notificationServiceConfigReturns struct {
		result1 *config.Config
		result2 error
	}
	notificationServiceConfigReturnsOnCall map[int]struct {
		result1 *config.Config
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ServiceConfigProvider) NotificationServiceConfig(arg1 string) (*config.Config, error) {
	fake.notificationServiceConfigMutex.Lock()
	ret, specificReturn := fake.notificationServiceConfigReturnsOnCall[len(fake.notificationServiceConfigArgsForCall)]
	fake.notificationServiceConfigArgsForCall = append(fake.notificationServiceConfigArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.NotificationServiceConfigStub
	fakeReturns := fake.notificationServiceConfigReturns
	fake.recordInvocation("NotificationServiceConfig", []interface{}{arg1})
	fake.notificationServiceConfigMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ServiceConfigProvider) NotificationServiceConfigCallCount() int {
	fake.notificationServiceConfigMutex.RLock()
	defer fake.notificationServiceConfigMutex.RUnlock()
	return len(fake.notificationServiceConfigArgsForCall)
}

func (fake *ServiceConfigProvider) NotificationServiceConfigCalls(stub func(string) (*config.Config, error)) {
	fake.notificationServiceConfigMutex.Lock()
	defer fake.notificationServiceConfigMutex.Unlock()
	fake.NotificationServiceConfigStub = stub
}

func (fake *ServiceConfigProvider) NotificationServiceConfigArgsForCall(i int) string {
	fake.notificationServiceConfigMutex.RLock()
	defer fake.notificationServiceConfigMutex.RUnlock()
	argsForCall := fake.notificationServiceConfigArgsForCall[i]
	return argsForCall.arg1
}

func (fake *ServiceConfigProvider) NotificationServiceConfigReturns(result1 *config.Config, result2 error) {
	fake.notificationServiceConfigMutex.Lock()
	defer fake.notificationServiceConfigMutex.Unlock()
	fake.NotificationServiceConfigStub = nil
	fake.notificationServiceConfigReturns = struct {
		result1 *config.Config
		result2 error
	}{result1, result2}
}

func (fake *ServiceConfigProvider) NotificationServiceConfigReturnsOnCall(i int, result1 *config.Config, result2 error) {
	fake.notificationServiceConfigMutex.Lock()
	defer fake.notificationServiceConfigMutex.Unlock()
	fake.NotificationServiceConfigStub = nil
	if fake.notificationServiceConfigReturnsOnCall == nil {
		fake.notificationServiceConfigReturnsOnCall = make(map[int]struct {
			result1 *config.Config
			result2 error
		})
	}
	fake.notificationServiceConfigReturnsOnCall[i] = struct {
		result1 *config.Config
		result2 error
	}{result1, result2}
}

func (fake *ServiceConfigProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ServiceConfigProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
