// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"context"
	"sync"

	"github.com/hyperledger-labs/fabric-smart-client/platform/fabric/driver"
	"github.com/hyperledger-labs/fabric-smart-client/platform/view/view"
)

type FakeTransactionManager struct {
	AddTransactionFactoryStub        func(driver.TransactionType, driver.TransactionFactory)
	addTransactionFactoryMutex       sync.RWMutex
	addTransactionFactoryArgsForCall []struct {
		arg1 driver.TransactionType
		arg2 driver.TransactionFactory
	}
	ComputeTxIDStub        func(*driver.TxIDComponents) string
	computeTxIDMutex       sync.RWMutex
	computeTxIDArgsForCall []struct {
		arg1 *driver.TxIDComponents
	}
	computeTxIDReturns struct {
		result1 string
	}
	computeTxIDReturnsOnCall map[int]struct {
		result1 string
	}
	NewEnvelopeStub        func() driver.Envelope
	newEnvelopeMutex       sync.RWMutex
	newEnvelopeArgsForCall []struct {
	}
	newEnvelopeReturns struct {
		result1 driver.Envelope
	}
	newEnvelopeReturnsOnCall map[int]struct {
		result1 driver.Envelope
	}
	NewProcessedTransactionStub        func([]byte) (driver.ProcessedTransaction, error)
	newProcessedTransactionMutex       sync.RWMutex
	newProcessedTransactionArgsForCall []struct {
		arg1 []byte
	}
	newProcessedTransactionReturns struct {
		result1 driver.ProcessedTransaction
		result2 error
	}
	newProcessedTransactionReturnsOnCall map[int]struct {
		result1 driver.ProcessedTransaction
		result2 error
	}
	NewProcessedTransactionFromEnvelopePayloadStub        func([]byte) (driver.ProcessedTransaction, int32, error)
	newProcessedTransactionFromEnvelopePayloadMutex       sync.RWMutex
	newProcessedTransactionFromEnvelopePayloadArgsForCall []struct {
		arg1 []byte
	}
	newProcessedTransactionFromEnvelopePayloadReturns struct {
		result1 driver.ProcessedTransaction
		result2 int32
		result3 error
	}
	newProcessedTransactionFromEnvelopePayloadReturnsOnCall map[int]struct {
		result1 driver.ProcessedTransaction
		result2 int32
		result3 error
	}
	NewProcessedTransactionFromEnvelopeRawStub        func([]byte) (driver.ProcessedTransaction, error)
	newProcessedTransactionFromEnvelopeRawMutex       sync.RWMutex
	newProcessedTransactionFromEnvelopeRawArgsForCall []struct {
		arg1 []byte
	}
	newProcessedTransactionFromEnvelopeRawReturns struct {
		result1 driver.ProcessedTransaction
		result2 error
	}
	newProcessedTransactionFromEnvelopeRawReturnsOnCall map[int]struct {
		result1 driver.ProcessedTransaction
		result2 error
	}
	NewProposalResponseFromBytesStub        func([]byte) (driver.ProposalResponse, error)
	newProposalResponseFromBytesMutex       sync.RWMutex
	newProposalResponseFromBytesArgsForCall []struct {
		arg1 []byte
	}
	newProposalResponseFromBytesReturns struct {
		result1 driver.ProposalResponse
		result2 error
	}
	newProposalResponseFromBytesReturnsOnCall map[int]struct {
		result1 driver.ProposalResponse
		result2 error
	}
	NewTransactionStub        func(context.Context, driver.TransactionType, view.Identity, []byte, string, string, []byte) (driver.Transaction, error)
	newTransactionMutex       sync.RWMutex
	newTransactionArgsForCall []struct {
		arg1 context.Context
		arg2 driver.TransactionType
		arg3 view.Identity
		arg4 []byte
		arg5 string
		arg6 string
		arg7 []byte
	}
	newTransactionReturns struct {
		result1 driver.Transaction
		result2 error
	}
	newTransactionReturnsOnCall map[int]struct {
		result1 driver.Transaction
		result2 error
	}
	NewTransactionFromBytesStub        func(context.Context, string, []byte) (driver.Transaction, error)
	newTransactionFromBytesMutex       sync.RWMutex
	newTransactionFromBytesArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 []byte
	}
	newTransactionFromBytesReturns struct {
		result1 driver.Transaction
		result2 error
	}
	newTransactionFromBytesReturnsOnCall map[int]struct {
		result1 driver.Transaction
		result2 error
	}
	NewTransactionFromEnvelopeBytesStub        func(context.Context, string, []byte) (driver.Transaction, error)
	newTransactionFromEnvelopeBytesMutex       sync.RWMutex
	newTransactionFromEnvelopeBytesArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 []byte
	}
	newTransactionFromEnvelopeBytesReturns struct {
		result1 driver.Transaction
		result2 error
	}
	newTransactionFromEnvelopeBytesReturnsOnCall map[int]struct {
		result1 driver.Transaction
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTransactionManager) AddTransactionFactory(arg1 driver.TransactionType, arg2 driver.TransactionFactory) {
	fake.addTransactionFactoryMutex.Lock()
	fake.addTransactionFactoryArgsForCall = append(fake.addTransactionFactoryArgsForCall, struct {
		arg1 driver.TransactionType
		arg2 driver.TransactionFactory
	}{arg1, arg2})
	stub := fake.AddTransactionFactoryStub
	fake.recordInvocation("AddTransactionFactory", []interface{}{arg1, arg2})
	fake.addTransactionFactoryMutex.Unlock()
	if stub != nil {
		fake.AddTransactionFactoryStub(arg1, arg2)
	}
}

func (fake *FakeTransactionManager) AddTransactionFactoryCallCount() int {
	fake.addTransactionFactoryMutex.RLock()
	defer fake.addTransactionFactoryMutex.RUnlock()
	return len(fake.addTransactionFactoryArgsForCall)
}

func (fake *FakeTransactionManager) AddTransactionFactoryCalls(stub func(driver.TransactionType, driver.TransactionFactory)) {
	fake.addTransactionFactoryMutex.Lock()
	defer fake.addTransactionFactoryMutex.Unlock()
	fake.AddTransactionFactoryStub = stub
}

func (fake *FakeTransactionManager) AddTransactionFactoryArgsForCall(i int) (driver.TransactionType, driver.TransactionFactory) {
	fake.addTransactionFactoryMutex.RLock()
	defer fake.addTransactionFactoryMutex.RUnlock()
	argsForCall := fake.addTransactionFactoryArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeTransactionManager) ComputeTxID(arg1 *driver.TxIDComponents) string {
	fake.computeTxIDMutex.Lock()
	ret, specificReturn := fake.computeTxIDReturnsOnCall[len(fake.computeTxIDArgsForCall)]
	fake.computeTxIDArgsForCall = append(fake.computeTxIDArgsForCall, struct {
		arg1 *driver.TxIDComponents
	}{arg1})
	stub := fake.ComputeTxIDStub
	fakeReturns := fake.computeTxIDReturns
	fake.recordInvocation("ComputeTxID", []interface{}{arg1})
	fake.computeTxIDMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeTransactionManager) ComputeTxIDCallCount() int {
	fake.computeTxIDMutex.RLock()
	defer fake.computeTxIDMutex.RUnlock()
	return len(fake.computeTxIDArgsForCall)
}

func (fake *FakeTransactionManager) ComputeTxIDCalls(stub func(*driver.TxIDComponents) string) {
	fake.computeTxIDMutex.Lock()
	defer fake.computeTxIDMutex.Unlock()
	fake.ComputeTxIDStub = stub
}

func (fake *FakeTransactionManager) ComputeTxIDArgsForCall(i int) *driver.TxIDComponents {
	fake.computeTxIDMutex.RLock()
	defer fake.computeTxIDMutex.RUnlock()
	argsForCall := fake.computeTxIDArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeTransactionManager) ComputeTxIDReturns(result1 string) {
	fake.computeTxIDMutex.Lock()
	defer fake.computeTxIDMutex.Unlock()
	fake.ComputeTxIDStub = nil
	fake.computeTxIDReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeTransactionManager) ComputeTxIDReturnsOnCall(i int, result1 string) {
	fake.computeTxIDMutex.Lock()
	defer fake.computeTxIDMutex.Unlock()
	fake.ComputeTxIDStub = nil
	if fake.computeTxIDReturnsOnCall == nil {
		fake.computeTxIDReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.computeTxIDReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeTransactionManager) NewEnvelope() driver.Envelope {
	fake.newEnvelopeMutex.Lock()
	ret, specificReturn := fake.newEnvelopeReturnsOnCall[len(fake.newEnvelopeArgsForCall)]
	fake.newEnvelopeArgsForCall = append(fake.newEnvelopeArgsForCall, struct {
	}{})
	stub := fake.NewEnvelopeStub
	fakeReturns := fake.newEnvelopeReturns
	fake.recordInvocation("NewEnvelope", []interface{}{})
	fake.newEnvelopeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeTransactionManager) NewEnvelopeCallCount() int {
	fake.newEnvelopeMutex.RLock()
	defer fake.newEnvelopeMutex.RUnlock()
	return len(fake.newEnvelopeArgsForCall)
}

func (fake *FakeTransactionManager) NewEnvelopeCalls(stub func() driver.Envelope) {
	fake.newEnvelopeMutex.Lock()
	defer fake.newEnvelopeMutex.Unlock()
	fake.NewEnvelopeStub = stub
}

func (fake *FakeTransactionManager) NewEnvelopeReturns(result1 driver.Envelope) {
	fake.newEnvelopeMutex.Lock()
	defer fake.newEnvelopeMutex.Unlock()
	fake.NewEnvelopeStub = nil
	fake.newEnvelopeReturns = struct {
		result1 driver.Envelope
	}{result1}
}

func (fake *FakeTransactionManager) NewEnvelopeReturnsOnCall(i int, result1 driver.Envelope) {
	fake.newEnvelopeMutex.Lock()
	defer fake.newEnvelopeMutex.Unlock()
	fake.NewEnvelopeStub = nil
	if fake.newEnvelopeReturnsOnCall == nil {
		fake.newEnvelopeReturnsOnCall = make(map[int]struct {
			result1 driver.Envelope
		})
	}
	fake.newEnvelopeReturnsOnCall[i] = struct {
		result1 driver.Envelope
	}{result1}
}

func (fake *FakeTransactionManager) NewProcessedTransaction(arg1 []byte) (driver.ProcessedTransaction, error) {
	var arg1Copy []byte
	if arg1 != nil {
		arg1Copy = make([]byte, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.newProcessedTransactionMutex.Lock()
	ret, specificReturn := fake.newProcessedTransactionReturnsOnCall[len(fake.newProcessedTransactionArgsForCall)]
	fake.newProcessedTransactionArgsForCall = append(fake.newProcessedTransactionArgsForCall, struct {
		arg1 []byte
	}{arg1Copy})
	stub := fake.NewProcessedTransactionStub
	fakeReturns := fake.newProcessedTransactionReturns
	fake.recordInvocation("NewProcessedTransaction", []interface{}{arg1Copy})
	fake.newProcessedTransactionMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTransactionManager) NewProcessedTransactionCallCount() int {
	fake.newProcessedTransactionMutex.RLock()
	defer fake.newProcessedTransactionMutex.RUnlock()
	return len(fake.newProcessedTransactionArgsForCall)
}

func (fake *FakeTransactionManager) NewProcessedTransactionCalls(stub func([]byte) (driver.ProcessedTransaction, error)) {
	fake.newProcessedTransactionMutex.Lock()
	defer fake.newProcessedTransactionMutex.Unlock()
	fake.NewProcessedTransactionStub = stub
}

func (fake *FakeTransactionManager) NewProcessedTransactionArgsForCall(i int) []byte {
	fake.newProcessedTransactionMutex.RLock()
	defer fake.newProcessedTransactionMutex.RUnlock()
	argsForCall := fake.newProcessedTransactionArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeTransactionManager) NewProcessedTransactionReturns(result1 driver.ProcessedTransaction, result2 error) {
	fake.newProcessedTransactionMutex.Lock()
	defer fake.newProcessedTransactionMutex.Unlock()
	fake.NewProcessedTransactionStub = nil
	fake.newProcessedTransactionReturns = struct {
		result1 driver.ProcessedTransaction
		result2 error
	}{result1, result2}
}

func (fake *FakeTransactionManager) NewProcessedTransactionReturnsOnCall(i int, result1 driver.ProcessedTransaction, result2 error) {
	fake.newProcessedTransactionMutex.Lock()
	defer fake.newProcessedTransactionMutex.Unlock()
	fake.NewProcessedTransactionStub = nil
	if fake.newProcessedTransactionReturnsOnCall == nil {
		fake.newProcessedTransactionReturnsOnCall = make(map[int]struct {
			result1 driver.ProcessedTransaction
			result2 error
		})
	}
	fake.newProcessedTransactionReturnsOnCall[i] = struct {
		result1 driver.ProcessedTransaction
		result2 error
	}{result1, result2}
}

func (fake *FakeTransactionManager) NewProcessedTransactionFromEnvelopePayload(arg1 []byte) (driver.ProcessedTransaction, int32, error) {
	var arg1Copy []byte
	if arg1 != nil {
		arg1Copy = make([]byte, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.newProcessedTransactionFromEnvelopePayloadMutex.Lock()
	ret, specificReturn := fake.newProcessedTransactionFromEnvelopePayloadReturnsOnCall[len(fake.newProcessedTransactionFromEnvelopePayloadArgsForCall)]
	fake.newProcessedTransactionFromEnvelopePayloadArgsForCall = append(fake.newProcessedTransactionFromEnvelopePayloadArgsForCall, struct {
		arg1 []byte
	}{arg1Copy})
	stub := fake.NewProcessedTransactionFromEnvelopePayloadStub
	fakeReturns := fake.newProcessedTransactionFromEnvelopePayloadReturns
	fake.recordInvocation("NewProcessedTransactionFromEnvelopePayload", []interface{}{arg1Copy})
	fake.newProcessedTransactionFromEnvelopePayloadMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeTransactionManager) NewProcessedTransactionFromEnvelopePayloadCallCount() int {
	fake.newProcessedTransactionFromEnvelopePayloadMutex.RLock()
	defer fake.newProcessedTransactionFromEnvelopePayloadMutex.RUnlock()
	return len(fake.newProcessedTransactionFromEnvelopePayloadArgsForCall)
}

func (fake *FakeTransactionManager) NewProcessedTransactionFromEnvelopePayloadCalls(stub func([]byte) (driver.ProcessedTransaction, int32, error)) {
	fake.newProcessedTransactionFromEnvelopePayloadMutex.Lock()
	defer fake.newProcessedTransactionFromEnvelopePayloadMutex.Unlock()
	fake.NewProcessedTransactionFromEnvelopePayloadStub = stub
}

func (fake *FakeTransactionManager) NewProcessedTransactionFromEnvelopePayloadArgsForCall(i int) []byte {
	fake.newProcessedTransactionFromEnvelopePayloadMutex.RLock()
	defer fake.newProcessedTransactionFromEnvelopePayloadMutex.RUnlock()
	argsForCall := fake.newProcessedTransactionFromEnvelopePayloadArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeTransactionManager) NewProcessedTransactionFromEnvelopePayloadReturns(result1 driver.ProcessedTransaction, result2 int32, result3 error) {
	fake.newProcessedTransactionFromEnvelopePayloadMutex.Lock()
	defer fake.newProcessedTransactionFromEnvelopePayloadMutex.Unlock()
	fake.NewProcessedTransactionFromEnvelopePayloadStub = nil
	fake.newProcessedTransactionFromEnvelopePayloadReturns = struct {
		result1 driver.ProcessedTransaction
		result2 int32
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeTransactionManager) NewProcessedTransactionFromEnvelopePayloadReturnsOnCall(i int, result1 driver.ProcessedTransaction, result2 int32, result3 error) {
	fake.newProcessedTransactionFromEnvelopePayloadMutex.Lock()
	defer fake.newProcessedTransactionFromEnvelopePayloadMutex.Unlock()
	fake.NewProcessedTransactionFromEnvelopePayloadStub = nil
	if fake.newProcessedTransactionFromEnvelopePayloadReturnsOnCall == nil {
		fake.newProcessedTransactionFromEnvelopePayloadReturnsOnCall = make(map[int]struct {
			result1 driver.ProcessedTransaction
			result2 int32
			result3 error
		})
	}
	fake.newProcessedTransactionFromEnvelopePayloadReturnsOnCall[i] = struct {
		result1 driver.ProcessedTransaction
		result2 int32
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeTransactionManager) NewProcessedTransactionFromEnvelopeRaw(arg1 []byte) (driver.ProcessedTransaction, error) {
	var arg1Copy []byte
	if arg1 != nil {
		arg1Copy = make([]byte, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.newProcessedTransactionFromEnvelopeRawMutex.Lock()
	ret, specificReturn := fake.newProcessedTransactionFromEnvelopeRawReturnsOnCall[len(fake.newProcessedTransactionFromEnvelopeRawArgsForCall)]
	fake.newProcessedTransactionFromEnvelopeRawArgsForCall = append(fake.newProcessedTransactionFromEnvelopeRawArgsForCall, struct {
		arg1 []byte
	}{arg1Copy})
	stub := fake.NewProcessedTransactionFromEnvelopeRawStub
	fakeReturns := fake.newProcessedTransactionFromEnvelopeRawReturns
	fake.recordInvocation("NewProcessedTransactionFromEnvelopeRaw", []interface{}{arg1Copy})
	fake.newProcessedTransactionFromEnvelopeRawMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTransactionManager) NewProcessedTransactionFromEnvelopeRawCallCount() int {
	fake.newProcessedTransactionFromEnvelopeRawMutex.RLock()
	defer fake.newProcessedTransactionFromEnvelopeRawMutex.RUnlock()
	return len(fake.newProcessedTransactionFromEnvelopeRawArgsForCall)
}

func (fake *FakeTransactionManager) NewProcessedTransactionFromEnvelopeRawCalls(stub func([]byte) (driver.ProcessedTransaction, error)) {
	fake.newProcessedTransactionFromEnvelopeRawMutex.Lock()
	defer fake.newProcessedTransactionFromEnvelopeRawMutex.Unlock()
	fake.NewProcessedTransactionFromEnvelopeRawStub = stub
}

func (fake *FakeTransactionManager) NewProcessedTransactionFromEnvelopeRawArgsForCall(i int) []byte {
	fake.newProcessedTransactionFromEnvelopeRawMutex.RLock()
	defer fake.newProcessedTransactionFromEnvelopeRawMutex.RUnlock()
	argsForCall := fake.newProcessedTransactionFromEnvelopeRawArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeTransactionManager) NewProcessedTransactionFromEnvelopeRawReturns(result1 driver.ProcessedTransaction, result2 error) {
	fake.newProcessedTransactionFromEnvelopeRawMutex.Lock()
	defer fake.newProcessedTransactionFromEnvelopeRawMutex.Unlock()
	fake.NewProcessedTransactionFromEnvelopeRawStub = nil
	fake.newProcessedTransactionFromEnvelopeRawReturns = struct {
		result1 driver.ProcessedTransaction
		result2 error
	}{result1, result2}
}

func (fake *FakeTransactionManager) NewProcessedTransactionFromEnvelopeRawReturnsOnCall(i int, result1 driver.ProcessedTransaction, result2 error) {
	fake.newProcessedTransactionFromEnvelopeRawMutex.Lock()
	defer fake.newProcessedTransactionFromEnvelopeRawMutex.Unlock()
	fake.NewProcessedTransactionFromEnvelopeRawStub = nil
	if fake.newProcessedTransactionFromEnvelopeRawReturnsOnCall == nil {
		fake.newProcessedTransactionFromEnvelopeRawReturnsOnCall = make(map[int]struct {
			result1 driver.ProcessedTransaction
			result2 error
		})
	}
	fake.newProcessedTransactionFromEnvelopeRawReturnsOnCall[i] = struct {
		result1 driver.ProcessedTransaction
		result2 error
	}{result1, result2}
}

func (fake *FakeTransactionManager) NewProposalResponseFromBytes(arg1 []byte) (driver.ProposalResponse, error) {
	var arg1Copy []byte
	if arg1 != nil {
		arg1Copy = make([]byte, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.newProposalResponseFromBytesMutex.Lock()
	ret, specificReturn := fake.newProposalResponseFromBytesReturnsOnCall[len(fake.newProposalResponseFromBytesArgsForCall)]
	fake.newProposalResponseFromBytesArgsForCall = append(fake.newProposalResponseFromBytesArgsForCall, struct {
		arg1 []byte
	}{arg1Copy})
	stub := fake.NewProposalResponseFromBytesStub
	fakeReturns := fake.newProposalResponseFromBytesReturns
	fake.recordInvocation("NewProposalResponseFromBytes", []interface{}{arg1Copy})
	fake.newProposalResponseFromBytesMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTransactionManager) NewProposalResponseFromBytesCallCount() int {
	fake.newProposalResponseFromBytesMutex.RLock()
	defer fake.newProposalResponseFromBytesMutex.RUnlock()
	return len(fake.newProposalResponseFromBytesArgsForCall)
}

func (fake *FakeTransactionManager) NewProposalResponseFromBytesCalls(stub func([]byte) (driver.ProposalResponse, error)) {
	fake.newProposalResponseFromBytesMutex.Lock()
	defer fake.newProposalResponseFromBytesMutex.Unlock()
	fake.NewProposalResponseFromBytesStub = stub
}

func (fake *FakeTransactionManager) NewProposalResponseFromBytesArgsForCall(i int) []byte {
	fake.newProposalResponseFromBytesMutex.RLock()
	defer fake.newProposalResponseFromBytesMutex.RUnlock()
	argsForCall := fake.newProposalResponseFromBytesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeTransactionManager) NewProposalResponseFromBytesReturns(result1 driver.ProposalResponse, result2 error) {
	fake.newProposalResponseFromBytesMutex.Lock()
	defer fake.newProposalResponseFromBytesMutex.Unlock()
	fake.NewProposalResponseFromBytesStub = nil
	fake.newProposalResponseFromBytesReturns = struct {
		result1 driver.ProposalResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeTransactionManager) NewProposalResponseFromBytesReturnsOnCall(i int, result1 driver.ProposalResponse, result2 error) {
	fake.newProposalResponseFromBytesMutex.Lock()
	defer fake.newProposalResponseFromBytesMutex.Unlock()
	fake.NewProposalResponseFromBytesStub = nil
	if fake.newProposalResponseFromBytesReturnsOnCall == nil {
		fake.newProposalResponseFromBytesReturnsOnCall = make(map[int]struct {
			result1 driver.ProposalResponse
			result2 error
		})
	}
	fake.newProposalResponseFromBytesReturnsOnCall[i] = struct {
		result1 driver.ProposalResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeTransactionManager) NewTransaction(arg1 context.Context, arg2 driver.TransactionType, arg3 view.Identity, arg4 []byte, arg5 string, arg6 string, arg7 []byte) (driver.Transaction, error) {
	var arg4Copy []byte
	if arg4 != nil {
		arg4Copy = make([]byte, len(arg4))
		copy(arg4Copy, arg4)
	}
	var arg7Copy []byte
	if arg7 != nil {
		arg7Copy = make([]byte, len(arg7))
		copy(arg7Copy, arg7)
	}
	fake.newTransactionMutex.Lock()
	ret, specificReturn := fake.newTransactionReturnsOnCall[len(fake.newTransactionArgsForCall)]
	fake.newTransactionArgsForCall = append(fake.newTransactionArgsForCall, struct {
		arg1 context.Context
		arg2 driver.TransactionType
		arg3 view.Identity
		arg4 []byte
		arg5 string
		arg6 string
		arg7 []byte
	}{arg1, arg2, arg3, arg4Copy, arg5, arg6, arg7Copy})
	stub := fake.NewTransactionStub
	fakeReturns := fake.newTransactionReturns
	fake.recordInvocation("NewTransaction", []interface{}{arg1, arg2, arg3, arg4Copy, arg5, arg6, arg7Copy})
	fake.newTransactionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5, arg6, arg7)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTransactionManager) NewTransactionCallCount() int {
	fake.newTransactionMutex.RLock()
	defer fake.newTransactionMutex.RUnlock()
	return len(fake.newTransactionArgsForCall)
}

func (fake *FakeTransactionManager) NewTransactionCalls(stub func(context.Context, driver.TransactionType, view.Identity, []byte, string, string, []byte) (driver.Transaction, error)) {
	fake.newTransactionMutex.Lock()
	defer fake.newTransactionMutex.Unlock()
	fake.NewTransactionStub = stub
}

func (fake *FakeTransactionManager) NewTransactionArgsForCall(i int) (context.Context, driver.TransactionType, view.Identity, []byte, string, string, []byte) {
	fake.newTransactionMutex.RLock()
	defer fake.newTransactionMutex.RUnlock()
	argsForCall := fake.newTransactionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5, argsForCall.arg6, argsForCall.arg7
}

func (fake *FakeTransactionManager) NewTransactionReturns(result1 driver.Transaction, result2 error) {
	fake.newTransactionMutex.Lock()
	defer fake.newTransactionMutex.Unlock()
	fake.NewTransactionStub = nil
	fake.newTransactionReturns = struct {
		result1 driver.Transaction
		result2 error
	}{result1, result2}
}

func (fake *FakeTransactionManager) NewTransactionReturnsOnCall(i int, result1 driver.Transaction, result2 error) {
	fake.newTransactionMutex.Lock()
	defer fake.newTransactionMutex.Unlock()
	fake.NewTransactionStub = nil
	if fake.newTransactionReturnsOnCall == nil {
		fake.newTransactionReturnsOnCall = make(map[int]struct {
			result1 driver.Transaction
			result2 error
		})
	}
	fake.newTransactionReturnsOnCall[i] = struct {
		result1 driver.Transaction
		result2 error
	}{result1, result2}
}

func (fake *FakeTransactionManager) NewTransactionFromBytes(arg1 context.Context, arg2 string, arg3 []byte) (driver.Transaction, error) {
	var arg3Copy []byte
	if arg3 != nil {
		arg3Copy = make([]byte, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.newTransactionFromBytesMutex.Lock()
	ret, specificReturn := fake.newTransactionFromBytesReturnsOnCall[len(fake.newTransactionFromBytesArgsForCall)]
	fake.newTransactionFromBytesArgsForCall = append(fake.newTransactionFromBytesArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 []byte
	}{arg1, arg2, arg3Copy})
	stub := fake.NewTransactionFromBytesStub
	fakeReturns := fake.newTransactionFromBytesReturns
	fake.recordInvocation("NewTransactionFromBytes", []interface{}{arg1, arg2, arg3Copy})
	fake.newTransactionFromBytesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTransactionManager) NewTransactionFromBytesCallCount() int {
	fake.newTransactionFromBytesMutex.RLock()
	defer fake.newTransactionFromBytesMutex.RUnlock()
	return len(fake.newTransactionFromBytesArgsForCall)
}

func (fake *FakeTransactionManager) NewTransactionFromBytesCalls(stub func(context.Context, string, []byte) (driver.Transaction, error)) {
	fake.newTransactionFromBytesMutex.Lock()
	defer fake.newTransactionFromBytesMutex.Unlock()
	fake.NewTransactionFromBytesStub = stub
}

func (fake *FakeTransactionManager) NewTransactionFromBytesArgsForCall(i int) (context.Context, string, []byte) {
	fake.newTransactionFromBytesMutex.RLock()
	defer fake.newTransactionFromBytesMutex.RUnlock()
	argsForCall := fake.newTransactionFromBytesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeTransactionManager) NewTransactionFromBytesReturns(result1 driver.Transaction, result2 error) {
	fake.newTransactionFromBytesMutex.Lock()
	defer fake.newTransactionFromBytesMutex.Unlock()
	fake.NewTransactionFromBytesStub = nil
	fake.newTransactionFromBytesReturns = struct {
		result1 driver.Transaction
		result2 error
	}{result1, result2}
}

func (fake *FakeTransactionManager) NewTransactionFromBytesReturnsOnCall(i int, result1 driver.Transaction, result2 error) {
	fake.newTransactionFromBytesMutex.Lock()
	defer fake.newTransactionFromBytesMutex.Unlock()
	fake.NewTransactionFromBytesStub = nil
	if fake.newTransactionFromBytesReturnsOnCall == nil {
		fake.newTransactionFromBytesReturnsOnCall = make(map[int]struct {
			result1 driver.Transaction
			result2 error
		})
	}
	fake.newTransactionFromBytesReturnsOnCall[i] = struct {
		result1 driver.Transaction
		result2 error
	}{result1, result2}
}

func (fake *FakeTransactionManager) NewTransactionFromEnvelopeBytes(arg1 context.Context, arg2 string, arg3 []byte) (driver.Transaction, error) {
	var arg3Copy []byte
	if arg3 != nil {
		arg3Copy = make([]byte, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.newTransactionFromEnvelopeBytesMutex.Lock()
	ret, specificReturn := fake.newTransactionFromEnvelopeBytesReturnsOnCall[len(fake.newTransactionFromEnvelopeBytesArgsForCall)]
	fake.newTransactionFromEnvelopeBytesArgsForCall = append(fake.newTransactionFromEnvelopeBytesArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 []byte
	}{arg1, arg2, arg3Copy})
	stub := fake.NewTransactionFromEnvelopeBytesStub
	fakeReturns := fake.newTransactionFromEnvelopeBytesReturns
	fake.recordInvocation("NewTransactionFromEnvelopeBytes", []interface{}{arg1, arg2, arg3Copy})
	fake.newTransactionFromEnvelopeBytesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTransactionManager) NewTransactionFromEnvelopeBytesCallCount() int {
	fake.newTransactionFromEnvelopeBytesMutex.RLock()
	defer fake.newTransactionFromEnvelopeBytesMutex.RUnlock()
	return len(fake.newTransactionFromEnvelopeBytesArgsForCall)
}

func (fake *FakeTransactionManager) NewTransactionFromEnvelopeBytesCalls(stub func(context.Context, string, []byte) (driver.Transaction, error)) {
	fake.newTransactionFromEnvelopeBytesMutex.Lock()
	defer fake.newTransactionFromEnvelopeBytesMutex.Unlock()
	fake.NewTransactionFromEnvelopeBytesStub = stub
}

func (fake *FakeTransactionManager) NewTransactionFromEnvelopeBytesArgsForCall(i int) (context.Context, string, []byte) {
	fake.newTransactionFromEnvelopeBytesMutex.RLock()
	defer fake.newTransactionFromEnvelopeBytesMutex.RUnlock()
	argsForCall := fake.newTransactionFromEnvelopeBytesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeTransactionManager) NewTransactionFromEnvelopeBytesReturns(result1 driver.Transaction, result2 error) {
	fake.newTransactionFromEnvelopeBytesMutex.Lock()
	defer fake.newTransactionFromEnvelopeBytesMutex.Unlock()
	fake.NewTransactionFromEnvelopeBytesStub = nil
	fake.newTransactionFromEnvelopeBytesReturns = struct {
		result1 driver.Transaction
		result2 error
	}{result1, result2}
}

func (fake *FakeTransactionManager) NewTransactionFromEnvelopeBytesReturnsOnCall(i int, result1 driver.Transaction, result2 error) {
	fake.newTransactionFromEnvelopeBytesMutex.Lock()
	defer fake.newTransactionFromEnvelopeBytesMutex.Unlock()
	fake.NewTransactionFromEnvelopeBytesStub = nil
	if fake.newTransactionFromEnvelopeBytesReturnsOnCall == nil {
		fake.newTransactionFromEnvelopeBytesReturnsOnCall = make(map[int]struct {
			result1 driver.Transaction
			result2 error
		})
	}
	fake.newTransactionFromEnvelopeBytesReturnsOnCall[i] = struct {
		result1 driver.Transaction
		result2 error
	}{result1, result2}
}

func (fake *FakeTransactionManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeTransactionManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ driver.TransactionManager = new(FakeTransactionManager)
