// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"sync"

	"github.com/hyperledger-labs/fabric-smart-client/platform/fabric/driver"
)

type FakeChaincodeManager struct {
	ChaincodeStub        func(string) driver.Chaincode
	chaincodeMutex       sync.RWMutex
	chaincodeArgsForCall []struct {
		arg1 string
	}
	chaincodeReturns struct {
		result1 driver.Chaincode
	}
	chaincodeReturnsOnCall map[int]struct {
		result1 driver.Chaincode
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeChaincodeManager) Chaincode(arg1 string) driver.Chaincode {
	fake.chaincodeMutex.Lock()
	ret, specificReturn := fake.chaincodeReturnsOnCall[len(fake.chaincodeArgsForCall)]
	fake.chaincodeArgsForCall = append(fake.chaincodeArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ChaincodeStub
	fakeReturns := fake.chaincodeReturns
	fake.recordInvocation("Chaincode", []interface{}{arg1})
	fake.chaincodeMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeChaincodeManager) ChaincodeCallCount() int {
	fake.chaincodeMutex.RLock()
	defer fake.chaincodeMutex.RUnlock()
	return len(fake.chaincodeArgsForCall)
}

func (fake *FakeChaincodeManager) ChaincodeCalls(stub func(string) driver.Chaincode) {
	fake.chaincodeMutex.Lock()
	defer fake.chaincodeMutex.Unlock()
	fake.ChaincodeStub = stub
}

func (fake *FakeChaincodeManager) ChaincodeArgsForCall(i int) string {
	fake.chaincodeMutex.RLock()
	defer fake.chaincodeMutex.RUnlock()
	argsForCall := fake.chaincodeArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeChaincodeManager) ChaincodeReturns(result1 driver.Chaincode) {
	fake.chaincodeMutex.Lock()
	defer fake.chaincodeMutex.Unlock()
	fake.ChaincodeStub = nil
	fake.chaincodeReturns = struct {
		result1 driver.Chaincode
	}{result1}
}

func (fake *FakeChaincodeManager) ChaincodeReturnsOnCall(i int, result1 driver.Chaincode) {
	fake.chaincodeMutex.Lock()
	defer fake.chaincodeMutex.Unlock()
	fake.ChaincodeStub = nil
	if fake.chaincodeReturnsOnCall == nil {
		fake.chaincodeReturnsOnCall = make(map[int]struct {
			result1 driver.Chaincode
		})
	}
	fake.chaincodeReturnsOnCall[i] = struct {
		result1 driver.Chaincode
	}{result1}
}

func (fake *FakeChaincodeManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeChaincodeManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ driver.ChaincodeManager = new(FakeChaincodeManager)
