name: Git Checks

on: [pull_request]

jobs:
  block-fixup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7.0.1
      - name: Block Fixup Commit Merge
        uses: 13rac1/block-fixup-merge-action@bd5504fb9ca0253e109d98eb86b7debc01970cdc # ratchet:13rac1/block-fixup-merge-action@v2.0.0

  go-mod-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # ratchet:actions/setup-go@v7.0.0
        with:
          go-version-file: "go.mod"
          cache-dependency-path: "**/*.sum"
      - run: make tidy
      - name: Check for diffs
        run: |
          git diff --exit-code || {
            echo "Please run 'make tidy' and commit the changes";
            exit 1;
          }
